-- NACL-test fictional dataset: Central Alberta Steel Open-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('74b587d8-93f2-5031-9885-a60b7a517664', 'central-alberta-steel-open-test', 'Central Alberta Steel Open-test', 'The first NACL-test calendar event: a one-weekend open for the founding Alberta clubs.', 'tournament', 'published', 'Westerner Park Arena-test', 'Red Deer', 'AB', 'CA', 'America/Edmonton', 0, date '2023-05-27', date '2023-05-28', '4842a217-7f85-509f-aa7e-cefa2bffbfab', 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', '74b587d8-93f2-5031-9885-a60b7a517664', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('74b587d8-93f2-5031-9885-a60b7a517664', '0538dd11-8537-5f9c-b2fe-918f45b21bc0');
select public.set_event_organization('74b587d8-93f2-5031-9885-a60b7a517664', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('6c090d10-08ee-5a45-bd5f-8e381181ffc1', '74b587d8-93f2-5031-9885-a60b7a517664', 'Male 5v5', '5v5', 'men', 'Source', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('288cdb75-8886-5e19-9ad6-adb155eb6369', '74b587d8-93f2-5031-9885-a60b7a517664', 'Male Longsword', 'longsword', 'men', 'Source', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 20),
  ('ad09ff4f-148c-598b-9320-5bccef57ec7d', '74b587d8-93f2-5031-9885-a60b7a517664', 'Female Longsword', 'longsword', 'women', 'Source', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 30),
  ('f091a4e0-c909-5941-b272-52d5db074198', '74b587d8-93f2-5031-9885-a60b7a517664', 'Male Sword & Shield', 'sword_shield', 'men', 'Source', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 40)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('bb9e840f-7f99-54e6-b046-59b87c0e0e5d', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('ccdfeac3-6ac8-5ace-a396-a39fd15040e1', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', '5796049c-2e49-521c-b959-47744fa8c73f', null, 'checked_in'),
  ('31d44ae9-5434-5555-8a72-8b0018bf005d', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', '52287cd0-9f3e-5911-9538-ce229cf0362b', null, 'checked_in'),
  ('30095849-d8e6-5dc2-b4ad-99afa9916e8a', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, '88af5e4f-d812-5e43-837b-5eb6dbb92226', 'checked_in'),
  ('1fd6256d-2fd3-5715-a986-86b1208a4173', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, '49c189e3-a1f5-5342-b03f-965e69b3406c', 'checked_in'),
  ('85bb66d1-fe1d-5941-bd04-d087b434dacd', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, 'd2ea0e0b-da23-5e24-802d-85145d3f616f', 'checked_in'),
  ('f1271493-6e15-53c0-9800-945beff8228e', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, '7df00fd3-0d78-5dbe-b0c7-eeaceda48ddb', 'checked_in'),
  ('c048fd16-5505-5217-8de0-b53123efc5cf', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, '3675139b-aab7-5d9b-b009-cb9386485d08', 'checked_in'),
  ('4f2d7732-b5a9-543c-a16f-a05b0101c70f', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, '8bf5a2df-8b24-5bae-b6cf-03c0dad81870', 'checked_in'),
  ('79987f17-d4f9-5a54-8377-3b2fd8b1660d', '288cdb75-8886-5e19-9ad6-adb155eb6369', null, 'dc6ad18c-6ea3-5243-b794-7098006f2790', 'checked_in'),
  ('aba4c80f-3cfd-553f-a3d4-bf348a08a1e0', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', null, 'f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61', 'checked_in'),
  ('192f94ff-a940-5707-b8b4-2fb2f38dd2c8', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', null, 'a92a1c83-58d6-572d-9736-27fde0c87cf7', 'checked_in'),
  ('62167570-c392-500c-ac50-5eb99cf8ee4d', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', null, 'ccd25c59-7eec-5757-bff1-3437c26baed8', 'checked_in'),
  ('89f6246f-b762-5051-a824-f7c4c85c2fc8', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', null, 'd1b9ab79-147f-5ab9-9356-0ebb9f9bcc40', 'checked_in'),
  ('a4b30200-02ae-55b4-9333-7acb704daf8c', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', null, 'a84d9159-737e-54fd-ad21-cbbe6152d754', 'checked_in'),
  ('8bb70a10-d691-5c87-9eb5-b235d3bf4866', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', null, '9890f7c8-373a-5cf8-b06c-34ea20a58304', 'checked_in'),
  ('ef026627-9ce0-5178-b1f4-11be1d7e786d', 'f091a4e0-c909-5941-b272-52d5db074198', null, '33dae536-85e7-5060-a8b0-8eed569e82d3', 'checked_in'),
  ('86454338-fe8e-5a4f-86c1-cf82f139b926', 'f091a4e0-c909-5941-b272-52d5db074198', null, 'a6d7fbe4-0392-5679-9e83-3a4693aa452d', 'checked_in'),
  ('b87776e1-f7ec-5a7f-92f0-9e425608809b', 'f091a4e0-c909-5941-b272-52d5db074198', null, 'bcf07ca4-7db2-527a-a644-5c49ff701df3', 'checked_in'),
  ('fd22c6b9-5e1d-5a0a-bf96-53ba0e3e716a', 'f091a4e0-c909-5941-b272-52d5db074198', null, 'b41fb9fe-c8ec-5405-a0f4-394ee6095b2e', 'checked_in'),
  ('885629ca-1345-5d45-a4e4-b9ea975667f2', 'f091a4e0-c909-5941-b272-52d5db074198', null, '1434a046-cc53-5391-86f0-ecf252a00d87', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('bb9e840f-7f99-54e6-b046-59b87c0e0e5d', '[{"fighter_id":"49c189e3-a1f5-5342-b03f-965e69b3406c","role":"fighter"},{"fighter_id":"b9551194-d28a-50e3-9bfc-36c446fa8f54","role":"fighter"},{"fighter_id":"e0e182fe-bce4-5347-ac8c-ac85f8f10fd5","role":"fighter"},{"fighter_id":"ff6d3454-18ef-5175-9d2b-56f676185804","role":"fighter"},{"fighter_id":"5385df95-b791-5de5-a10f-9db8491e2dbc","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '6c090d10-08ee-5a45-bd5f-8e381181ffc1' and status <> 'finished');
select public.set_entry_roster('ccdfeac3-6ac8-5ace-a396-a39fd15040e1', '[{"fighter_id":"695e3415-b6f8-5182-94d9-d8e4904c74e6","role":"fighter"},{"fighter_id":"7df00fd3-0d78-5dbe-b0c7-eeaceda48ddb","role":"fighter"},{"fighter_id":"bcf07ca4-7db2-527a-a644-5c49ff701df3","role":"fighter"},{"fighter_id":"1fcb6cfe-8069-5c6d-96dd-56ea1b461f7b","role":"fighter"},{"fighter_id":"b41fb9fe-c8ec-5405-a0f4-394ee6095b2e","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '6c090d10-08ee-5a45-bd5f-8e381181ffc1' and status <> 'finished');
select public.set_entry_roster('31d44ae9-5434-5555-8a72-8b0018bf005d', '[{"fighter_id":"8bf5a2df-8b24-5bae-b6cf-03c0dad81870","role":"fighter"},{"fighter_id":"dc6ad18c-6ea3-5243-b794-7098006f2790","role":"fighter"},{"fighter_id":"1434a046-cc53-5391-86f0-ecf252a00d87","role":"fighter"},{"fighter_id":"33dae536-85e7-5060-a8b0-8eed569e82d3","role":"mercenary"},{"fighter_id":"8120e2f4-1510-5cfd-a077-7320c47a52a9","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '6c090d10-08ee-5a45-bd5f-8e381181ffc1' and status <> 'finished');
-- Male 5v5: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('0db51a29-aee5-5ca1-832e-3e92c1710906', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', 'round_robin', 'Round 1', 0, null, '31d44ae9-5434-5555-8a72-8b0018bf005d', 'ccdfeac3-6ac8-5ace-a396-a39fd15040e1', 'Ring 1', (timestamp '2023-05-27 10:00' at time zone 'America/Edmonton'), 15),
  ('cf64b9f3-6678-5218-9941-97c1eaa1a879', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', 'round_robin', 'Round 2', 0, null, 'ccdfeac3-6ac8-5ace-a396-a39fd15040e1', 'bb9e840f-7f99-54e6-b046-59b87c0e0e5d', 'Ring 1', (timestamp '2023-05-27 10:17' at time zone 'America/Edmonton'), 15),
  ('12951a49-1c60-5a1a-960d-6c0a2c567154', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', 'round_robin', 'Round 3', 0, null, 'bb9e840f-7f99-54e6-b046-59b87c0e0e5d', '31d44ae9-5434-5555-8a72-8b0018bf005d', 'Ring 1', (timestamp '2023-05-27 10:34' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '0db51a29-aee5-5ca1-832e-3e92c1710906' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'cf64b9f3-6678-5218-9941-97c1eaa1a879' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '12951a49-1c60-5a1a-960d-6c0a2c567154' and m.queue_state <> 'final';
select public.finish_competition('6c090d10-08ee-5a45-bd5f-8e381181ffc1', 'tournament_structure') where exists (select 1 from public.competitions where id = '6c090d10-08ee-5a45-bd5f-8e381181ffc1' and status <> 'finished');
-- Male Longsword: elimination, 7 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('623eacb8-ce34-5e49-9b00-65d948716c82', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'elimination', 'Quarterfinal', 1, null, '79987f17-d4f9-5a54-8377-3b2fd8b1660d', '4f2d7732-b5a9-543c-a16f-a05b0101c70f', 'Ring 2', (timestamp '2023-05-27 10:00' at time zone 'America/Edmonton'), 8),
  ('99474a63-fec7-5c47-8a6b-c94e73a53371', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'elimination', 'Quarterfinal', 2, null, '85bb66d1-fe1d-5941-bd04-d087b434dacd', '1fd6256d-2fd3-5715-a986-86b1208a4173', 'Ring 2', (timestamp '2023-05-27 10:10' at time zone 'America/Edmonton'), 8),
  ('492e263d-be9e-54fa-9e61-f1deeb27c4f1', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'elimination', 'Quarterfinal', 3, null, 'f1271493-6e15-53c0-9800-945beff8228e', 'c048fd16-5505-5217-8de0-b53123efc5cf', 'Ring 2', (timestamp '2023-05-27 10:20' at time zone 'America/Edmonton'), 8),
  ('a17be935-7b30-5a84-869d-cb4be3d2ba86', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'elimination', 'Semifinal', 0, null, '30095849-d8e6-5dc2-b4ad-99afa9916e8a', null, 'Ring 2', (timestamp '2023-05-27 10:30' at time zone 'America/Edmonton'), 8),
  ('4f0e9e1a-aa70-5a6c-894d-8eabd8c64c43', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2023-05-27 10:40' at time zone 'America/Edmonton'), 8),
  ('abc51e8e-4d83-5237-a6dc-5e3cce5f5cc2', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2023-05-27 10:50' at time zone 'America/Edmonton'), 8),
  ('5d279cbb-a161-5f8f-8e6a-dda9325e16d1', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2023-05-27 11:00' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('623eacb8-ce34-5e49-9b00-65d948716c82'::uuid, 'a17be935-7b30-5a84-869d-cb4be3d2ba86'::uuid, 'b'),
  ('99474a63-fec7-5c47-8a6b-c94e73a53371'::uuid, '4f0e9e1a-aa70-5a6c-894d-8eabd8c64c43'::uuid, 'a'),
  ('492e263d-be9e-54fa-9e61-f1deeb27c4f1'::uuid, '4f0e9e1a-aa70-5a6c-894d-8eabd8c64c43'::uuid, 'b'),
  ('a17be935-7b30-5a84-869d-cb4be3d2ba86'::uuid, 'abc51e8e-4d83-5237-a6dc-5e3cce5f5cc2'::uuid, 'a'),
  ('4f0e9e1a-aa70-5a6c-894d-8eabd8c64c43'::uuid, 'abc51e8e-4d83-5237-a6dc-5e3cce5f5cc2'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,1]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '623eacb8-ce34-5e49-9b00-65d948716c82' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,2]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '99474a63-fec7-5c47-8a6b-c94e73a53371' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[0,1,1,3,0,0],"b":[0,1,2,1,1,2]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '492e263d-be9e-54fa-9e61-f1deeb27c4f1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[1,1,2],"b":[0,2,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'a17be935-7b30-5a84-869d-cb4be3d2ba86' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 2, '{"kind":"duel","rounds":{"a":[7,0],"b":[2,0]},"totals":{"a":7,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '4f0e9e1a-aa70-5a6c-894d-8eabd8c64c43' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,2]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'abc51e8e-4d83-5237-a6dc-5e3cce5f5cc2' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[3,1],"b":[1,0]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '5d279cbb-a161-5f8f-8e6a-dda9325e16d1' and m.queue_state <> 'final';
select public.finish_competition('288cdb75-8886-5e19-9ad6-adb155eb6369', 'tournament_structure') where exists (select 1 from public.competitions where id = '288cdb75-8886-5e19-9ad6-adb155eb6369' and status <> 'finished');
-- Female Longsword: round_robin, 6 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('e7efa0da-a93a-5d8e-a620-e6d9d6e5ea85', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 1', 0, null, 'a4b30200-02ae-55b4-9333-7acb704daf8c', '8bb70a10-d691-5c87-9eb5-b235d3bf4866', 'Ring 3', (timestamp '2023-05-27 10:00' at time zone 'America/Edmonton'), 8),
  ('8bc5ffb4-88b1-5449-8146-4cbe5d086f1f', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 1', 1, null, '89f6246f-b762-5051-a824-f7c4c85c2fc8', '62167570-c392-500c-ac50-5eb99cf8ee4d', 'Ring 3', (timestamp '2023-05-27 10:10' at time zone 'America/Edmonton'), 8),
  ('cc82dc97-01c1-55f7-9c18-d5d6df8f091c', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 1', 2, null, 'aba4c80f-3cfd-553f-a3d4-bf348a08a1e0', '192f94ff-a940-5707-b8b4-2fb2f38dd2c8', 'Ring 3', (timestamp '2023-05-27 10:20' at time zone 'America/Edmonton'), 8),
  ('6e3485f9-6909-5055-b6b5-51a1d3a92224', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 2', 0, null, '62167570-c392-500c-ac50-5eb99cf8ee4d', 'a4b30200-02ae-55b4-9333-7acb704daf8c', 'Ring 3', (timestamp '2023-05-27 10:30' at time zone 'America/Edmonton'), 8),
  ('fa7c01f4-ec25-54aa-b10c-ab113576106c', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 2', 1, null, '8bb70a10-d691-5c87-9eb5-b235d3bf4866', '192f94ff-a940-5707-b8b4-2fb2f38dd2c8', 'Ring 3', (timestamp '2023-05-27 10:40' at time zone 'America/Edmonton'), 8),
  ('59aa5ee5-6e65-5dc3-a661-8f0406cab105', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 2', 2, null, '89f6246f-b762-5051-a824-f7c4c85c2fc8', 'aba4c80f-3cfd-553f-a3d4-bf348a08a1e0', 'Ring 3', (timestamp '2023-05-27 10:50' at time zone 'America/Edmonton'), 8),
  ('8a72d3b6-3da3-5653-ad61-959e72ea989e', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 3', 0, null, 'a4b30200-02ae-55b4-9333-7acb704daf8c', '192f94ff-a940-5707-b8b4-2fb2f38dd2c8', 'Ring 3', (timestamp '2023-05-27 11:00' at time zone 'America/Edmonton'), 8),
  ('582fcb79-5ca2-508c-85e4-8cf9d258c98c', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 3', 1, null, '62167570-c392-500c-ac50-5eb99cf8ee4d', 'aba4c80f-3cfd-553f-a3d4-bf348a08a1e0', 'Ring 3', (timestamp '2023-05-27 11:10' at time zone 'America/Edmonton'), 8),
  ('aa752788-95d5-5c45-9525-3d5aecac043b', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 3', 2, null, '8bb70a10-d691-5c87-9eb5-b235d3bf4866', '89f6246f-b762-5051-a824-f7c4c85c2fc8', 'Ring 3', (timestamp '2023-05-27 11:20' at time zone 'America/Edmonton'), 8),
  ('78828b50-e65a-5bf3-829e-d793f5218949', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 4', 0, null, 'aba4c80f-3cfd-553f-a3d4-bf348a08a1e0', 'a4b30200-02ae-55b4-9333-7acb704daf8c', 'Ring 3', (timestamp '2023-05-27 11:30' at time zone 'America/Edmonton'), 8),
  ('f22ee4b5-87a1-515a-b42e-108b3450e461', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 4', 1, null, '192f94ff-a940-5707-b8b4-2fb2f38dd2c8', '89f6246f-b762-5051-a824-f7c4c85c2fc8', 'Ring 3', (timestamp '2023-05-27 11:40' at time zone 'America/Edmonton'), 8),
  ('9e0695e8-cbd9-5ab3-a78a-ac32730a3d57', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 4', 2, null, '62167570-c392-500c-ac50-5eb99cf8ee4d', '8bb70a10-d691-5c87-9eb5-b235d3bf4866', 'Ring 3', (timestamp '2023-05-27 11:50' at time zone 'America/Edmonton'), 8),
  ('ee3e8f3e-489d-5aa9-9977-aa9c0fd13fff', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 5', 0, null, 'a4b30200-02ae-55b4-9333-7acb704daf8c', '89f6246f-b762-5051-a824-f7c4c85c2fc8', 'Ring 3', (timestamp '2023-05-27 12:00' at time zone 'America/Edmonton'), 8),
  ('dd8ce646-2cee-5a93-b362-454ee3f79512', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 5', 1, null, 'aba4c80f-3cfd-553f-a3d4-bf348a08a1e0', '8bb70a10-d691-5c87-9eb5-b235d3bf4866', 'Ring 3', (timestamp '2023-05-27 12:10' at time zone 'America/Edmonton'), 8),
  ('e3afda1c-b04e-5df3-8b03-df2e5ee3c250', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'round_robin', 'Round 5', 2, null, '192f94ff-a940-5707-b8b4-2fb2f38dd2c8', '62167570-c392-500c-ac50-5eb99cf8ee4d', 'Ring 3', (timestamp '2023-05-27 12:20' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 7, 1, '{"kind":"duel","rounds":{"a":[2,5],"b":[1,0]},"totals":{"a":7,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'e7efa0da-a93a-5d8e-a620-e6d9d6e5ea85' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[1,3,1],"b":[2,1,0]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '8bc5ffb4-88b1-5449-8146-4cbe5d086f1f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 8, 3, '{"kind":"duel","rounds":{"a":[0,2,1,1,4],"b":[2,0,1,0,0]},"totals":{"a":8,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'cc82dc97-01c1-55f7-9c18-d5d6df8f091c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[3,1]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '6e3485f9-6909-5055-b6b5-51a1d3a92224' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,2]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'fa7c01f4-ec25-54aa-b10c-ab113576106c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,3]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '59aa5ee5-6e65-5dc3-a661-8f0406cab105' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[0,4]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '8a72d3b6-3da3-5653-ad61-959e72ea989e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,3]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '582fcb79-5ca2-508c-85e4-8cf9d258c98c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[1,1],"b":[4,1]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'aa752788-95d5-5c45-9525-3d5aecac043b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[1,1,3],"b":[1,0,1]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '78828b50-e65a-5bf3-829e-d793f5218949' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 6, '{"kind":"duel","rounds":{"a":[2,1,1],"b":[1,1,4]},"totals":{"a":4,"b":6}}'::jsonb, m.version) from public.matches m where m.id = 'f22ee4b5-87a1-515a-b42e-108b3450e461' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 7, 9, '{"kind":"duel","rounds":{"a":[1,1,1,0,0,1,1,2],"b":[1,1,1,0,0,1,2,3]},"totals":{"a":7,"b":9}}'::jsonb, m.version) from public.matches m where m.id = '9e0695e8-cbd9-5ab3-a78a-ac32730a3d57' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[1,1],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'ee3e8f3e-489d-5aa9-9977-aa9c0fd13fff' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 1, '{"kind":"duel","rounds":{"a":[5,4],"b":[0,1]},"totals":{"a":9,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'dd8ce646-2cee-5a93-b362-454ee3f79512' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[1,3],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'e3afda1c-b04e-5df3-8b03-df2e5ee3c250' and m.queue_state <> 'final';
select public.finish_competition('ad09ff4f-148c-598b-9320-5bccef57ec7d', 'tournament_structure') where exists (select 1 from public.competitions where id = 'ad09ff4f-148c-598b-9320-5bccef57ec7d' and status <> 'finished');
-- Male Sword & Shield: round_robin, 5 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('3241e7c3-52ae-5606-82a1-f78c321f8b43', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 1', 0, null, 'fd22c6b9-5e1d-5a0a-bf96-53ba0e3e716a', '86454338-fe8e-5a4f-86c1-cf82f139b926', 'Ring 1', (timestamp '2023-05-27 10:51' at time zone 'America/Edmonton'), 8),
  ('f115511d-6896-5336-ae1e-eac560b49781', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 1', 1, null, 'b87776e1-f7ec-5a7f-92f0-9e425608809b', 'ef026627-9ce0-5178-b1f4-11be1d7e786d', 'Ring 1', (timestamp '2023-05-27 11:01' at time zone 'America/Edmonton'), 8),
  ('08eec953-d2b7-5108-98bc-e1a89541590a', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 2', 0, null, '86454338-fe8e-5a4f-86c1-cf82f139b926', '885629ca-1345-5d45-a4e4-b9ea975667f2', 'Ring 1', (timestamp '2023-05-27 11:11' at time zone 'America/Edmonton'), 8),
  ('0fdf20b0-2473-5624-aa1a-b41143519b6c', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 2', 1, null, 'fd22c6b9-5e1d-5a0a-bf96-53ba0e3e716a', 'b87776e1-f7ec-5a7f-92f0-9e425608809b', 'Ring 1', (timestamp '2023-05-27 11:21' at time zone 'America/Edmonton'), 8),
  ('cd23c237-95eb-5fc1-a3e5-94bfd3b897e0', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 3', 0, null, '885629ca-1345-5d45-a4e4-b9ea975667f2', 'ef026627-9ce0-5178-b1f4-11be1d7e786d', 'Ring 1', (timestamp '2023-05-27 11:31' at time zone 'America/Edmonton'), 8),
  ('063574a9-d011-579d-ba5c-dbcd2ad6abcb', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 3', 1, null, '86454338-fe8e-5a4f-86c1-cf82f139b926', 'b87776e1-f7ec-5a7f-92f0-9e425608809b', 'Ring 1', (timestamp '2023-05-27 11:41' at time zone 'America/Edmonton'), 8),
  ('bde6de2a-e819-51fc-a2f9-b17fa36b2d8b', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 4', 0, null, 'b87776e1-f7ec-5a7f-92f0-9e425608809b', '885629ca-1345-5d45-a4e4-b9ea975667f2', 'Ring 1', (timestamp '2023-05-27 11:51' at time zone 'America/Edmonton'), 8),
  ('b831ee9f-11b4-560a-905a-e05b5a76dbd3', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 4', 1, null, 'ef026627-9ce0-5178-b1f4-11be1d7e786d', 'fd22c6b9-5e1d-5a0a-bf96-53ba0e3e716a', 'Ring 1', (timestamp '2023-05-27 12:01' at time zone 'America/Edmonton'), 8),
  ('e65618a6-ccc3-5ae7-9364-386dc715c6b6', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 5', 0, null, '885629ca-1345-5d45-a4e4-b9ea975667f2', 'fd22c6b9-5e1d-5a0a-bf96-53ba0e3e716a', 'Ring 1', (timestamp '2023-05-27 12:11' at time zone 'America/Edmonton'), 8),
  ('4ff7a3ec-1759-5811-a515-b0d399bd421c', 'f091a4e0-c909-5941-b272-52d5db074198', 'round_robin', 'Round 5', 1, null, 'ef026627-9ce0-5178-b1f4-11be1d7e786d', '86454338-fe8e-5a4f-86c1-cf82f139b926', 'Ring 1', (timestamp '2023-05-27 12:21' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 2, 6, '{"kind":"duel","rounds":{"a":[1,1],"b":[1,5]},"totals":{"a":2,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '3241e7c3-52ae-5606-82a1-f78c321f8b43' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 8, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,4]},"totals":{"a":0,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'f115511d-6896-5336-ae1e-eac560b49781' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[1,1,2],"b":[1,1,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '08eec953-d2b7-5108-98bc-e1a89541590a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[1,3],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '0fdf20b0-2473-5624-aa1a-b41143519b6c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 11, '{"kind":"duel","rounds":{"a":[2,1],"b":[10,1]},"totals":{"a":3,"b":11}}'::jsonb, m.version) from public.matches m where m.id = 'cd23c237-95eb-5fc1-a3e5-94bfd3b897e0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[2,2]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '063574a9-d011-579d-ba5c-dbcd2ad6abcb' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[2,2],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'bde6de2a-e819-51fc-a2f9-b17fa36b2d8b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[4,1],"b":[1,2]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'b831ee9f-11b4-560a-905a-e05b5a76dbd3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 6, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,4]},"totals":{"a":1,"b":6}}'::jsonb, m.version) from public.matches m where m.id = 'e65618a6-ccc3-5ae7-9364-386dc715c6b6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 3, '{"kind":"duel","rounds":{"a":[3,0,4],"b":[2,1,0]},"totals":{"a":7,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '4ff7a3ec-1759-5811-a515-b0d399bd421c' and m.queue_state <> 'final';
select public.finish_competition('f091a4e0-c909-5941-b272-52d5db074198', 'tournament_structure') where exists (select 1 from public.competitions where id = 'f091a4e0-c909-5941-b272-52d5db074198' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '6c090d10-08ee-5a45-bd5f-8e381181ffc1', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '288cdb75-8886-5e19-9ad6-adb155eb6369', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'ad09ff4f-148c-598b-9320-5bccef57ec7d', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'f091a4e0-c909-5941-b272-52d5db074198', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = '74b587d8-93f2-5031-9885-a60b7a517664' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = '74b587d8-93f2-5031-9885-a60b7a517664' and m.queue_state = 'final';
update public.audit_log set at = (date '2023-05-28' + time '21:00') at time zone 'America/Edmonton' where event_id = '74b587d8-93f2-5031-9885-a60b7a517664';
commit;
