-- NACL-test fictional dataset: Saskatchewan Steel Cup-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('bad1abb6-3156-5153-92f0-f960e476c968', 'saskatchewan-steel-cup-test', 'Saskatchewan Steel Cup-test', 'First NACL-test event outside Alberta, hosted by Stormbreakers-test.', 'tournament', 'published', 'Prairie Hall-test', 'Saskatoon', 'SK', 'CA', 'America/Regina', 0, date '2023-08-12', date '2023-08-13', '9ca49345-6351-519e-b23c-de0edff69ee0', 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', 'bad1abb6-3156-5153-92f0-f960e476c968', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('bad1abb6-3156-5153-92f0-f960e476c968', '0538dd11-8537-5f9c-b2fe-918f45b21bc0');
select public.set_event_organization('bad1abb6-3156-5153-92f0-f960e476c968', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('4719ae14-8f8b-5043-aca6-5c71a34535c4', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Male 5v5', '5v5', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('ed6ed2b2-bcfc-58d1-8311-17a64660ad14', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Female 5v5', '5v5', 'women', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 20),
  ('446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Male Longsword', 'longsword', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 30),
  ('ddca1279-97f9-511b-8bbe-f3b35add5149', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Female Longsword', 'longsword', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 40),
  ('9b83335e-ca9c-55d3-a3dd-4370c2671529', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Male Sword & Shield', 'sword_shield', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 50),
  ('e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Female Sword & Shield', 'sword_shield', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 60),
  ('f82c80c8-acf9-5fba-9200-93cc63a7f583', 'bad1abb6-3156-5153-92f0-f960e476c968', 'Male Polearm', 'polearm', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 70)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('1edf0476-9c3d-521b-9837-7db82b2f03ef', '4719ae14-8f8b-5043-aca6-5c71a34535c4', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('eca4e802-2956-5c8e-bfee-fdea403c211c', '4719ae14-8f8b-5043-aca6-5c71a34535c4', 'e9de392a-a969-592b-809d-fe5732f32cd7', null, 'checked_in'),
  ('811c6494-68b3-5260-acde-2a65826a0a52', '4719ae14-8f8b-5043-aca6-5c71a34535c4', '52287cd0-9f3e-5911-9538-ce229cf0362b', null, 'checked_in'),
  ('6e438a26-d22b-570c-a348-c86749d2e106', 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14', '9e6caec8-33a2-5b5c-97e8-89f86facf0ea', null, 'checked_in'),
  ('f498e751-aea0-5309-a9be-09209c34e66e', 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14', '9ca49345-6351-519e-b23c-de0edff69ee0', null, 'checked_in'),
  ('b433b245-09d2-5ecf-929c-e6f1a02ee125', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, 'dc986b96-be3f-5c26-914b-c1162aa0eb4b', 'checked_in'),
  ('cd2a7cec-06af-546b-b05d-3f71596660d4', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, '88af5e4f-d812-5e43-837b-5eb6dbb92226', 'checked_in'),
  ('9bc5828b-bcc1-5db2-a25a-7a65861e151b', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, '49c189e3-a1f5-5342-b03f-965e69b3406c', 'checked_in'),
  ('7cec4988-4b96-5729-9d37-4866bd9fe1d6', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, '97d5d06f-fcbe-5363-875c-abb48e8c9cbc', 'checked_in'),
  ('bb674373-9332-5f22-b159-ec3fd00cc5e8', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, 'd3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd', 'checked_in'),
  ('984c3a83-509f-5208-a8af-821955b0a338', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, 'df7d277f-b7dc-5d74-85f9-0a5e44bffad5', 'checked_in'),
  ('1723e98b-9f32-5491-a6f9-52beb47b6912', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, 'aa6336d6-f73e-5fa9-987f-556bf20050d8', 'checked_in'),
  ('d9a9aeb2-0bca-55d2-8358-e017b05140df', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', null, 'dc6ad18c-6ea3-5243-b794-7098006f2790', 'checked_in'),
  ('04dec327-0b66-5cf1-9557-8b4e1250269d', 'ddca1279-97f9-511b-8bbe-f3b35add5149', null, 'ccd25c59-7eec-5757-bff1-3437c26baed8', 'checked_in'),
  ('3d89a52c-8e0e-57e6-9720-fd926eec0182', 'ddca1279-97f9-511b-8bbe-f3b35add5149', null, '9890f7c8-373a-5cf8-b06c-34ea20a58304', 'checked_in'),
  ('892fb4be-8ff6-5463-84c7-a9bef720db7c', 'ddca1279-97f9-511b-8bbe-f3b35add5149', null, '866f9797-f136-5e8e-9aad-a556a65b580a', 'checked_in'),
  ('800fb6e7-a26e-56c6-8306-b73693860039', 'ddca1279-97f9-511b-8bbe-f3b35add5149', null, '58d24f9c-3ad4-50dc-befa-24ef2c80e2b1', 'checked_in'),
  ('b941d039-aa95-5ffd-b718-dda70a46a1c8', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, '72ab5bcb-c669-59a6-9865-86a0a151bc59', 'checked_in'),
  ('164208a0-83a6-5d4b-a1d1-97d1fdeec5dd', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, 'ff6d3454-18ef-5175-9d2b-56f676185804', 'checked_in'),
  ('3daadc65-dc2d-52e5-a84e-12e71ffdb71f', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, '4a28fccb-ff24-506e-8459-b2a304fb4784', 'checked_in'),
  ('ad7b14b5-c9be-5c3d-b352-0c34ed065891', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, 'cb21b06a-886b-5e1a-9453-1c173a5168f9', 'checked_in'),
  ('c2d611f0-f0fc-5f0a-b286-c1628ec88839', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, '53ac4dfa-3d15-5881-8a92-361c7e59b120', 'checked_in'),
  ('b449875c-17c1-5e8d-8458-c73872a6e75e', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, '1434a046-cc53-5391-86f0-ecf252a00d87', 'checked_in'),
  ('3289eb69-bac3-51f0-b98e-91c8a51e9538', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, '1b7a98f8-321b-5f82-a59c-55c84cab431b', 'checked_in'),
  ('ada17c47-aad6-5ec1-9e25-a51d685c2fa7', '9b83335e-ca9c-55d3-a3dd-4370c2671529', null, '4c9434e0-b2f5-5d5c-9ed3-c342dcab2258', 'checked_in'),
  ('6ac50450-d4d6-5758-8c34-56332e1bf6f5', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, '14aed5cd-7ebd-5bd5-a88c-b122058d9b5b', 'checked_in'),
  ('1843099c-4850-53dc-b474-c70915de3974', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, 'f59071d8-f158-5947-ba7a-7ff8533d06e5', 'checked_in'),
  ('27fd882e-c8fb-5bea-b15b-09c255c9352e', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, '982d4f9a-fb1c-5e81-b7f7-62c231c79fb2', 'checked_in'),
  ('56e4d815-871c-5ea0-8d39-b3ec820a3394', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, '3ce36aa6-ecae-5293-bac9-da3cebdd791a', 'checked_in'),
  ('6f651ade-293f-567b-ad34-55901f62714c', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, 'a8964f93-eda0-51d9-a592-43792c58b827', 'checked_in'),
  ('92124ce8-1f05-54d3-9054-f10dce491f26', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, 'dd3afd51-2fca-58cd-8d14-006dec7363a4', 'checked_in'),
  ('445b4854-065f-557e-a4f3-272ba65d7b1c', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', null, 'ac409506-3655-5834-b81b-a48ced9c62b9', 'checked_in'),
  ('341292ce-05fd-5090-b057-f9aafbcfb30c', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, 'b9551194-d28a-50e3-9bfc-36c446fa8f54', 'checked_in'),
  ('63d02f2a-ceba-59bc-83ed-49b0f8f896aa', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, 'e0e182fe-bce4-5347-ac8c-ac85f8f10fd5', 'checked_in'),
  ('ca607282-87de-5bbb-90ab-7851dbfe6355', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, '151f1b02-af6f-5a34-b0cb-a056556d730a', 'checked_in'),
  ('ec9f007f-9f79-53b9-a48a-31e25d4821bc', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, '5385df95-b791-5de5-a10f-9db8491e2dbc', 'checked_in'),
  ('846a163c-4233-512d-98eb-5008c057c880', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, '0e28a5bf-3ca5-50ce-bf11-142105c58181', 'checked_in'),
  ('e7e93fa7-3ee2-5f61-bda7-8a2a1d44623b', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, 'c9450ef4-e03e-545e-9fdc-0bc7747e447f', 'checked_in'),
  ('f9c2fb30-b088-5495-9229-e4c0b62160ef', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, '7f46df0f-b1c8-527e-aff1-d8ababc108d8', 'checked_in'),
  ('745dfb46-6319-5929-837c-f98981633012', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, '334bbc46-99e7-573f-8be9-5c304f12e660', 'checked_in'),
  ('30db715f-76d5-5b48-8bbb-0d8ccd851a8a', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', null, '8c9cc09b-4d19-5a87-b875-398e5233cd86', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('1edf0476-9c3d-521b-9837-7db82b2f03ef', '[{"fighter_id":"b9551194-d28a-50e3-9bfc-36c446fa8f54","role":"fighter"},{"fighter_id":"49c189e3-a1f5-5342-b03f-965e69b3406c","role":"fighter"},{"fighter_id":"72ab5bcb-c669-59a6-9865-86a0a151bc59","role":"fighter"},{"fighter_id":"e0e182fe-bce4-5347-ac8c-ac85f8f10fd5","role":"fighter"},{"fighter_id":"ff6d3454-18ef-5175-9d2b-56f676185804","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = '4719ae14-8f8b-5043-aca6-5c71a34535c4' and status <> 'finished');
select public.set_entry_roster('eca4e802-2956-5c8e-bfee-fdea403c211c', '[{"fighter_id":"5385df95-b791-5de5-a10f-9db8491e2dbc","role":"fighter"},{"fighter_id":"151f1b02-af6f-5a34-b0cb-a056556d730a","role":"fighter"},{"fighter_id":"4a28fccb-ff24-506e-8459-b2a304fb4784","role":"fighter"},{"fighter_id":"aa6336d6-f73e-5fa9-987f-556bf20050d8","role":"fighter"},{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '4719ae14-8f8b-5043-aca6-5c71a34535c4' and status <> 'finished');
select public.set_entry_roster('811c6494-68b3-5260-acde-2a65826a0a52', '[{"fighter_id":"8bf5a2df-8b24-5bae-b6cf-03c0dad81870","role":"fighter"},{"fighter_id":"dc6ad18c-6ea3-5243-b794-7098006f2790","role":"fighter"},{"fighter_id":"1434a046-cc53-5391-86f0-ecf252a00d87","role":"fighter"},{"fighter_id":"53ac4dfa-3d15-5881-8a92-361c7e59b120","role":"mercenary"},{"fighter_id":"d3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '4719ae14-8f8b-5043-aca6-5c71a34535c4' and status <> 'finished');
select public.set_entry_roster('6e438a26-d22b-570c-a348-c86749d2e106', '[{"fighter_id":"ccd25c59-7eec-5757-bff1-3437c26baed8","role":"fighter"},{"fighter_id":"0e9e0d00-70a7-5985-ac4a-8b379a5521bf","role":"fighter"},{"fighter_id":"14aed5cd-7ebd-5bd5-a88c-b122058d9b5b","role":"fighter"},{"fighter_id":"831b7043-6c86-5de6-9865-fba0592e1309","role":"mercenary"},{"fighter_id":"9890f7c8-373a-5cf8-b06c-34ea20a58304","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14' and status <> 'finished');
select public.set_entry_roster('f498e751-aea0-5309-a9be-09209c34e66e', '[{"fighter_id":"3ce36aa6-ecae-5293-bac9-da3cebdd791a","role":"fighter"},{"fighter_id":"866f9797-f136-5e8e-9aad-a556a65b580a","role":"fighter"},{"fighter_id":"982d4f9a-fb1c-5e81-b7f7-62c231c79fb2","role":"fighter"},{"fighter_id":"58d24f9c-3ad4-50dc-befa-24ef2c80e2b1","role":"mercenary"},{"fighter_id":"dd3afd51-2fca-58cd-8d14-006dec7363a4","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14' and status <> 'finished');
-- Male 5v5: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('b9299ccc-cff9-5659-97f4-9b983882a900', '4719ae14-8f8b-5043-aca6-5c71a34535c4', 'round_robin', 'Round 1', 0, null, '811c6494-68b3-5260-acde-2a65826a0a52', '1edf0476-9c3d-521b-9837-7db82b2f03ef', 'Ring 1', (timestamp '2023-08-12 10:00' at time zone 'America/Regina'), 15),
  ('1984f247-b211-5ac2-a5a5-a2f8c82a2fbe', '4719ae14-8f8b-5043-aca6-5c71a34535c4', 'round_robin', 'Round 2', 0, null, '1edf0476-9c3d-521b-9837-7db82b2f03ef', 'eca4e802-2956-5c8e-bfee-fdea403c211c', 'Ring 1', (timestamp '2023-08-12 10:17' at time zone 'America/Regina'), 15),
  ('4b21776c-d828-5d9b-a4bc-4e63e9088a9c', '4719ae14-8f8b-5043-aca6-5c71a34535c4', 'round_robin', 'Round 3', 0, null, 'eca4e802-2956-5c8e-bfee-fdea403c211c', '811c6494-68b3-5260-acde-2a65826a0a52', 'Ring 1', (timestamp '2023-08-12 10:34' at time zone 'America/Regina'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'b9299ccc-cff9-5659-97f4-9b983882a900' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '1984f247-b211-5ac2-a5a5-a2f8c82a2fbe' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '4b21776c-d828-5d9b-a4bc-4e63e9088a9c' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '4719ae14-8f8b-5043-aca6-5c71a34535c4' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('4719ae14-8f8b-5043-aca6-5c71a34535c4') where tied group by part, rank loop perform public.record_tie_decision('4719ae14-8f8b-5043-aca6-5c71a34535c4', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('4719ae14-8f8b-5043-aca6-5c71a34535c4', 'tournament_structure') where exists (select 1 from public.competitions where id = '4719ae14-8f8b-5043-aca6-5c71a34535c4' and status <> 'finished');
-- Female 5v5: round_robin, 2 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('55bf2438-4669-52b0-b5b8-48cd00fce7c4', 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14', 'round_robin', 'Round 1', 0, null, '6e438a26-d22b-570c-a348-c86749d2e106', 'f498e751-aea0-5309-a9be-09209c34e66e', 'Ring 2', (timestamp '2023-08-12 10:00' at time zone 'America/Regina'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '55bf2438-4669-52b0-b5b8-48cd00fce7c4' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('ed6ed2b2-bcfc-58d1-8311-17a64660ad14') where tied group by part, rank loop perform public.record_tie_decision('ed6ed2b2-bcfc-58d1-8311-17a64660ad14', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('ed6ed2b2-bcfc-58d1-8311-17a64660ad14', 'tournament_structure') where exists (select 1 from public.competitions where id = 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14' and status <> 'finished');
-- Male Longsword: elimination, 8 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('43bb6a24-de4e-5bad-a4b7-c17fffc94dc7', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'elimination', 'Quarterfinal', 0, null, '9bc5828b-bcc1-5db2-a25a-7a65861e151b', '7cec4988-4b96-5729-9d37-4866bd9fe1d6', 'Ring 3', (timestamp '2023-08-12 10:00' at time zone 'America/Regina'), 8),
  ('8f8384f2-348f-5bb0-9643-88648448709f', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'elimination', 'Quarterfinal', 1, null, 'b433b245-09d2-5ecf-929c-e6f1a02ee125', '984c3a83-509f-5208-a8af-821955b0a338', 'Ring 3', (timestamp '2023-08-12 10:10' at time zone 'America/Regina'), 8),
  ('f83dfdda-97d7-53ff-993a-f30629474234', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'elimination', 'Quarterfinal', 2, null, 'cd2a7cec-06af-546b-b05d-3f71596660d4', 'bb674373-9332-5f22-b159-ec3fd00cc5e8', 'Ring 3', (timestamp '2023-08-12 10:20' at time zone 'America/Regina'), 8),
  ('18c2d0d5-3840-54e4-b4cf-e10409eb4914', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'elimination', 'Quarterfinal', 3, null, '1723e98b-9f32-5491-a6f9-52beb47b6912', 'd9a9aeb2-0bca-55d2-8358-e017b05140df', 'Ring 3', (timestamp '2023-08-12 10:30' at time zone 'America/Regina'), 8),
  ('8b532453-ad45-53fb-b49a-1bc473f18db4', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 3', (timestamp '2023-08-12 10:40' at time zone 'America/Regina'), 8),
  ('3b70433e-5819-533d-963a-cd90ac6e2a87', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 3', (timestamp '2023-08-12 10:50' at time zone 'America/Regina'), 8),
  ('98b2f5a1-f6dd-5d2a-b826-2b2c7d90c2ba', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2023-08-12 11:00' at time zone 'America/Regina'), 8),
  ('2398afe5-3fe9-552a-b3dd-b37b2bb16b7e', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2023-08-12 11:10' at time zone 'America/Regina'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('43bb6a24-de4e-5bad-a4b7-c17fffc94dc7'::uuid, '8b532453-ad45-53fb-b49a-1bc473f18db4'::uuid, 'a'),
  ('8f8384f2-348f-5bb0-9643-88648448709f'::uuid, '8b532453-ad45-53fb-b49a-1bc473f18db4'::uuid, 'b'),
  ('f83dfdda-97d7-53ff-993a-f30629474234'::uuid, '3b70433e-5819-533d-963a-cd90ac6e2a87'::uuid, 'a'),
  ('18c2d0d5-3840-54e4-b4cf-e10409eb4914'::uuid, '3b70433e-5819-533d-963a-cd90ac6e2a87'::uuid, 'b'),
  ('8b532453-ad45-53fb-b49a-1bc473f18db4'::uuid, '98b2f5a1-f6dd-5d2a-b826-2b2c7d90c2ba'::uuid, 'a'),
  ('3b70433e-5819-533d-963a-cd90ac6e2a87'::uuid, '98b2f5a1-f6dd-5d2a-b826-2b2c7d90c2ba'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 9, 2, '{"kind":"duel","rounds":{"a":[2,7],"b":[1,1]},"totals":{"a":9,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '43bb6a24-de4e-5bad-a4b7-c17fffc94dc7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[2,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '8f8384f2-348f-5bb0-9643-88648448709f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[1,1],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'f83dfdda-97d7-53ff-993a-f30629474234' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 7, '{"kind":"duel","rounds":{"a":[2,1,1,0],"b":[3,0,2,2]},"totals":{"a":4,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '18c2d0d5-3840-54e4-b4cf-e10409eb4914' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[3,2],"b":[1,2]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '8b532453-ad45-53fb-b49a-1bc473f18db4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 0, '{"kind":"duel","rounds":{"a":[2,3],"b":[0,0]},"totals":{"a":5,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '3b70433e-5819-533d-963a-cd90ac6e2a87' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,2]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '98b2f5a1-f6dd-5d2a-b826-2b2c7d90c2ba' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 7, '{"kind":"duel","rounds":{"a":[2,2,2,3],"b":[2,3,1,1]},"totals":{"a":9,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '2398afe5-3fe9-552a-b3dd-b37b2bb16b7e' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '446bdf38-e45c-5a0a-86ef-c6a147e23b16' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('446bdf38-e45c-5a0a-86ef-c6a147e23b16') where tied group by part, rank loop perform public.record_tie_decision('446bdf38-e45c-5a0a-86ef-c6a147e23b16', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'tournament_structure') where exists (select 1 from public.competitions where id = '446bdf38-e45c-5a0a-86ef-c6a147e23b16' and status <> 'finished');
-- Female Longsword: round_robin, 4 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('d53b860c-a398-5269-bd6f-db5c6a4d3c96', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'round_robin', 'Round 1', 0, null, '800fb6e7-a26e-56c6-8306-b73693860039', '3d89a52c-8e0e-57e6-9720-fd926eec0182', 'Ring 1', (timestamp '2023-08-12 10:51' at time zone 'America/Regina'), 8),
  ('ae6d8c53-524c-5fc2-8664-1760a1567e6e', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'round_robin', 'Round 1', 1, null, '892fb4be-8ff6-5463-84c7-a9bef720db7c', '04dec327-0b66-5cf1-9557-8b4e1250269d', 'Ring 1', (timestamp '2023-08-12 11:01' at time zone 'America/Regina'), 8),
  ('5ed3ae2f-ebf3-504a-b701-dfbc0ebc896b', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'round_robin', 'Round 2', 0, null, '04dec327-0b66-5cf1-9557-8b4e1250269d', '800fb6e7-a26e-56c6-8306-b73693860039', 'Ring 1', (timestamp '2023-08-12 11:11' at time zone 'America/Regina'), 8),
  ('4da1cc59-6410-56cb-b3c6-489942bb58ae', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'round_robin', 'Round 2', 1, null, '3d89a52c-8e0e-57e6-9720-fd926eec0182', '892fb4be-8ff6-5463-84c7-a9bef720db7c', 'Ring 1', (timestamp '2023-08-12 11:21' at time zone 'America/Regina'), 8),
  ('e515a847-7dee-5330-9075-7dbf19d96a52', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'round_robin', 'Round 3', 0, null, '800fb6e7-a26e-56c6-8306-b73693860039', '892fb4be-8ff6-5463-84c7-a9bef720db7c', 'Ring 1', (timestamp '2023-08-12 11:31' at time zone 'America/Regina'), 8),
  ('8f760656-2598-59aa-b536-e119e46087d4', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'round_robin', 'Round 3', 1, null, '04dec327-0b66-5cf1-9557-8b4e1250269d', '3d89a52c-8e0e-57e6-9720-fd926eec0182', 'Ring 1', (timestamp '2023-08-12 11:41' at time zone 'America/Regina'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 6, 2, '{"kind":"duel","rounds":{"a":[3,3],"b":[1,1]},"totals":{"a":6,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'd53b860c-a398-5269-bd6f-db5c6a4d3c96' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 7, '{"kind":"duel","rounds":{"a":[1,0,3],"b":[1,1,5]},"totals":{"a":4,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'ae6d8c53-524c-5fc2-8664-1760a1567e6e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 8, 5, '{"kind":"duel","rounds":{"a":[1,1,1,3,2],"b":[2,1,0,2,0]},"totals":{"a":8,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '5ed3ae2f-ebf3-504a-b701-dfbc0ebc896b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[1,1],"b":[3,2]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '4da1cc59-6410-56cb-b3c6-489942bb58ae' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 1, '{"kind":"duel","rounds":{"a":[4,2],"b":[1,0]},"totals":{"a":6,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'e515a847-7dee-5330-9075-7dbf19d96a52' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '8f760656-2598-59aa-b536-e119e46087d4' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'ddca1279-97f9-511b-8bbe-f3b35add5149' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('ddca1279-97f9-511b-8bbe-f3b35add5149') where tied group by part, rank loop perform public.record_tie_decision('ddca1279-97f9-511b-8bbe-f3b35add5149', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('ddca1279-97f9-511b-8bbe-f3b35add5149', 'tournament_structure') where exists (select 1 from public.competitions where id = 'ddca1279-97f9-511b-8bbe-f3b35add5149' and status <> 'finished');
-- Male Sword & Shield: elimination, 8 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('a1e87ead-134c-5be2-a93a-6c92d2f5eba1', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'elimination', 'Quarterfinal', 0, null, 'c2d611f0-f0fc-5f0a-b286-c1628ec88839', 'b941d039-aa95-5ffd-b718-dda70a46a1c8', 'Ring 2', (timestamp '2023-08-12 10:17' at time zone 'America/Regina'), 8),
  ('019312b7-ad56-52c3-ae37-26743021cdba', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'elimination', 'Quarterfinal', 1, null, 'b449875c-17c1-5e8d-8458-c73872a6e75e', '3daadc65-dc2d-52e5-a84e-12e71ffdb71f', 'Ring 2', (timestamp '2023-08-12 10:27' at time zone 'America/Regina'), 8),
  ('bbe90c46-9ff9-57d6-b072-fea0acf0dfb4', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'elimination', 'Quarterfinal', 2, null, '3289eb69-bac3-51f0-b98e-91c8a51e9538', 'ada17c47-aad6-5ec1-9e25-a51d685c2fa7', 'Ring 2', (timestamp '2023-08-12 10:37' at time zone 'America/Regina'), 8),
  ('fd4a0e8c-89b8-562f-961c-035ac249c887', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'elimination', 'Quarterfinal', 3, null, '164208a0-83a6-5d4b-a1d1-97d1fdeec5dd', 'ad7b14b5-c9be-5c3d-b352-0c34ed065891', 'Ring 2', (timestamp '2023-08-12 10:47' at time zone 'America/Regina'), 8),
  ('1eabbca9-98e1-52f0-bf07-c2ecfbb1faf4', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2023-08-12 10:57' at time zone 'America/Regina'), 8),
  ('b3771c38-0e55-5048-8e19-f4e9339497e2', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2023-08-12 11:07' at time zone 'America/Regina'), 8),
  ('77ae95f3-1c00-5493-8cb5-7d43d3961c43', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2023-08-12 11:17' at time zone 'America/Regina'), 8),
  ('be13cc9e-d046-5e32-a0db-86c09900f540', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2023-08-12 11:27' at time zone 'America/Regina'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('a1e87ead-134c-5be2-a93a-6c92d2f5eba1'::uuid, '1eabbca9-98e1-52f0-bf07-c2ecfbb1faf4'::uuid, 'a'),
  ('019312b7-ad56-52c3-ae37-26743021cdba'::uuid, '1eabbca9-98e1-52f0-bf07-c2ecfbb1faf4'::uuid, 'b'),
  ('bbe90c46-9ff9-57d6-b072-fea0acf0dfb4'::uuid, 'b3771c38-0e55-5048-8e19-f4e9339497e2'::uuid, 'a'),
  ('fd4a0e8c-89b8-562f-961c-035ac249c887'::uuid, 'b3771c38-0e55-5048-8e19-f4e9339497e2'::uuid, 'b'),
  ('1eabbca9-98e1-52f0-bf07-c2ecfbb1faf4'::uuid, '77ae95f3-1c00-5493-8cb5-7d43d3961c43'::uuid, 'a'),
  ('b3771c38-0e55-5048-8e19-f4e9339497e2'::uuid, '77ae95f3-1c00-5493-8cb5-7d43d3961c43'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 6, 2, '{"kind":"duel","rounds":{"a":[3,3],"b":[1,1]},"totals":{"a":6,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'a1e87ead-134c-5be2-a93a-6c92d2f5eba1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,3]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '019312b7-ad56-52c3-ae37-26743021cdba' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[1,4],"b":[2,1]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'bbe90c46-9ff9-57d6-b072-fea0acf0dfb4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 0, '{"kind":"duel","rounds":{"a":[2,2],"b":[0,0]},"totals":{"a":4,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'fd4a0e8c-89b8-562f-961c-035ac249c887' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[2,2],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '1eabbca9-98e1-52f0-bf07-c2ecfbb1faf4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[2,0],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'b3771c38-0e55-5048-8e19-f4e9339497e2' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 1, '{"kind":"duel","rounds":{"a":[3,4],"b":[0,1]},"totals":{"a":7,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '77ae95f3-1c00-5493-8cb5-7d43d3961c43' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,0]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'be13cc9e-d046-5e32-a0db-86c09900f540' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '9b83335e-ca9c-55d3-a3dd-4370c2671529' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('9b83335e-ca9c-55d3-a3dd-4370c2671529') where tied group by part, rank loop perform public.record_tie_decision('9b83335e-ca9c-55d3-a3dd-4370c2671529', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('9b83335e-ca9c-55d3-a3dd-4370c2671529', 'tournament_structure') where exists (select 1 from public.competitions where id = '9b83335e-ca9c-55d3-a3dd-4370c2671529' and status <> 'finished');
-- Female Sword & Shield: elimination, 7 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('db8b48ee-b3d2-5a9b-abeb-b105c060aa75', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'elimination', 'Quarterfinal', 1, null, '56e4d815-871c-5ea0-8d39-b3ec820a3394', '6ac50450-d4d6-5758-8c34-56332e1bf6f5', 'Ring 3', (timestamp '2023-08-12 11:20' at time zone 'America/Regina'), 8),
  ('fd779815-d058-535c-8924-fae72ac9126e', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'elimination', 'Quarterfinal', 2, null, '1843099c-4850-53dc-b474-c70915de3974', '6f651ade-293f-567b-ad34-55901f62714c', 'Ring 3', (timestamp '2023-08-12 11:30' at time zone 'America/Regina'), 8),
  ('ab7e0800-3271-511a-bd17-5a0ff8993e9c', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'elimination', 'Quarterfinal', 3, null, '445b4854-065f-557e-a4f3-272ba65d7b1c', '92124ce8-1f05-54d3-9054-f10dce491f26', 'Ring 3', (timestamp '2023-08-12 11:40' at time zone 'America/Regina'), 8),
  ('f32dfccf-ae98-5435-bcbd-fcdedbfab324', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'elimination', 'Semifinal', 0, null, '27fd882e-c8fb-5bea-b15b-09c255c9352e', null, 'Ring 3', (timestamp '2023-08-12 11:50' at time zone 'America/Regina'), 8),
  ('f726913f-01d9-57fd-813e-63d20c0613fd', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 3', (timestamp '2023-08-12 12:00' at time zone 'America/Regina'), 8),
  ('666ff455-700a-51d9-a5d1-bf3ae6e1a5ad', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2023-08-12 12:10' at time zone 'America/Regina'), 8),
  ('090ba08a-cbc5-50bd-b94a-fc6a8d09fc3b', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2023-08-12 12:20' at time zone 'America/Regina'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('db8b48ee-b3d2-5a9b-abeb-b105c060aa75'::uuid, 'f32dfccf-ae98-5435-bcbd-fcdedbfab324'::uuid, 'b'),
  ('fd779815-d058-535c-8924-fae72ac9126e'::uuid, 'f726913f-01d9-57fd-813e-63d20c0613fd'::uuid, 'a'),
  ('ab7e0800-3271-511a-bd17-5a0ff8993e9c'::uuid, 'f726913f-01d9-57fd-813e-63d20c0613fd'::uuid, 'b'),
  ('f32dfccf-ae98-5435-bcbd-fcdedbfab324'::uuid, '666ff455-700a-51d9-a5d1-bf3ae6e1a5ad'::uuid, 'a'),
  ('f726913f-01d9-57fd-813e-63d20c0613fd'::uuid, '666ff455-700a-51d9-a5d1-bf3ae6e1a5ad'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[3,1],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'db8b48ee-b3d2-5a9b-abeb-b105c060aa75' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,1]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'fd779815-d058-535c-8924-fae72ac9126e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[4,0]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ab7e0800-3271-511a-bd17-5a0ff8993e9c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 10, '{"kind":"duel","rounds":{"a":[1,1,0],"b":[2,1,7]},"totals":{"a":2,"b":10}}'::jsonb, m.version) from public.matches m where m.id = 'f32dfccf-ae98-5435-bcbd-fcdedbfab324' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[0,2],"b":[2,3]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'f726913f-01d9-57fd-813e-63d20c0613fd' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,2]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '666ff455-700a-51d9-a5d1-bf3ae6e1a5ad' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[0,0,1,1,0],"b":[1,0,1,1,2]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '090ba08a-cbc5-50bd-b94a-fc6a8d09fc3b' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('e859d681-3aaa-55c2-a3fe-c80ccc6f70e3') where tied group by part, rank loop perform public.record_tie_decision('e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'tournament_structure') where exists (select 1 from public.competitions where id = 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3' and status <> 'finished');
-- Male Polearm: elimination, 9 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('1ecdd96a-9703-5733-af15-da0d6fc139ab', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Round of 16', 1, null, 'f9c2fb30-b088-5495-9229-e4c0b62160ef', '745dfb46-6319-5929-837c-f98981633012', 'Ring 1', (timestamp '2023-08-12 11:51' at time zone 'America/Regina'), 8),
  ('f62ee383-bc86-5fa9-ae1e-f8fd6ed33d16', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Quarterfinal', 0, null, 'e7e93fa7-3ee2-5f61-bda7-8a2a1d44623b', null, 'Ring 1', (timestamp '2023-08-12 12:01' at time zone 'America/Regina'), 8),
  ('390dc77f-a313-5e95-a125-08d2dadd0d7b', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Quarterfinal', 1, null, '30db715f-76d5-5b48-8bbb-0d8ccd851a8a', '63d02f2a-ceba-59bc-83ed-49b0f8f896aa', 'Ring 1', (timestamp '2023-08-12 12:11' at time zone 'America/Regina'), 8),
  ('7fb0ca6a-9092-56ea-a478-5a497466aa00', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Quarterfinal', 2, null, '341292ce-05fd-5090-b057-f9aafbcfb30c', 'ec9f007f-9f79-53b9-a48a-31e25d4821bc', 'Ring 1', (timestamp '2023-08-12 12:21' at time zone 'America/Regina'), 8),
  ('3bdaf3c7-923a-5f08-b3c6-1728ed252704', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Quarterfinal', 3, null, 'ca607282-87de-5bbb-90ab-7851dbfe6355', '846a163c-4233-512d-98eb-5008c057c880', 'Ring 1', (timestamp '2023-08-12 12:31' at time zone 'America/Regina'), 8),
  ('f2246814-433c-5426-bd8a-c4c7bb185f57', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 1', (timestamp '2023-08-12 12:41' at time zone 'America/Regina'), 8),
  ('53d160b3-7af9-54ab-a399-6c87310bbfcf', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 1', (timestamp '2023-08-12 12:51' at time zone 'America/Regina'), 8),
  ('3a92dfd1-c86a-5e22-b7b4-950615a6f42e', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'final', 'Final', 0, null, null, null, 'Ring 1', (timestamp '2023-08-12 13:01' at time zone 'America/Regina'), 8),
  ('05c9dfe8-c839-5514-bbcf-be70685b405b', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'third_place', 'Third place', 0, null, null, null, 'Ring 1', (timestamp '2023-08-12 13:11' at time zone 'America/Regina'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('1ecdd96a-9703-5733-af15-da0d6fc139ab'::uuid, 'f62ee383-bc86-5fa9-ae1e-f8fd6ed33d16'::uuid, 'b'),
  ('f62ee383-bc86-5fa9-ae1e-f8fd6ed33d16'::uuid, 'f2246814-433c-5426-bd8a-c4c7bb185f57'::uuid, 'a'),
  ('390dc77f-a313-5e95-a125-08d2dadd0d7b'::uuid, 'f2246814-433c-5426-bd8a-c4c7bb185f57'::uuid, 'b'),
  ('7fb0ca6a-9092-56ea-a478-5a497466aa00'::uuid, '53d160b3-7af9-54ab-a399-6c87310bbfcf'::uuid, 'a'),
  ('3bdaf3c7-923a-5f08-b3c6-1728ed252704'::uuid, '53d160b3-7af9-54ab-a399-6c87310bbfcf'::uuid, 'b'),
  ('f2246814-433c-5426-bd8a-c4c7bb185f57'::uuid, '3a92dfd1-c86a-5e22-b7b4-950615a6f42e'::uuid, 'a'),
  ('53d160b3-7af9-54ab-a399-6c87310bbfcf'::uuid, '3a92dfd1-c86a-5e22-b7b4-950615a6f42e'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,2]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '1ecdd96a-9703-5733-af15-da0d6fc139ab' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[1,2],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'f62ee383-bc86-5fa9-ae1e-f8fd6ed33d16' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 0, '{"kind":"duel","rounds":{"a":[3,1],"b":[0,0]},"totals":{"a":4,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '390dc77f-a313-5e95-a125-08d2dadd0d7b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,1]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '7fb0ca6a-9092-56ea-a478-5a497466aa00' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '3bdaf3c7-923a-5f08-b3c6-1728ed252704' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[2,0,3],"b":[0,2,0]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'f2246814-433c-5426-bd8a-c4c7bb185f57' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 8, 10, '{"kind":"duel","rounds":{"a":[4,1,2,0,1,0],"b":[2,2,3,1,1,1]},"totals":{"a":8,"b":10}}'::jsonb, m.version) from public.matches m where m.id = '53d160b3-7af9-54ab-a399-6c87310bbfcf' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '3a92dfd1-c86a-5e22-b7b4-950615a6f42e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1],"b":[2,1]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '05c9dfe8-c839-5514-bbcf-be70685b405b' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'f82c80c8-acf9-5fba-9200-93cc63a7f583' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('f82c80c8-acf9-5fba-9200-93cc63a7f583') where tied group by part, rank loop perform public.record_tie_decision('f82c80c8-acf9-5fba-9200-93cc63a7f583', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('f82c80c8-acf9-5fba-9200-93cc63a7f583', 'tournament_structure') where exists (select 1 from public.competitions where id = 'f82c80c8-acf9-5fba-9200-93cc63a7f583' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '4719ae14-8f8b-5043-aca6-5c71a34535c4', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'ed6ed2b2-bcfc-58d1-8311-17a64660ad14', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '446bdf38-e45c-5a0a-86ef-c6a147e23b16', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'ddca1279-97f9-511b-8bbe-f3b35add5149', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '9b83335e-ca9c-55d3-a3dd-4370c2671529', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'e859d681-3aaa-55c2-a3fe-c80ccc6f70e3', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'f82c80c8-acf9-5fba-9200-93cc63a7f583', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = 'bad1abb6-3156-5153-92f0-f960e476c968' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = 'bad1abb6-3156-5153-92f0-f960e476c968' and m.queue_state = 'final';
update public.audit_log set at = (date '2023-08-13' + time '21:00') at time zone 'America/Regina' where event_id = 'bad1abb6-3156-5153-92f0-f960e476c968';
commit;
