-- NACL-test fictional dataset: Battle of the Badlands-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'battle-of-the-badlands-test', 'Battle of the Badlands-test', 'A small summer event in the Alberta badlands.', 'tournament', 'published', 'Badlands Rodeo Grounds-test', 'Drumheller', 'AB', 'CA', 'America/Edmonton', 0, date '2024-08-17', date '2024-08-18', null, 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'bb59ba34-678b-553a-bf7d-a34c419ec2b2');
select public.set_event_organization('4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('07936f08-06ae-5d28-a700-ccc50aadfe4e', '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'Male 5v5', '5v5', 'men', 'Source', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'Male Longsword', 'longsword', 'men', 'Source', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 20),
  ('5db0558c-a10f-556e-b6e6-0bf9f5885fc8', '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'Female Longsword', 'longsword', 'women', 'Source', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 30),
  ('65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e', 'Male Sword & Shield', 'sword_shield', 'men', 'Source', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 40)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('5777c23c-1e2a-5bdf-a3b6-3bc795a6df8a', '07936f08-06ae-5d28-a700-ccc50aadfe4e', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('5c9e24d5-143a-5656-8791-f873ee5414e5', '07936f08-06ae-5d28-a700-ccc50aadfe4e', '9e6caec8-33a2-5b5c-97e8-89f86facf0ea', null, 'checked_in'),
  ('f4e5272a-7d08-5041-9b3c-c88605418437', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, '88af5e4f-d812-5e43-837b-5eb6dbb92226', 'checked_in'),
  ('e795ef4e-7f7b-5ef7-9f62-b743ea1f17f4', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, '49c189e3-a1f5-5342-b03f-965e69b3406c', 'checked_in'),
  ('3860e663-a75e-56bd-b633-94605b9ed218', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, 'd3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd', 'checked_in'),
  ('7ff33054-cbb1-5921-b893-e47ad5170d07', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, 'df7d277f-b7dc-5d74-85f9-0a5e44bffad5', 'checked_in'),
  ('d24e9bd5-1463-5cfb-a12a-a9f3d153537b', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, 'd2ea0e0b-da23-5e24-802d-85145d3f616f', 'checked_in'),
  ('53236b07-4f5c-526d-9fc8-054ccff76957', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, 'f8297a85-7282-5c93-a25a-7ebfd34d0160', 'checked_in'),
  ('aa32139f-337a-55f3-872a-02716e4f589b', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, '9d6c5769-9a00-5895-a943-8dd9f804984d', 'checked_in'),
  ('fee149ba-eee5-5c1a-b909-157fc51d90e2', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', null, '31375f7d-13ba-5a5f-95ec-75173fd0c9a1', 'checked_in'),
  ('8d76b9b6-b0d1-55e0-88cb-b6aca62a0267', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, 'f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61', 'checked_in'),
  ('c0430143-ce53-5d52-bc16-27447ef94ccd', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, '7b2a7b7d-ddd2-595d-9269-7efa0dbacd1a', 'checked_in'),
  ('01124d87-e77c-5a42-b602-6469c381e94a', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, 'ccd25c59-7eec-5757-bff1-3437c26baed8', 'checked_in'),
  ('bf5c2e49-6bf9-513c-bc0e-a24213d736f7', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, 'a84d9159-737e-54fd-ad21-cbbe6152d754', 'checked_in'),
  ('664e98cd-fb6e-5644-bb91-3021f150ccc8', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, '104dfdb9-1ffa-54a2-8eb7-59e80cd8dad9', 'checked_in'),
  ('908e4eb7-9c12-54f3-a096-6bd500cce3cd', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, '866f9797-f136-5e8e-9aad-a556a65b580a', 'checked_in'),
  ('0cd0c6f3-8c3a-5bda-8f70-f040c943fdb4', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', null, '4cb4a51f-1606-5b8d-bf8b-4d859aef037c', 'checked_in'),
  ('15aff335-f4e8-5182-94b3-887bd270e2ef', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', null, '72ab5bcb-c669-59a6-9865-86a0a151bc59', 'checked_in'),
  ('8cb065bf-7e02-5618-97e2-de9e59ae4a47', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', null, 'a6d7fbe4-0392-5679-9e83-3a4693aa452d', 'checked_in'),
  ('afad119d-a665-5601-b8f5-4401f746c49b', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', null, '200ae42d-0337-5186-ab5e-51d6f011162f', 'checked_in'),
  ('bfbdcfc8-692b-5dbe-904e-44e0fc61c02c', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', null, 'b41fb9fe-c8ec-5405-a0f4-394ee6095b2e', 'checked_in'),
  ('1ca109a1-51d0-50fe-87fc-721f5921d392', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', null, '1a9c131f-3e6b-5182-868c-ad907a16b5b1', 'checked_in'),
  ('d014ebc8-f5ca-54e0-bfe2-594842fdce91', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', null, 'f5cc5373-d952-5604-adde-f304f3f6c86e', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('5777c23c-1e2a-5bdf-a3b6-3bc795a6df8a', '[{"fighter_id":"e0e182fe-bce4-5347-ac8c-ac85f8f10fd5","role":"fighter"},{"fighter_id":"49c189e3-a1f5-5342-b03f-965e69b3406c","role":"fighter"},{"fighter_id":"72ab5bcb-c669-59a6-9865-86a0a151bc59","role":"fighter"},{"fighter_id":"1a9c131f-3e6b-5182-868c-ad907a16b5b1","role":"mercenary"},{"fighter_id":"b41fb9fe-c8ec-5405-a0f4-394ee6095b2e","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '07936f08-06ae-5d28-a700-ccc50aadfe4e' and status <> 'finished');
select public.set_entry_roster('5c9e24d5-143a-5656-8791-f873ee5414e5', '[{"fighter_id":"8120e2f4-1510-5cfd-a077-7320c47a52a9","role":"fighter"},{"fighter_id":"a495403d-712c-5520-b2a2-f8c766eaaa6b","role":"fighter"},{"fighter_id":"d3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd","role":"fighter"},{"fighter_id":"a6d7fbe4-0392-5679-9e83-3a4693aa452d","role":"fighter"},{"fighter_id":"5385df95-b791-5de5-a10f-9db8491e2dbc","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '07936f08-06ae-5d28-a700-ccc50aadfe4e' and status <> 'finished');
-- Male 5v5: round_robin, 2 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('1fc79f5c-83cd-5f53-9fda-5aebd51e676f', '07936f08-06ae-5d28-a700-ccc50aadfe4e', 'round_robin', 'Round 1', 0, null, '5c9e24d5-143a-5656-8791-f873ee5414e5', '5777c23c-1e2a-5bdf-a3b6-3bc795a6df8a', 'Ring 1', (timestamp '2024-08-17 10:00' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '1fc79f5c-83cd-5f53-9fda-5aebd51e676f' and m.queue_state <> 'final';
select public.finish_competition('07936f08-06ae-5d28-a700-ccc50aadfe4e', 'tournament_structure') where exists (select 1 from public.competitions where id = '07936f08-06ae-5d28-a700-ccc50aadfe4e' and status <> 'finished');
-- Male Longsword: elimination, 8 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('18d01acd-e128-5890-b313-76987133f846', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'elimination', 'Quarterfinal', 0, null, 'fee149ba-eee5-5c1a-b909-157fc51d90e2', 'e795ef4e-7f7b-5ef7-9f62-b743ea1f17f4', 'Ring 2', (timestamp '2024-08-17 10:00' at time zone 'America/Edmonton'), 8),
  ('9e78f225-5aec-5a9f-a5fe-998765228624', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'elimination', 'Quarterfinal', 1, null, '3860e663-a75e-56bd-b633-94605b9ed218', 'f4e5272a-7d08-5041-9b3c-c88605418437', 'Ring 2', (timestamp '2024-08-17 10:10' at time zone 'America/Edmonton'), 8),
  ('38e52540-b6e1-5ae7-a5ea-e55752fd7994', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'elimination', 'Quarterfinal', 2, null, '7ff33054-cbb1-5921-b893-e47ad5170d07', 'aa32139f-337a-55f3-872a-02716e4f589b', 'Ring 2', (timestamp '2024-08-17 10:20' at time zone 'America/Edmonton'), 8),
  ('8ce321e8-d33c-5e47-82ce-46f042fb94e6', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'elimination', 'Quarterfinal', 3, null, 'd24e9bd5-1463-5cfb-a12a-a9f3d153537b', '53236b07-4f5c-526d-9fc8-054ccff76957', 'Ring 2', (timestamp '2024-08-17 10:30' at time zone 'America/Edmonton'), 8),
  ('2a18cc12-e874-5bb5-b0b7-dc7b4cd4607b', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2024-08-17 10:40' at time zone 'America/Edmonton'), 8),
  ('5537e956-339b-5dde-8561-4ad02239c2e0', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2024-08-17 10:50' at time zone 'America/Edmonton'), 8),
  ('3924b02e-7d68-5c37-9f0d-da72ad70d8cc', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2024-08-17 11:00' at time zone 'America/Edmonton'), 8),
  ('d58be663-08e6-5831-9107-78f84938c1d4', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2024-08-17 11:10' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('18d01acd-e128-5890-b313-76987133f846'::uuid, '2a18cc12-e874-5bb5-b0b7-dc7b4cd4607b'::uuid, 'a'),
  ('9e78f225-5aec-5a9f-a5fe-998765228624'::uuid, '2a18cc12-e874-5bb5-b0b7-dc7b4cd4607b'::uuid, 'b'),
  ('38e52540-b6e1-5ae7-a5ea-e55752fd7994'::uuid, '5537e956-339b-5dde-8561-4ad02239c2e0'::uuid, 'a'),
  ('8ce321e8-d33c-5e47-82ce-46f042fb94e6'::uuid, '5537e956-339b-5dde-8561-4ad02239c2e0'::uuid, 'b'),
  ('2a18cc12-e874-5bb5-b0b7-dc7b4cd4607b'::uuid, '3924b02e-7d68-5c37-9f0d-da72ad70d8cc'::uuid, 'a'),
  ('5537e956-339b-5dde-8561-4ad02239c2e0'::uuid, '3924b02e-7d68-5c37-9f0d-da72ad70d8cc'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,1]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '18d01acd-e128-5890-b313-76987133f846' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 10, 8, '{"kind":"duel","rounds":{"a":[1,2,2,0,2,3],"b":[3,1,2,0,1,1]},"totals":{"a":10,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '9e78f225-5aec-5a9f-a5fe-998765228624' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[1,3],"b":[1,0]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '38e52540-b6e1-5ae7-a5ea-e55752fd7994' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 0, '{"kind":"duel","rounds":{"a":[4,2],"b":[0,0]},"totals":{"a":6,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '8ce321e8-d33c-5e47-82ce-46f042fb94e6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 0, '{"kind":"duel","rounds":{"a":[4,2],"b":[0,0]},"totals":{"a":6,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '2a18cc12-e874-5bb5-b0b7-dc7b4cd4607b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 1, '{"kind":"duel","rounds":{"a":[4,3],"b":[1,0]},"totals":{"a":7,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '5537e956-339b-5dde-8561-4ad02239c2e0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[2,0,3],"b":[1,0,1]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '3924b02e-7d68-5c37-9f0d-da72ad70d8cc' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,4]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'd58be663-08e6-5831-9107-78f84938c1d4' and m.queue_state <> 'final';
select public.finish_competition('fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'tournament_structure') where exists (select 1 from public.competitions where id = 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c' and status <> 'finished');
-- Female Longsword: elimination, 7 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('4be0528f-ddcc-50fd-9f1e-68a3884d3fa0', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'elimination', 'Quarterfinal', 1, null, 'c0430143-ce53-5d52-bc16-27447ef94ccd', '664e98cd-fb6e-5644-bb91-3021f150ccc8', 'Ring 3', (timestamp '2024-08-17 10:00' at time zone 'America/Edmonton'), 8),
  ('b382a1c3-c939-5d0d-b523-4ee077957c59', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'elimination', 'Quarterfinal', 2, null, '908e4eb7-9c12-54f3-a096-6bd500cce3cd', '01124d87-e77c-5a42-b602-6469c381e94a', 'Ring 3', (timestamp '2024-08-17 10:10' at time zone 'America/Edmonton'), 8),
  ('3f513300-0cae-5974-b630-bc0f6c27dfec', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'elimination', 'Quarterfinal', 3, null, '0cd0c6f3-8c3a-5bda-8f70-f040c943fdb4', 'bf5c2e49-6bf9-513c-bc0e-a24213d736f7', 'Ring 3', (timestamp '2024-08-17 10:20' at time zone 'America/Edmonton'), 8),
  ('d2e9ede6-5d8a-5c62-9020-ac897731649d', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'elimination', 'Semifinal', 0, null, '8d76b9b6-b0d1-55e0-88cb-b6aca62a0267', null, 'Ring 3', (timestamp '2024-08-17 10:30' at time zone 'America/Edmonton'), 8),
  ('78095925-fb5a-5445-92b6-a56dbb90d703', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 3', (timestamp '2024-08-17 10:40' at time zone 'America/Edmonton'), 8),
  ('b086c8bb-2936-54c4-9151-b26aa0c52ea8', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2024-08-17 10:50' at time zone 'America/Edmonton'), 8),
  ('871003dd-d2a8-5da6-8525-22d301652432', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2024-08-17 11:00' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('4be0528f-ddcc-50fd-9f1e-68a3884d3fa0'::uuid, 'd2e9ede6-5d8a-5c62-9020-ac897731649d'::uuid, 'b'),
  ('b382a1c3-c939-5d0d-b523-4ee077957c59'::uuid, '78095925-fb5a-5445-92b6-a56dbb90d703'::uuid, 'a'),
  ('3f513300-0cae-5974-b630-bc0f6c27dfec'::uuid, '78095925-fb5a-5445-92b6-a56dbb90d703'::uuid, 'b'),
  ('d2e9ede6-5d8a-5c62-9020-ac897731649d'::uuid, 'b086c8bb-2936-54c4-9151-b26aa0c52ea8'::uuid, 'a'),
  ('78095925-fb5a-5445-92b6-a56dbb90d703'::uuid, 'b086c8bb-2936-54c4-9151-b26aa0c52ea8'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,2]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '4be0528f-ddcc-50fd-9f1e-68a3884d3fa0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[0,0,0,1,3,1,0],"b":[0,1,0,0,2,2,2]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'b382a1c3-c939-5d0d-b523-4ee077957c59' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 8, '{"kind":"duel","rounds":{"a":[1,4],"b":[4,4]},"totals":{"a":5,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '3f513300-0cae-5974-b630-bc0f6c27dfec' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[0,2]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'd2e9ede6-5d8a-5c62-9020-ac897731649d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 5, '{"kind":"duel","rounds":{"a":[0,2,0,1,1,5],"b":[0,1,1,1,2,0]},"totals":{"a":9,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '78095925-fb5a-5445-92b6-a56dbb90d703' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'b086c8bb-2936-54c4-9151-b26aa0c52ea8' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 3, '{"kind":"duel","rounds":{"a":[1,2,3],"b":[0,2,1]},"totals":{"a":6,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '871003dd-d2a8-5da6-8525-22d301652432' and m.queue_state <> 'final';
select public.finish_competition('5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'tournament_structure') where exists (select 1 from public.competitions where id = '5db0558c-a10f-556e-b6e6-0bf9f5885fc8' and status <> 'finished');
-- Male Sword & Shield: round_robin, 6 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('67aee0f4-8be9-5f1b-aec9-dc55d291d381', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 1', 0, null, 'afad119d-a665-5601-b8f5-4401f746c49b', '1ca109a1-51d0-50fe-87fc-721f5921d392', 'Ring 1', (timestamp '2024-08-17 10:17' at time zone 'America/Edmonton'), 8),
  ('cf797fe3-9dbd-5e56-98e3-75e8f02545e2', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 1', 1, null, 'd014ebc8-f5ca-54e0-bfe2-594842fdce91', 'bfbdcfc8-692b-5dbe-904e-44e0fc61c02c', 'Ring 1', (timestamp '2024-08-17 10:27' at time zone 'America/Edmonton'), 8),
  ('c15f9f3e-4cfd-53cc-b888-fd1648c22d34', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 1', 2, null, '8cb065bf-7e02-5618-97e2-de9e59ae4a47', '15aff335-f4e8-5182-94b3-887bd270e2ef', 'Ring 1', (timestamp '2024-08-17 10:37' at time zone 'America/Edmonton'), 8),
  ('30da0889-cb04-573a-a6c9-5c8f7e7f0604', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 2', 0, null, 'bfbdcfc8-692b-5dbe-904e-44e0fc61c02c', 'afad119d-a665-5601-b8f5-4401f746c49b', 'Ring 1', (timestamp '2024-08-17 10:47' at time zone 'America/Edmonton'), 8),
  ('467e103b-cede-50a9-aa7d-953ef92c6132', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 2', 1, null, '1ca109a1-51d0-50fe-87fc-721f5921d392', '15aff335-f4e8-5182-94b3-887bd270e2ef', 'Ring 1', (timestamp '2024-08-17 10:57' at time zone 'America/Edmonton'), 8),
  ('228bf090-aa68-5439-aa65-e8c007af4499', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 2', 2, null, 'd014ebc8-f5ca-54e0-bfe2-594842fdce91', '8cb065bf-7e02-5618-97e2-de9e59ae4a47', 'Ring 1', (timestamp '2024-08-17 11:07' at time zone 'America/Edmonton'), 8),
  ('39dec5f2-c79d-587c-8990-94b690a8a608', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 3', 0, null, 'afad119d-a665-5601-b8f5-4401f746c49b', '15aff335-f4e8-5182-94b3-887bd270e2ef', 'Ring 1', (timestamp '2024-08-17 11:17' at time zone 'America/Edmonton'), 8),
  ('4e1510ab-3ff6-56a2-86a6-7d742507474c', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 3', 1, null, 'bfbdcfc8-692b-5dbe-904e-44e0fc61c02c', '8cb065bf-7e02-5618-97e2-de9e59ae4a47', 'Ring 1', (timestamp '2024-08-17 11:27' at time zone 'America/Edmonton'), 8),
  ('4e13919b-9b95-518f-8f81-f32fdd058ed6', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 3', 2, null, '1ca109a1-51d0-50fe-87fc-721f5921d392', 'd014ebc8-f5ca-54e0-bfe2-594842fdce91', 'Ring 1', (timestamp '2024-08-17 11:37' at time zone 'America/Edmonton'), 8),
  ('57398867-a665-5d8f-8ca7-34bd518c0295', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 4', 0, null, '8cb065bf-7e02-5618-97e2-de9e59ae4a47', 'afad119d-a665-5601-b8f5-4401f746c49b', 'Ring 1', (timestamp '2024-08-17 11:47' at time zone 'America/Edmonton'), 8),
  ('7c0e8cb6-f514-55a7-b850-07d08640f311', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 4', 1, null, '15aff335-f4e8-5182-94b3-887bd270e2ef', 'd014ebc8-f5ca-54e0-bfe2-594842fdce91', 'Ring 1', (timestamp '2024-08-17 11:57' at time zone 'America/Edmonton'), 8),
  ('5e16b596-6f11-5179-aed5-4139abed3746', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 4', 2, null, 'bfbdcfc8-692b-5dbe-904e-44e0fc61c02c', '1ca109a1-51d0-50fe-87fc-721f5921d392', 'Ring 1', (timestamp '2024-08-17 12:07' at time zone 'America/Edmonton'), 8),
  ('f3056c4c-327f-55cf-ae3d-fdbb81a08b28', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 5', 0, null, 'afad119d-a665-5601-b8f5-4401f746c49b', 'd014ebc8-f5ca-54e0-bfe2-594842fdce91', 'Ring 1', (timestamp '2024-08-17 12:17' at time zone 'America/Edmonton'), 8),
  ('96e17621-37a8-53e9-b4de-2052f2a66f6a', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 5', 1, null, '8cb065bf-7e02-5618-97e2-de9e59ae4a47', '1ca109a1-51d0-50fe-87fc-721f5921d392', 'Ring 1', (timestamp '2024-08-17 12:27' at time zone 'America/Edmonton'), 8),
  ('b97086a0-23f4-5e79-af15-fc3f31403627', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'round_robin', 'Round 5', 2, null, '15aff335-f4e8-5182-94b3-887bd270e2ef', 'bfbdcfc8-692b-5dbe-904e-44e0fc61c02c', 'Ring 1', (timestamp '2024-08-17 12:37' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[2,0],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '67aee0f4-8be9-5f1b-aec9-dc55d291d381' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[0,3]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'cf797fe3-9dbd-5e56-98e3-75e8f02545e2' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 8, '{"kind":"duel","rounds":{"a":[2,0],"b":[3,5]},"totals":{"a":2,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'c15f9f3e-4cfd-53cc-b888-fd1648c22d34' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[0,3],"b":[1,0]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '30da0889-cb04-573a-a6c9-5c8f7e7f0604' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,1]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '467e103b-cede-50a9-aa7d-953ef92c6132' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[0,2,1,0,0,1,1],"b":[1,1,0,1,1,1,2]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '228bf090-aa68-5439-aa65-e8c007af4499' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[1,1],"b":[3,1]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '39dec5f2-c79d-587c-8990-94b690a8a608' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[0,1,0,2,1],"b":[1,0,1,0,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '4e1510ab-3ff6-56a2-86a6-7d742507474c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[3,2]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '4e13919b-9b95-518f-8f81-f32fdd058ed6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[2,3],"b":[1,1]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '57398867-a665-5d8f-8ca7-34bd518c0295' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 2, '{"kind":"duel","rounds":{"a":[3,3],"b":[1,1]},"totals":{"a":6,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '7c0e8cb6-f514-55a7-b850-07d08640f311' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[1,2],"b":[1,0]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '5e16b596-6f11-5179-aed5-4139abed3746' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[0,2,1,0],"b":[0,1,2,2]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'f3056c4c-327f-55cf-ae3d-fdbb81a08b28' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 8, 2, '{"kind":"duel","rounds":{"a":[5,3],"b":[0,2]},"totals":{"a":8,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '96e17621-37a8-53e9-b4de-2052f2a66f6a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,0]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'b97086a0-23f4-5e79-af15-fc3f31403627' and m.queue_state <> 'final';
select public.finish_competition('65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'tournament_structure') where exists (select 1 from public.competitions where id = '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '07936f08-06ae-5d28-a700-ccc50aadfe4e', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'fe4c8534-ab2d-58b6-82d3-5e108ed0e98c', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '5db0558c-a10f-556e-b6e6-0bf9f5885fc8', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '65f8d3f0-6ed6-5d1e-b8da-7abdf7a2fd61', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e' and m.queue_state = 'final';
update public.audit_log set at = (date '2024-08-18' + time '21:00') at time zone 'America/Edmonton' where event_id = '4e7c23b4-432c-5a3e-9859-1799ffa0bf1e';
commit;
