-- NACL-test fictional dataset: Blackfalds Battle Bash-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('ce770d56-ddcb-5993-ae8e-67652373ff34', 'blackfalds-battle-bash-test', 'Blackfalds Battle Bash-test', 'A late-season bash in central Alberta.', 'tournament', 'published', 'Blackfalds Multiplex-test', 'Blackfalds', 'AB', 'CA', 'America/Edmonton', 0, date '2024-11-09', date '2024-11-10', '4842a217-7f85-509f-aa7e-cefa2bffbfab', 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', 'ce770d56-ddcb-5993-ae8e-67652373ff34', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('ce770d56-ddcb-5993-ae8e-67652373ff34', 'bb59ba34-678b-553a-bf7d-a34c419ec2b2');
select public.set_event_organization('ce770d56-ddcb-5993-ae8e-67652373ff34', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('0020f56d-908d-5942-b2d9-e08961adb754', 'ce770d56-ddcb-5993-ae8e-67652373ff34', 'Male 3v3', '3v3', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('9cbce0bb-d25e-5ed9-b468-efe31c720def', 'ce770d56-ddcb-5993-ae8e-67652373ff34', 'Male Longsword', 'longsword', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 20),
  ('3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'ce770d56-ddcb-5993-ae8e-67652373ff34', 'Female Sword & Shield', 'sword_shield', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'pools_elimination', 'running', null, 30),
  ('d23b1270-5964-5596-a90a-177eec066cec', 'ce770d56-ddcb-5993-ae8e-67652373ff34', 'Male Polearm', 'polearm', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 40)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('3f03d1d2-6bf6-58de-8926-ebb96046c4f7', '0020f56d-908d-5942-b2d9-e08961adb754', '4842a217-7f85-509f-aa7e-cefa2bffbfab', null, 'checked_in'),
  ('ef55959b-da00-550d-ab1c-33cb3431fbcf', '0020f56d-908d-5942-b2d9-e08961adb754', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('aa067d82-9d8e-50e5-b573-8813d8a0ec87', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, 'dc986b96-be3f-5c26-914b-c1162aa0eb4b', 'checked_in'),
  ('ab326369-bf05-509d-a2bb-9022c6d4c4d5', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, '7ba3fceb-e85e-5ed0-84a0-76915d6c6f83', 'checked_in'),
  ('a9cf8cae-de88-504a-99f4-e62455fa3de8', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, '88af5e4f-d812-5e43-837b-5eb6dbb92226', 'checked_in'),
  ('7ca79d92-31e0-568b-8300-a2a556b1a8ce', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, 'd3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd', 'checked_in'),
  ('3bae1753-a159-5326-86d6-f25584d73748', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, 'e3b4a9f7-0116-5514-b4ba-e76cfc0ee774', 'checked_in'),
  ('95203029-b2b2-5ff0-8dc7-83b084b01a16', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, '88d259b3-3d84-5796-bdcb-c2fdfd8b09ed', 'checked_in'),
  ('48a0cc57-3c1f-51d7-b26f-42fe160d7352', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, 'c2114868-da44-5a82-a1d3-f91f5326285f', 'checked_in'),
  ('180d3656-acad-531c-95cd-df0afdb5fd96', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, '3675139b-aab7-5d9b-b009-cb9386485d08', 'checked_in'),
  ('8da658db-985c-5572-b5c6-5445a3d991cb', '9cbce0bb-d25e-5ed9-b468-efe31c720def', null, 'f8297a85-7282-5c93-a25a-7ebfd34d0160', 'checked_in'),
  ('5771093c-e124-52d6-8616-ed1bd4ccabd9', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '7b4eb64c-041e-55c7-ade2-755393281205', 'checked_in'),
  ('35e8a1b2-dd29-5b8d-a522-2dff75edd19b', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, 'faaae965-8f7f-5c9d-8300-0d6cf7cf6b75', 'checked_in'),
  ('e11cde15-15ba-590c-bd72-167f1e5e1bd4', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '285f8b35-de1b-5ade-82c6-4fe0a0a132d9', 'checked_in'),
  ('542cfedb-b48e-52b7-9d2d-2ead098f8ae0', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '8a0b0f89-6e54-548f-938c-84238b1e23e1', 'checked_in'),
  ('238a3305-3b14-5c4e-a42d-39d0cff632d3', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '14aed5cd-7ebd-5bd5-a88c-b122058d9b5b', 'checked_in'),
  ('84253b86-abbd-5956-b06e-61f5e591084c', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '48e29b2c-61a9-5986-88bf-44714334aa9d', 'checked_in'),
  ('3981405f-cded-5544-829d-65101db3f3b8', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '44de541c-49d9-5576-bad7-2bcd7f194801', 'checked_in'),
  ('c2a88160-f7cd-5228-8b85-b6f181ff661a', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, 'f59071d8-f158-5947-ba7a-7ff8533d06e5', 'checked_in'),
  ('0f8ac5dd-671f-5d1b-804c-b62622c9bc5b', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, 'f7373850-cf16-5419-8c34-acfe15164af2', 'checked_in'),
  ('668064e0-bbd7-5be0-98d6-fde707b78cdd', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', null, '5777bdcc-18bc-518f-a88f-103441365171', 'checked_in'),
  ('32eebfd5-8d70-5baa-9f1f-42747d3b17ec', 'd23b1270-5964-5596-a90a-177eec066cec', null, 'bd195699-a4ba-5049-babf-d01f743911b5', 'checked_in'),
  ('655d162a-054d-5a6d-ab21-95b0f909b6ba', 'd23b1270-5964-5596-a90a-177eec066cec', null, '0e28a5bf-3ca5-50ce-bf11-142105c58181', 'checked_in'),
  ('7516f8f1-cc51-53dc-800f-4359f8301ccd', 'd23b1270-5964-5596-a90a-177eec066cec', null, '4feb7fd3-dd4d-532d-a360-5869eb50cc97', 'checked_in'),
  ('caedb686-70dc-544c-ad17-1466524b4212', 'd23b1270-5964-5596-a90a-177eec066cec', null, '1fcb6cfe-8069-5c6d-96dd-56ea1b461f7b', 'checked_in'),
  ('e46421bd-2a44-5a45-92d3-097a6c1fe26b', 'd23b1270-5964-5596-a90a-177eec066cec', null, 'c9450ef4-e03e-545e-9fdc-0bc7747e447f', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('3f03d1d2-6bf6-58de-8926-ebb96046c4f7', '[{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"fighter"},{"fighter_id":"b4b23592-ecfd-5625-92ec-4224c70404c2","role":"fighter"},{"fighter_id":"88af5e4f-d812-5e43-837b-5eb6dbb92226","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = '0020f56d-908d-5942-b2d9-e08961adb754' and status <> 'finished');
select public.set_entry_roster('ef55959b-da00-550d-ab1c-33cb3431fbcf', '[{"fighter_id":"0e28a5bf-3ca5-50ce-bf11-142105c58181","role":"fighter"},{"fighter_id":"88d259b3-3d84-5796-bdcb-c2fdfd8b09ed","role":"fighter"},{"fighter_id":"c2114868-da44-5a82-a1d3-f91f5326285f","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = '0020f56d-908d-5942-b2d9-e08961adb754' and status <> 'finished');
-- Male 3v3: round_robin, 2 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('62e5039d-882f-50ed-893a-881bb16f53ff', '0020f56d-908d-5942-b2d9-e08961adb754', 'round_robin', 'Round 1', 0, null, 'ef55959b-da00-550d-ab1c-33cb3431fbcf', '3f03d1d2-6bf6-58de-8926-ebb96046c4f7', 'Ring 1', (timestamp '2024-11-09 10:00' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '62e5039d-882f-50ed-893a-881bb16f53ff' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '0020f56d-908d-5942-b2d9-e08961adb754' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('0020f56d-908d-5942-b2d9-e08961adb754') where tied group by part, rank loop perform public.record_tie_decision('0020f56d-908d-5942-b2d9-e08961adb754', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('0020f56d-908d-5942-b2d9-e08961adb754', 'tournament_structure') where exists (select 1 from public.competitions where id = '0020f56d-908d-5942-b2d9-e08961adb754' and status <> 'finished');
-- Male Longsword: elimination, 9 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('76039be0-04de-5ac4-a3e8-a2456bd6109e', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Round of 16', 1, null, '7ca79d92-31e0-568b-8300-a2a556b1a8ce', '8da658db-985c-5572-b5c6-5445a3d991cb', 'Ring 2', (timestamp '2024-11-09 10:00' at time zone 'America/Edmonton'), 8),
  ('51b54ed1-ee70-526b-9054-033c2c870ad0', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Quarterfinal', 0, null, 'a9cf8cae-de88-504a-99f4-e62455fa3de8', null, 'Ring 2', (timestamp '2024-11-09 10:10' at time zone 'America/Edmonton'), 8),
  ('cf49e7c8-3dea-59d9-aff1-058f9e99b36e', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Quarterfinal', 1, null, '48a0cc57-3c1f-51d7-b26f-42fe160d7352', '3bae1753-a159-5326-86d6-f25584d73748', 'Ring 2', (timestamp '2024-11-09 10:20' at time zone 'America/Edmonton'), 8),
  ('4e263222-d147-579e-a3ce-0af70b22da5b', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Quarterfinal', 2, null, '95203029-b2b2-5ff0-8dc7-83b084b01a16', 'aa067d82-9d8e-50e5-b573-8813d8a0ec87', 'Ring 2', (timestamp '2024-11-09 10:30' at time zone 'America/Edmonton'), 8),
  ('c4d25a24-a1de-5012-8e3b-b3e2c6e5f3c1', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Quarterfinal', 3, null, 'ab326369-bf05-509d-a2bb-9022c6d4c4d5', '180d3656-acad-531c-95cd-df0afdb5fd96', 'Ring 2', (timestamp '2024-11-09 10:40' at time zone 'America/Edmonton'), 8),
  ('65ff45d5-d7f1-5d39-8926-9ea87168dac7', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2024-11-09 10:50' at time zone 'America/Edmonton'), 8),
  ('c3de3b20-2d61-557a-98da-5c1d4c84971d', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2024-11-09 11:00' at time zone 'America/Edmonton'), 8),
  ('81f42746-d65d-5f76-8c16-72be558ee0d1', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2024-11-09 11:10' at time zone 'America/Edmonton'), 8),
  ('b2f01c33-b3c6-59a8-aeec-c89b560103d4', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2024-11-09 11:20' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('76039be0-04de-5ac4-a3e8-a2456bd6109e'::uuid, '51b54ed1-ee70-526b-9054-033c2c870ad0'::uuid, 'b'),
  ('51b54ed1-ee70-526b-9054-033c2c870ad0'::uuid, '65ff45d5-d7f1-5d39-8926-9ea87168dac7'::uuid, 'a'),
  ('cf49e7c8-3dea-59d9-aff1-058f9e99b36e'::uuid, '65ff45d5-d7f1-5d39-8926-9ea87168dac7'::uuid, 'b'),
  ('4e263222-d147-579e-a3ce-0af70b22da5b'::uuid, 'c3de3b20-2d61-557a-98da-5c1d4c84971d'::uuid, 'a'),
  ('c4d25a24-a1de-5012-8e3b-b3e2c6e5f3c1'::uuid, 'c3de3b20-2d61-557a-98da-5c1d4c84971d'::uuid, 'b'),
  ('65ff45d5-d7f1-5d39-8926-9ea87168dac7'::uuid, '81f42746-d65d-5f76-8c16-72be558ee0d1'::uuid, 'a'),
  ('c3de3b20-2d61-557a-98da-5c1d4c84971d'::uuid, '81f42746-d65d-5f76-8c16-72be558ee0d1'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,1]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '76039be0-04de-5ac4-a3e8-a2456bd6109e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[0,4],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '51b54ed1-ee70-526b-9054-033c2c870ad0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 7, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,7]},"totals":{"a":0,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'cf49e7c8-3dea-59d9-aff1-058f9e99b36e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 3, '{"kind":"duel","rounds":{"a":[2,4],"b":[1,2]},"totals":{"a":6,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '4e263222-d147-579e-a3ce-0af70b22da5b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 6, 8, '{"kind":"duel","rounds":{"a":[3,1,1,0,1],"b":[2,2,1,1,2]},"totals":{"a":6,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'c4d25a24-a1de-5012-8e3b-b3e2c6e5f3c1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 4, '{"kind":"duel","rounds":{"a":[0,0,0,3,1,2],"b":[0,1,0,2,1,0]},"totals":{"a":6,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '65ff45d5-d7f1-5d39-8926-9ea87168dac7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 10, 8, '{"kind":"duel","rounds":{"a":[1,2,0,1,1,1,1,3],"b":[0,3,1,0,1,0,2,1]},"totals":{"a":10,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'c3de3b20-2d61-557a-98da-5c1d4c84971d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 10, '{"kind":"duel","rounds":{"a":[1,4],"b":[6,4]},"totals":{"a":5,"b":10}}'::jsonb, m.version) from public.matches m where m.id = '81f42746-d65d-5f76-8c16-72be558ee0d1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[0,2],"b":[2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'b2f01c33-b3c6-59a8-aeec-c89b560103d4' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '9cbce0bb-d25e-5ed9-b468-efe31c720def' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('9cbce0bb-d25e-5ed9-b468-efe31c720def') where tied group by part, rank loop perform public.record_tie_decision('9cbce0bb-d25e-5ed9-b468-efe31c720def', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('9cbce0bb-d25e-5ed9-b468-efe31c720def', 'tournament_structure') where exists (select 1 from public.competitions where id = '9cbce0bb-d25e-5ed9-b468-efe31c720def' and status <> 'finished');
-- Female Sword & Shield: pools_elimination, 10 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('a0e222ca-945a-5758-9a21-b0297db46b02', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 1', 0, 'A', 'c2a88160-f7cd-5228-8b85-b6f181ff661a', '84253b86-abbd-5956-b06e-61f5e591084c', 'Ring 3', (timestamp '2024-11-09 10:00' at time zone 'America/Edmonton'), 8),
  ('046d4485-a3a1-5332-8bf2-eac2ce6a1b24', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 1', 1, 'A', '542cfedb-b48e-52b7-9d2d-2ead098f8ae0', '35e8a1b2-dd29-5b8d-a522-2dff75edd19b', 'Ring 3', (timestamp '2024-11-09 10:10' at time zone 'America/Edmonton'), 8),
  ('4b8d0e65-b49f-511e-92bd-5e289b803620', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 2', 0, 'A', '84253b86-abbd-5956-b06e-61f5e591084c', '5771093c-e124-52d6-8616-ed1bd4ccabd9', 'Ring 3', (timestamp '2024-11-09 10:20' at time zone 'America/Edmonton'), 8),
  ('1cc84fd4-d44c-5573-8415-341e59ecd951', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 2', 1, 'A', 'c2a88160-f7cd-5228-8b85-b6f181ff661a', '542cfedb-b48e-52b7-9d2d-2ead098f8ae0', 'Ring 3', (timestamp '2024-11-09 10:30' at time zone 'America/Edmonton'), 8),
  ('e51bd5b6-49ce-5d20-8b42-530e04b39b55', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 3', 0, 'A', '5771093c-e124-52d6-8616-ed1bd4ccabd9', '35e8a1b2-dd29-5b8d-a522-2dff75edd19b', 'Ring 3', (timestamp '2024-11-09 10:40' at time zone 'America/Edmonton'), 8),
  ('95c1e487-4e53-5a01-9a9e-65d68b9659d0', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 3', 1, 'A', '84253b86-abbd-5956-b06e-61f5e591084c', '542cfedb-b48e-52b7-9d2d-2ead098f8ae0', 'Ring 3', (timestamp '2024-11-09 10:50' at time zone 'America/Edmonton'), 8),
  ('d239bb3a-4a8c-54f7-a946-e91e8cddece0', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 4', 0, 'A', '542cfedb-b48e-52b7-9d2d-2ead098f8ae0', '5771093c-e124-52d6-8616-ed1bd4ccabd9', 'Ring 3', (timestamp '2024-11-09 11:00' at time zone 'America/Edmonton'), 8),
  ('e576919b-82ab-5bc9-bfa0-df9dbabb9c00', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 4', 1, 'A', '35e8a1b2-dd29-5b8d-a522-2dff75edd19b', 'c2a88160-f7cd-5228-8b85-b6f181ff661a', 'Ring 3', (timestamp '2024-11-09 11:10' at time zone 'America/Edmonton'), 8),
  ('abe6a48c-6354-51a4-8a1f-6dcf8a8fce28', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 5', 0, 'A', '5771093c-e124-52d6-8616-ed1bd4ccabd9', 'c2a88160-f7cd-5228-8b85-b6f181ff661a', 'Ring 3', (timestamp '2024-11-09 11:20' at time zone 'America/Edmonton'), 8),
  ('a74d437f-5157-5a19-8491-3785f7514581', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 5', 1, 'A', '35e8a1b2-dd29-5b8d-a522-2dff75edd19b', '84253b86-abbd-5956-b06e-61f5e591084c', 'Ring 3', (timestamp '2024-11-09 11:30' at time zone 'America/Edmonton'), 8),
  ('7bfaf48b-ba5d-5f34-b82f-4f442077cb76', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 1', 0, 'B', '238a3305-3b14-5c4e-a42d-39d0cff632d3', '0f8ac5dd-671f-5d1b-804c-b62622c9bc5b', 'Ring 3', (timestamp '2024-11-09 11:40' at time zone 'America/Edmonton'), 8),
  ('f6be1b2a-7297-5a23-81e6-24a83d959f5a', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 1', 1, 'B', '3981405f-cded-5544-829d-65101db3f3b8', '668064e0-bbd7-5be0-98d6-fde707b78cdd', 'Ring 3', (timestamp '2024-11-09 11:50' at time zone 'America/Edmonton'), 8),
  ('d80ffa5e-6d39-5ba5-9dca-a6db2767d920', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 2', 0, 'B', '0f8ac5dd-671f-5d1b-804c-b62622c9bc5b', 'e11cde15-15ba-590c-bd72-167f1e5e1bd4', 'Ring 3', (timestamp '2024-11-09 12:00' at time zone 'America/Edmonton'), 8),
  ('ce90b4c0-8c4d-5ad0-af40-0af3afe6e511', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 2', 1, 'B', '238a3305-3b14-5c4e-a42d-39d0cff632d3', '3981405f-cded-5544-829d-65101db3f3b8', 'Ring 3', (timestamp '2024-11-09 12:10' at time zone 'America/Edmonton'), 8),
  ('98fb9b02-cb0b-5a3b-ae6e-390f51f5f1db', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 3', 0, 'B', 'e11cde15-15ba-590c-bd72-167f1e5e1bd4', '668064e0-bbd7-5be0-98d6-fde707b78cdd', 'Ring 3', (timestamp '2024-11-09 12:20' at time zone 'America/Edmonton'), 8),
  ('2b976ed1-f65c-5772-b626-8ee26a507bfe', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 3', 1, 'B', '0f8ac5dd-671f-5d1b-804c-b62622c9bc5b', '3981405f-cded-5544-829d-65101db3f3b8', 'Ring 3', (timestamp '2024-11-09 12:30' at time zone 'America/Edmonton'), 8),
  ('f4dd63b6-c158-52be-8540-960eeb4fe795', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 4', 0, 'B', '3981405f-cded-5544-829d-65101db3f3b8', 'e11cde15-15ba-590c-bd72-167f1e5e1bd4', 'Ring 3', (timestamp '2024-11-09 12:40' at time zone 'America/Edmonton'), 8),
  ('38d61792-e470-525c-bb4e-ba216fbfa7d7', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 4', 1, 'B', '668064e0-bbd7-5be0-98d6-fde707b78cdd', '238a3305-3b14-5c4e-a42d-39d0cff632d3', 'Ring 3', (timestamp '2024-11-09 12:50' at time zone 'America/Edmonton'), 8),
  ('bd783adc-9014-5d28-ae41-ff9877d5d96b', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 5', 0, 'B', 'e11cde15-15ba-590c-bd72-167f1e5e1bd4', '238a3305-3b14-5c4e-a42d-39d0cff632d3', 'Ring 3', (timestamp '2024-11-09 13:00' at time zone 'America/Edmonton'), 8),
  ('36bbc34c-924d-5b1a-8c2b-f3ada63bb984', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'pool', 'Round 5', 1, 'B', '668064e0-bbd7-5be0-98d6-fde707b78cdd', '0f8ac5dd-671f-5d1b-804c-b62622c9bc5b', 'Ring 3', (timestamp '2024-11-09 13:10' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[3,2],"b":[1,0]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'a0e222ca-945a-5758-9a21-b0297db46b02' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[1,3]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '046d4485-a3a1-5332-8bf2-eac2ce6a1b24' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[2,0],"b":[2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '4b8d0e65-b49f-511e-92bd-5e289b803620' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[5,0]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '1cc84fd4-d44c-5573-8415-341e59ecd951' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[1,4],"b":[1,1]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'e51bd5b6-49ce-5d20-8b42-530e04b39b55' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[3,1],"b":[0,2]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '95c1e487-4e53-5a01-9a9e-65d68b9659d0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 8, '{"kind":"duel","rounds":{"a":[0,3,1,1],"b":[4,0,0,4]},"totals":{"a":5,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'd239bb3a-4a8c-54f7-a946-e91e8cddece0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[1,2,1,1,0],"b":[0,3,0,1,3]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'e576919b-82ab-5bc9-bfa0-df9dbabb9c00' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 14, 10, '{"kind":"duel","rounds":{"a":[0,3,2,2,2,5],"b":[2,0,3,3,0,2]},"totals":{"a":14,"b":10}}'::jsonb, m.version) from public.matches m where m.id = 'abe6a48c-6354-51a4-8a1f-6dcf8a8fce28' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[2,0],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'a74d437f-5157-5a19-8491-3785f7514581' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[1,1],"b":[1,4]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '7bfaf48b-ba5d-5f34-b82f-4f442077cb76' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'f6be1b2a-7297-5a23-81e6-24a83d959f5a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'd80ffa5e-6d39-5ba5-9dca-a6db2767d920' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[1,1],"b":[2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ce90b4c0-8c4d-5ad0-af40-0af3afe6e511' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[1,1,2],"b":[0,1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '98fb9b02-cb0b-5a3b-ae6e-390f51f5f1db' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 0, '{"kind":"duel","rounds":{"a":[4,2],"b":[0,0]},"totals":{"a":6,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '2b976ed1-f65c-5772-b626-8ee26a507bfe' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 8, '{"kind":"duel","rounds":{"a":[2,1,1,0],"b":[3,0,1,4]},"totals":{"a":4,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'f4dd63b6-c158-52be-8540-960eeb4fe795' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[1,1],"b":[3,1]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '38d61792-e470-525c-bb4e-ba216fbfa7d7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,1]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'bd783adc-9014-5d28-ae41-ff9877d5d96b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,3]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '36bbc34c-924d-5b1a-8c2b-f3ada63bb984' and m.queue_state <> 'final';
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('7b446433-0508-5bad-902a-29c404a79c96', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'elimination', 'Semifinal', 0, null, '5771093c-e124-52d6-8616-ed1bd4ccabd9', '0f8ac5dd-671f-5d1b-804c-b62622c9bc5b', 'Ring 3', (timestamp '2024-11-09 13:20' at time zone 'America/Edmonton'), 8),
  ('bc1c57e8-412f-58c6-9ed8-3f195e4ca1c2', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'elimination', 'Semifinal', 1, null, 'e11cde15-15ba-590c-bd72-167f1e5e1bd4', '35e8a1b2-dd29-5b8d-a522-2dff75edd19b', 'Ring 3', (timestamp '2024-11-09 13:30' at time zone 'America/Edmonton'), 8),
  ('193e566a-cb8c-55dc-81de-cf805a948375', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2024-11-09 13:40' at time zone 'America/Edmonton'), 8),
  ('efa65437-d012-5d48-a313-e4f7dd1c3ecd', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2024-11-09 13:50' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('7b446433-0508-5bad-902a-29c404a79c96'::uuid, '193e566a-cb8c-55dc-81de-cf805a948375'::uuid, 'a'),
  ('bc1c57e8-412f-58c6-9ed8-3f195e4ca1c2'::uuid, '193e566a-cb8c-55dc-81de-cf805a948375'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '7b446433-0508-5bad-902a-29c404a79c96' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[2,2],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'bc1c57e8-412f-58c6-9ed8-3f195e4ca1c2' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 6, '{"kind":"duel","rounds":{"a":[2,2],"b":[1,5]},"totals":{"a":4,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '193e566a-cb8c-55dc-81de-cf805a948375' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[1,1],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'efa65437-d012-5d48-a313-e4f7dd1c3ecd' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('3dd7f748-fdf9-5fdf-ad82-6b7332212a3d') where tied group by part, rank loop perform public.record_tie_decision('3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'tournament_structure') where exists (select 1 from public.competitions where id = '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d' and status <> 'finished');
-- Male Polearm: round_robin, 5 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('3b912427-a95e-51c8-8b1b-965ce6d00f12', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 1', 0, null, '655d162a-054d-5a6d-ab21-95b0f909b6ba', '7516f8f1-cc51-53dc-800f-4359f8301ccd', 'Ring 1', (timestamp '2024-11-09 10:17' at time zone 'America/Edmonton'), 8),
  ('dfb8ec45-ede4-5459-971a-790d8aa99a28', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 1', 1, null, 'caedb686-70dc-544c-ad17-1466524b4212', '32eebfd5-8d70-5baa-9f1f-42747d3b17ec', 'Ring 1', (timestamp '2024-11-09 10:27' at time zone 'America/Edmonton'), 8),
  ('8a63f242-0d0f-5347-90f8-c247e1e79d41', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 2', 0, null, '7516f8f1-cc51-53dc-800f-4359f8301ccd', 'e46421bd-2a44-5a45-92d3-097a6c1fe26b', 'Ring 1', (timestamp '2024-11-09 10:37' at time zone 'America/Edmonton'), 8),
  ('ca7e7454-eb8e-54d5-985f-3f5b6aefbbe2', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 2', 1, null, '655d162a-054d-5a6d-ab21-95b0f909b6ba', 'caedb686-70dc-544c-ad17-1466524b4212', 'Ring 1', (timestamp '2024-11-09 10:47' at time zone 'America/Edmonton'), 8),
  ('2859954e-12c4-59e4-8669-5fa8d9e3d5ef', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 3', 0, null, 'e46421bd-2a44-5a45-92d3-097a6c1fe26b', '32eebfd5-8d70-5baa-9f1f-42747d3b17ec', 'Ring 1', (timestamp '2024-11-09 10:57' at time zone 'America/Edmonton'), 8),
  ('87ddb545-7d37-5178-88a6-4dd2fd170af5', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 3', 1, null, '7516f8f1-cc51-53dc-800f-4359f8301ccd', 'caedb686-70dc-544c-ad17-1466524b4212', 'Ring 1', (timestamp '2024-11-09 11:07' at time zone 'America/Edmonton'), 8),
  ('85f2fb29-a094-5b69-ba97-74499596114a', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 4', 0, null, 'caedb686-70dc-544c-ad17-1466524b4212', 'e46421bd-2a44-5a45-92d3-097a6c1fe26b', 'Ring 1', (timestamp '2024-11-09 11:17' at time zone 'America/Edmonton'), 8),
  ('8d9f085b-d6a3-5879-b690-d140127ef2b8', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 4', 1, null, '32eebfd5-8d70-5baa-9f1f-42747d3b17ec', '655d162a-054d-5a6d-ab21-95b0f909b6ba', 'Ring 1', (timestamp '2024-11-09 11:27' at time zone 'America/Edmonton'), 8),
  ('c873e887-ae2a-5e37-b478-2cc3c1576755', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 5', 0, null, 'e46421bd-2a44-5a45-92d3-097a6c1fe26b', '655d162a-054d-5a6d-ab21-95b0f909b6ba', 'Ring 1', (timestamp '2024-11-09 11:37' at time zone 'America/Edmonton'), 8),
  ('6f8d82d9-2cff-5a1d-8b81-54fb81635aa1', 'd23b1270-5964-5596-a90a-177eec066cec', 'round_robin', 'Round 5', 1, null, '32eebfd5-8d70-5baa-9f1f-42747d3b17ec', '7516f8f1-cc51-53dc-800f-4359f8301ccd', 'Ring 1', (timestamp '2024-11-09 11:47' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 8, 6, '{"kind":"duel","rounds":{"a":[1,3,0,2,2],"b":[2,2,0,2,0]},"totals":{"a":8,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '3b912427-a95e-51c8-8b1b-965ce6d00f12' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,3]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'dfb8ec45-ede4-5459-971a-790d8aa99a28' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '8a63f242-0d0f-5347-90f8-c247e1e79d41' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,1,1],"b":[2,0,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'ca7e7454-eb8e-54d5-985f-3f5b6aefbbe2' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[1,3],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '2859954e-12c4-59e4-8669-5fa8d9e3d5ef' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 8, 1, '{"kind":"duel","rounds":{"a":[5,3],"b":[0,1]},"totals":{"a":8,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '87ddb545-7d37-5178-88a6-4dd2fd170af5' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 6, '{"kind":"duel","rounds":{"a":[1,1],"b":[4,2]},"totals":{"a":2,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '85f2fb29-a094-5b69-ba97-74499596114a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[2,1],"b":[2,3]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '8d9f085b-d6a3-5879-b690-d140127ef2b8' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 4, '{"kind":"duel","rounds":{"a":[0,0,2,0,2,3],"b":[0,0,2,0,2,0]},"totals":{"a":7,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'c873e887-ae2a-5e37-b478-2cc3c1576755' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 6, '{"kind":"duel","rounds":{"a":[0,1],"b":[3,3]},"totals":{"a":1,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '6f8d82d9-2cff-5a1d-8b81-54fb81635aa1' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'd23b1270-5964-5596-a90a-177eec066cec' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('d23b1270-5964-5596-a90a-177eec066cec') where tied group by part, rank loop perform public.record_tie_decision('d23b1270-5964-5596-a90a-177eec066cec', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('d23b1270-5964-5596-a90a-177eec066cec', 'tournament_structure') where exists (select 1 from public.competitions where id = 'd23b1270-5964-5596-a90a-177eec066cec' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '0020f56d-908d-5942-b2d9-e08961adb754', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '9cbce0bb-d25e-5ed9-b468-efe31c720def', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '3dd7f748-fdf9-5fdf-ad82-6b7332212a3d', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'd23b1270-5964-5596-a90a-177eec066cec', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = 'ce770d56-ddcb-5993-ae8e-67652373ff34' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = 'ce770d56-ddcb-5993-ae8e-67652373ff34' and m.queue_state = 'final';
update public.audit_log set at = (date '2024-11-10' + time '21:00') at time zone 'America/Edmonton' where event_id = 'ce770d56-ddcb-5993-ae8e-67652373ff34';
commit;
