-- NACL-test fictional dataset: Prairie Siege-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'prairie-siege-test', 'Prairie Siege-test', 'Southern Alberta season opener hosted by Crimson Stags-test.', 'tournament', 'published', 'Exhibition Park Hall-test', 'Lethbridge', 'AB', 'CA', 'America/Edmonton', 0, date '2025-03-15', date '2025-03-16', 'e9de392a-a969-592b-809d-fe5732f32cd7', 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'efe22c3e-9535-5607-9f69-ca0db8246165');
select public.set_event_organization('50a32e72-97da-5e2f-9657-fb9c0a8b0efc', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('c2a11d28-355e-54ba-8e68-ffb546b67c6d', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Male 5v5', '5v5', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('840c0164-a61d-5e5c-b72d-f920bdd0135a', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Female 5v5', '5v5', 'women', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 20),
  ('2f469480-3a23-5e0b-8f01-25b047d7f816', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Male Longsword', 'longsword', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 30),
  ('efb382ae-9a3f-5815-a567-efe6e2e23035', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Female Longsword', 'longsword', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 40),
  ('4574050d-94c8-5b0c-a101-aa751079dc49', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Male Sword & Shield', 'sword_shield', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 50),
  ('1568aa86-ff64-51a5-b996-9065a397de58', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Female Sword & Shield', 'sword_shield', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 60),
  ('da95c9e1-a9d1-5b87-8116-64b101397a00', '50a32e72-97da-5e2f-9657-fb9c0a8b0efc', 'Male Polearm', 'polearm', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 70)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('3c63fa73-a6b3-5bcf-810c-23a3905118f3', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('1c8d048b-2543-5a35-8c31-2f0a09e069c2', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('1ede42aa-f4f9-5ae0-9e77-89148263eab8', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', '5796049c-2e49-521c-b959-47744fa8c73f', null, 'checked_in'),
  ('401fb808-8b5b-5190-aab5-16374c761991', '840c0164-a61d-5e5c-b72d-f920bdd0135a', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('25d2d527-05e4-5581-a7f5-6feb72ed37fb', '840c0164-a61d-5e5c-b72d-f920bdd0135a', 'e9de392a-a969-592b-809d-fe5732f32cd7', null, 'checked_in'),
  ('3cb40f1e-728b-5fce-91b7-a43d4427bc06', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, '49c189e3-a1f5-5342-b03f-965e69b3406c', 'checked_in'),
  ('01c9058a-9794-5faa-bfd5-ebd118ffa3a0', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, '97d5d06f-fcbe-5363-875c-abb48e8c9cbc', 'checked_in'),
  ('6d0908f6-a581-536a-8c21-04b943ed92f0', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, 'd2ea0e0b-da23-5e24-802d-85145d3f616f', 'checked_in'),
  ('d95676e5-23b7-5d80-9c23-4d436fa935c0', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, 'aa6336d6-f73e-5fa9-987f-556bf20050d8', 'checked_in'),
  ('2fc16eb9-2ad3-5474-8c11-6e182f1e5097', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, 'e3b4a9f7-0116-5514-b4ba-e76cfc0ee774', 'checked_in'),
  ('cc4bf918-d479-541a-a3d7-22414c034538', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, '88d259b3-3d84-5796-bdcb-c2fdfd8b09ed', 'checked_in'),
  ('8cc4cab8-c095-55d7-a70b-b5f59971fae9', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, 'c2114868-da44-5a82-a1d3-f91f5326285f', 'checked_in'),
  ('c727bae5-1bb5-5191-9387-0f10c61e66bc', '2f469480-3a23-5e0b-8f01-25b047d7f816', null, '31375f7d-13ba-5a5f-95ec-75173fd0c9a1', 'checked_in'),
  ('f00eef93-2563-5ac6-bad7-34593b56c5bd', 'efb382ae-9a3f-5815-a567-efe6e2e23035', null, 'f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61', 'checked_in'),
  ('a2ab3194-9177-5796-8a51-c3010a9ac279', 'efb382ae-9a3f-5815-a567-efe6e2e23035', null, 'a92a1c83-58d6-572d-9736-27fde0c87cf7', 'checked_in'),
  ('5d5a2dc9-c08b-5c8a-b034-97dd7b890826', 'efb382ae-9a3f-5815-a567-efe6e2e23035', null, '0debf14e-901a-5dde-a288-533867b19c6e', 'checked_in'),
  ('97e87686-2c04-5ed2-95db-ebc72578e463', 'efb382ae-9a3f-5815-a567-efe6e2e23035', null, 'ccd25c59-7eec-5757-bff1-3437c26baed8', 'checked_in'),
  ('2577b417-7bf7-5e23-b1a9-3763e8714d7e', 'efb382ae-9a3f-5815-a567-efe6e2e23035', null, 'a84d9159-737e-54fd-ad21-cbbe6152d754', 'checked_in'),
  ('16c4484d-43ed-55a8-927f-3a3affcf969a', 'efb382ae-9a3f-5815-a567-efe6e2e23035', null, '9890f7c8-373a-5cf8-b06c-34ea20a58304', 'checked_in'),
  ('0a2c5cdf-215d-5c6b-bf39-739f036efbce', '4574050d-94c8-5b0c-a101-aa751079dc49', null, '72ab5bcb-c669-59a6-9865-86a0a151bc59', 'checked_in'),
  ('cbb9d07d-284d-529c-b9bc-d19ac89e8ead', '4574050d-94c8-5b0c-a101-aa751079dc49', null, 'ff6d3454-18ef-5175-9d2b-56f676185804', 'checked_in'),
  ('b2499337-3da3-536a-ba50-e3ba392eb37d', '4574050d-94c8-5b0c-a101-aa751079dc49', null, '4a28fccb-ff24-506e-8459-b2a304fb4784', 'checked_in'),
  ('e740f17d-1c50-53bf-a726-aea9d0368d43', '4574050d-94c8-5b0c-a101-aa751079dc49', null, '74aade55-9f48-5ddd-867a-c465dcdc36e0', 'checked_in'),
  ('284480de-9ea6-55f0-a5bc-0dbad10da763', '4574050d-94c8-5b0c-a101-aa751079dc49', null, 'd3460606-8729-5cfb-a130-125cbbe8bcc6', 'checked_in'),
  ('0fdeae2a-0059-50a7-b0d5-61c8941d3fd3', '4574050d-94c8-5b0c-a101-aa751079dc49', null, 'cb21b06a-886b-5e1a-9453-1c173a5168f9', 'checked_in'),
  ('ab6f85e6-7b42-52e4-86bf-adaf6b5067aa', '4574050d-94c8-5b0c-a101-aa751079dc49', null, '200ae42d-0337-5186-ab5e-51d6f011162f', 'checked_in'),
  ('1321af75-e696-5704-b71d-16eb67bfb8ef', '4574050d-94c8-5b0c-a101-aa751079dc49', null, 'b181793f-6729-5349-8392-78e65113b857', 'checked_in'),
  ('638bdd08-07e0-5cf1-be9c-15572c667fac', '1568aa86-ff64-51a5-b996-9065a397de58', null, 'faaae965-8f7f-5c9d-8300-0d6cf7cf6b75', 'checked_in'),
  ('f466741d-fdf6-5d9f-8af4-23a4761456ef', '1568aa86-ff64-51a5-b996-9065a397de58', null, '285f8b35-de1b-5ade-82c6-4fe0a0a132d9', 'checked_in'),
  ('92d9a8dc-b127-5bff-93c1-8513b9607d76', '1568aa86-ff64-51a5-b996-9065a397de58', null, '8a0b0f89-6e54-548f-938c-84238b1e23e1', 'checked_in'),
  ('1fcd22b0-1c78-5cc7-837c-2f11001ab3a4', '1568aa86-ff64-51a5-b996-9065a397de58', null, '48e29b2c-61a9-5986-88bf-44714334aa9d', 'checked_in'),
  ('9b21f943-6d4b-5c80-8142-b6f2653d2adf', '1568aa86-ff64-51a5-b996-9065a397de58', null, '44de541c-49d9-5576-bad7-2bcd7f194801', 'checked_in'),
  ('b37d8d7c-3928-57c7-b858-51b8dec6f588', '1568aa86-ff64-51a5-b996-9065a397de58', null, 'f59071d8-f158-5947-ba7a-7ff8533d06e5', 'checked_in'),
  ('07b3d0e8-e381-53e9-8b5e-5601199da05e', '1568aa86-ff64-51a5-b996-9065a397de58', null, 'a8964f93-eda0-51d9-a592-43792c58b827', 'checked_in'),
  ('4d8bb515-a50d-547e-b25c-4604a509b7a8', '1568aa86-ff64-51a5-b996-9065a397de58', null, 'dd3afd51-2fca-58cd-8d14-006dec7363a4', 'checked_in'),
  ('71789294-01ec-5955-a181-5759ed955f03', 'da95c9e1-a9d1-5b87-8116-64b101397a00', null, '151f1b02-af6f-5a34-b0cb-a056556d730a', 'checked_in'),
  ('792765ae-e210-5900-a7b7-1280e2a43509', 'da95c9e1-a9d1-5b87-8116-64b101397a00', null, '5385df95-b791-5de5-a10f-9db8491e2dbc', 'checked_in'),
  ('498f82ac-2590-5699-bb55-633f55fa1cca', 'da95c9e1-a9d1-5b87-8116-64b101397a00', null, '0e28a5bf-3ca5-50ce-bf11-142105c58181', 'checked_in'),
  ('3ca3434e-7143-5895-90c2-16a8f4f4ef1e', 'da95c9e1-a9d1-5b87-8116-64b101397a00', null, '1fcb6cfe-8069-5c6d-96dd-56ea1b461f7b', 'checked_in'),
  ('5c74f4cc-74bf-5e53-90af-be7de2e3f02b', 'da95c9e1-a9d1-5b87-8116-64b101397a00', null, '695e3415-b6f8-5182-94d9-d8e4904c74e6', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('3c63fa73-a6b3-5bcf-810c-23a3905118f3', '[{"fighter_id":"b9551194-d28a-50e3-9bfc-36c446fa8f54","role":"fighter"},{"fighter_id":"49c189e3-a1f5-5342-b03f-965e69b3406c","role":"fighter"},{"fighter_id":"72ab5bcb-c669-59a6-9865-86a0a151bc59","role":"fighter"},{"fighter_id":"e0e182fe-bce4-5347-ac8c-ac85f8f10fd5","role":"fighter"},{"fighter_id":"ff6d3454-18ef-5175-9d2b-56f676185804","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = 'c2a11d28-355e-54ba-8e68-ffb546b67c6d' and status <> 'finished');
select public.set_entry_roster('1c8d048b-2543-5a35-8c31-2f0a09e069c2', '[{"fighter_id":"e3b4a9f7-0116-5514-b4ba-e76cfc0ee774","role":"fighter"},{"fighter_id":"cb21b06a-886b-5e1a-9453-1c173a5168f9","role":"fighter"},{"fighter_id":"0e28a5bf-3ca5-50ce-bf11-142105c58181","role":"fighter"},{"fighter_id":"88d259b3-3d84-5796-bdcb-c2fdfd8b09ed","role":"fighter"},{"fighter_id":"151f1b02-af6f-5a34-b0cb-a056556d730a","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'c2a11d28-355e-54ba-8e68-ffb546b67c6d' and status <> 'finished');
select public.set_entry_roster('1ede42aa-f4f9-5ae0-9e77-89148263eab8', '[{"fighter_id":"695e3415-b6f8-5182-94d9-d8e4904c74e6","role":"fighter"},{"fighter_id":"b181793f-6729-5349-8392-78e65113b857","role":"fighter"},{"fighter_id":"1fcb6cfe-8069-5c6d-96dd-56ea1b461f7b","role":"fighter"},{"fighter_id":"4a28fccb-ff24-506e-8459-b2a304fb4784","role":"mercenary"},{"fighter_id":"aa6336d6-f73e-5fa9-987f-556bf20050d8","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'c2a11d28-355e-54ba-8e68-ffb546b67c6d' and status <> 'finished');
select public.set_entry_roster('401fb808-8b5b-5190-aab5-16374c761991', '[{"fighter_id":"a92a1c83-58d6-572d-9736-27fde0c87cf7","role":"fighter"},{"fighter_id":"8a0b0f89-6e54-548f-938c-84238b1e23e1","role":"fighter"},{"fighter_id":"285f8b35-de1b-5ade-82c6-4fe0a0a132d9","role":"fighter"},{"fighter_id":"27a1672b-da85-5cb1-b3d2-29f1d968da7a","role":"mercenary"},{"fighter_id":"f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '840c0164-a61d-5e5c-b72d-f920bdd0135a' and status <> 'finished');
select public.set_entry_roster('25d2d527-05e4-5581-a7f5-6feb72ed37fb', '[{"fighter_id":"d5185702-fa37-5db8-8a4d-2cb114461bcf","role":"fighter"},{"fighter_id":"48e29b2c-61a9-5986-88bf-44714334aa9d","role":"fighter"},{"fighter_id":"44de541c-49d9-5576-bad7-2bcd7f194801","role":"fighter"},{"fighter_id":"9890f7c8-373a-5cf8-b06c-34ea20a58304","role":"mercenary"},{"fighter_id":"ccd25c59-7eec-5757-bff1-3437c26baed8","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '840c0164-a61d-5e5c-b72d-f920bdd0135a' and status <> 'finished');
-- Male 5v5: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('419a254a-592a-5ea8-a1ba-52357cf8ca7d', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', 'round_robin', 'Round 1', 0, null, '3c63fa73-a6b3-5bcf-810c-23a3905118f3', '1ede42aa-f4f9-5ae0-9e77-89148263eab8', 'Ring 1', (timestamp '2025-03-15 10:00' at time zone 'America/Edmonton'), 15),
  ('3ce66b31-9d7b-50df-a8d7-7bbff7715367', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', 'round_robin', 'Round 2', 0, null, '1ede42aa-f4f9-5ae0-9e77-89148263eab8', '1c8d048b-2543-5a35-8c31-2f0a09e069c2', 'Ring 1', (timestamp '2025-03-15 10:17' at time zone 'America/Edmonton'), 15),
  ('d3f1e7cd-7b7e-5279-b004-11e8ba567e6e', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', 'round_robin', 'Round 3', 0, null, '1c8d048b-2543-5a35-8c31-2f0a09e069c2', '3c63fa73-a6b3-5bcf-810c-23a3905118f3', 'Ring 1', (timestamp '2025-03-15 10:34' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '419a254a-592a-5ea8-a1ba-52357cf8ca7d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '3ce66b31-9d7b-50df-a8d7-7bbff7715367' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'd3f1e7cd-7b7e-5279-b004-11e8ba567e6e' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'c2a11d28-355e-54ba-8e68-ffb546b67c6d' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('c2a11d28-355e-54ba-8e68-ffb546b67c6d') where tied group by part, rank loop perform public.record_tie_decision('c2a11d28-355e-54ba-8e68-ffb546b67c6d', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('c2a11d28-355e-54ba-8e68-ffb546b67c6d', 'tournament_structure') where exists (select 1 from public.competitions where id = 'c2a11d28-355e-54ba-8e68-ffb546b67c6d' and status <> 'finished');
-- Female 5v5: round_robin, 2 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('9410a319-86e8-5911-a696-02defe522064', '840c0164-a61d-5e5c-b72d-f920bdd0135a', 'round_robin', 'Round 1', 0, null, '25d2d527-05e4-5581-a7f5-6feb72ed37fb', '401fb808-8b5b-5190-aab5-16374c761991', 'Ring 2', (timestamp '2025-03-15 10:00' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '9410a319-86e8-5911-a696-02defe522064' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '840c0164-a61d-5e5c-b72d-f920bdd0135a' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('840c0164-a61d-5e5c-b72d-f920bdd0135a') where tied group by part, rank loop perform public.record_tie_decision('840c0164-a61d-5e5c-b72d-f920bdd0135a', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('840c0164-a61d-5e5c-b72d-f920bdd0135a', 'tournament_structure') where exists (select 1 from public.competitions where id = '840c0164-a61d-5e5c-b72d-f920bdd0135a' and status <> 'finished');
-- Male Longsword: elimination, 8 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('2d820c49-dfa1-5d2d-9427-7f573494c5e3', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'elimination', 'Quarterfinal', 0, null, '8cc4cab8-c095-55d7-a70b-b5f59971fae9', '2fc16eb9-2ad3-5474-8c11-6e182f1e5097', 'Ring 3', (timestamp '2025-03-15 10:00' at time zone 'America/Edmonton'), 8),
  ('9aa0256e-bc06-5c36-88f3-1b7dca9a5557', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'elimination', 'Quarterfinal', 1, null, 'd95676e5-23b7-5d80-9c23-4d436fa935c0', 'c727bae5-1bb5-5191-9387-0f10c61e66bc', 'Ring 3', (timestamp '2025-03-15 10:10' at time zone 'America/Edmonton'), 8),
  ('a44c21b0-2ae0-5988-8bfd-a5c149afdb73', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'elimination', 'Quarterfinal', 2, null, '3cb40f1e-728b-5fce-91b7-a43d4427bc06', '6d0908f6-a581-536a-8c21-04b943ed92f0', 'Ring 3', (timestamp '2025-03-15 10:20' at time zone 'America/Edmonton'), 8),
  ('3c06ee82-982f-5271-86f7-c2fcfb0bcd15', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'elimination', 'Quarterfinal', 3, null, 'cc4bf918-d479-541a-a3d7-22414c034538', '01c9058a-9794-5faa-bfd5-ebd118ffa3a0', 'Ring 3', (timestamp '2025-03-15 10:30' at time zone 'America/Edmonton'), 8),
  ('8db07cab-2663-5eb8-8eb6-0016e7c65e58', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 3', (timestamp '2025-03-15 10:40' at time zone 'America/Edmonton'), 8),
  ('661ba62c-01f9-5d92-8125-db1af4d0d0fd', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 3', (timestamp '2025-03-15 10:50' at time zone 'America/Edmonton'), 8),
  ('0cdb616c-2c71-5f5d-9aef-015e346c4fc4', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2025-03-15 11:00' at time zone 'America/Edmonton'), 8),
  ('1ea5fa4f-fa7f-5e8e-9ee2-2955f062e08c', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2025-03-15 11:10' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('2d820c49-dfa1-5d2d-9427-7f573494c5e3'::uuid, '8db07cab-2663-5eb8-8eb6-0016e7c65e58'::uuid, 'a'),
  ('9aa0256e-bc06-5c36-88f3-1b7dca9a5557'::uuid, '8db07cab-2663-5eb8-8eb6-0016e7c65e58'::uuid, 'b'),
  ('a44c21b0-2ae0-5988-8bfd-a5c149afdb73'::uuid, '661ba62c-01f9-5d92-8125-db1af4d0d0fd'::uuid, 'a'),
  ('3c06ee82-982f-5271-86f7-c2fcfb0bcd15'::uuid, '661ba62c-01f9-5d92-8125-db1af4d0d0fd'::uuid, 'b'),
  ('8db07cab-2663-5eb8-8eb6-0016e7c65e58'::uuid, '0cdb616c-2c71-5f5d-9aef-015e346c4fc4'::uuid, 'a'),
  ('661ba62c-01f9-5d92-8125-db1af4d0d0fd'::uuid, '0cdb616c-2c71-5f5d-9aef-015e346c4fc4'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[1,0],"b":[3,2]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '2d820c49-dfa1-5d2d-9427-7f573494c5e3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 7, 9, '{"kind":"duel","rounds":{"a":[2,2,3,0],"b":[3,2,3,1]},"totals":{"a":7,"b":9}}'::jsonb, m.version) from public.matches m where m.id = '9aa0256e-bc06-5c36-88f3-1b7dca9a5557' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 0, '{"kind":"duel","rounds":{"a":[4,2],"b":[0,0]},"totals":{"a":6,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'a44c21b0-2ae0-5988-8bfd-a5c149afdb73' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,3]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '3c06ee82-982f-5271-86f7-c2fcfb0bcd15' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 0, '{"kind":"duel","rounds":{"a":[3,3],"b":[0,0]},"totals":{"a":6,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '8db07cab-2663-5eb8-8eb6-0016e7c65e58' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '661ba62c-01f9-5d92-8125-db1af4d0d0fd' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[2,2]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '0cdb616c-2c71-5f5d-9aef-015e346c4fc4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[0,1],"b":[2,3]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '1ea5fa4f-fa7f-5e8e-9ee2-2955f062e08c' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '2f469480-3a23-5e0b-8f01-25b047d7f816' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('2f469480-3a23-5e0b-8f01-25b047d7f816') where tied group by part, rank loop perform public.record_tie_decision('2f469480-3a23-5e0b-8f01-25b047d7f816', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('2f469480-3a23-5e0b-8f01-25b047d7f816', 'tournament_structure') where exists (select 1 from public.competitions where id = '2f469480-3a23-5e0b-8f01-25b047d7f816' and status <> 'finished');
-- Female Longsword: round_robin, 6 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('a9d280f4-be6a-5c07-aacf-9022ad31e523', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 1', 0, null, 'a2ab3194-9177-5796-8a51-c3010a9ac279', '97e87686-2c04-5ed2-95db-ebc72578e463', 'Ring 1', (timestamp '2025-03-15 10:51' at time zone 'America/Edmonton'), 8),
  ('089ddc2d-4f34-503c-9c84-7aacb019fb79', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 1', 1, null, 'f00eef93-2563-5ac6-bad7-34593b56c5bd', '5d5a2dc9-c08b-5c8a-b034-97dd7b890826', 'Ring 1', (timestamp '2025-03-15 11:01' at time zone 'America/Edmonton'), 8),
  ('fd562336-95df-5119-90ed-02518ddeed64', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 1', 2, null, '16c4484d-43ed-55a8-927f-3a3affcf969a', '2577b417-7bf7-5e23-b1a9-3763e8714d7e', 'Ring 1', (timestamp '2025-03-15 11:11' at time zone 'America/Edmonton'), 8),
  ('b9ddb0b9-7d3e-57a1-a534-3b28e9098b97', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 2', 0, null, '5d5a2dc9-c08b-5c8a-b034-97dd7b890826', 'a2ab3194-9177-5796-8a51-c3010a9ac279', 'Ring 1', (timestamp '2025-03-15 11:21' at time zone 'America/Edmonton'), 8),
  ('2d30b049-81ac-5637-82d1-389c00285e31', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 2', 1, null, '97e87686-2c04-5ed2-95db-ebc72578e463', '2577b417-7bf7-5e23-b1a9-3763e8714d7e', 'Ring 1', (timestamp '2025-03-15 11:31' at time zone 'America/Edmonton'), 8),
  ('397d1ded-1827-536b-b99d-e26c775a20a3', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 2', 2, null, 'f00eef93-2563-5ac6-bad7-34593b56c5bd', '16c4484d-43ed-55a8-927f-3a3affcf969a', 'Ring 1', (timestamp '2025-03-15 11:41' at time zone 'America/Edmonton'), 8),
  ('6c795b7f-ee85-5eab-beb5-e7419401b207', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 3', 0, null, 'a2ab3194-9177-5796-8a51-c3010a9ac279', '2577b417-7bf7-5e23-b1a9-3763e8714d7e', 'Ring 1', (timestamp '2025-03-15 11:51' at time zone 'America/Edmonton'), 8),
  ('5ab9a11a-7f51-5884-9b31-a0367fcbc123', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 3', 1, null, '5d5a2dc9-c08b-5c8a-b034-97dd7b890826', '16c4484d-43ed-55a8-927f-3a3affcf969a', 'Ring 1', (timestamp '2025-03-15 12:01' at time zone 'America/Edmonton'), 8),
  ('98e70b68-124b-574a-a625-11099952292d', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 3', 2, null, '97e87686-2c04-5ed2-95db-ebc72578e463', 'f00eef93-2563-5ac6-bad7-34593b56c5bd', 'Ring 1', (timestamp '2025-03-15 12:11' at time zone 'America/Edmonton'), 8),
  ('267fe19d-feaa-54fe-abbc-aa578b3e4df4', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 4', 0, null, '16c4484d-43ed-55a8-927f-3a3affcf969a', 'a2ab3194-9177-5796-8a51-c3010a9ac279', 'Ring 1', (timestamp '2025-03-15 12:21' at time zone 'America/Edmonton'), 8),
  ('ce6b5d6b-a93c-55b4-9583-221b8e5858fa', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 4', 1, null, '2577b417-7bf7-5e23-b1a9-3763e8714d7e', 'f00eef93-2563-5ac6-bad7-34593b56c5bd', 'Ring 1', (timestamp '2025-03-15 12:31' at time zone 'America/Edmonton'), 8),
  ('dd633c26-6491-5a2a-ae77-f6c1fdc5f162', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 4', 2, null, '5d5a2dc9-c08b-5c8a-b034-97dd7b890826', '97e87686-2c04-5ed2-95db-ebc72578e463', 'Ring 1', (timestamp '2025-03-15 12:41' at time zone 'America/Edmonton'), 8),
  ('1e42449b-9e11-579e-baed-fba6eaec3d91', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 5', 0, null, 'a2ab3194-9177-5796-8a51-c3010a9ac279', 'f00eef93-2563-5ac6-bad7-34593b56c5bd', 'Ring 1', (timestamp '2025-03-15 12:51' at time zone 'America/Edmonton'), 8),
  ('e5572e3e-ff94-5f2d-a1ce-f2a593bf365b', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 5', 1, null, '16c4484d-43ed-55a8-927f-3a3affcf969a', '97e87686-2c04-5ed2-95db-ebc72578e463', 'Ring 1', (timestamp '2025-03-15 13:01' at time zone 'America/Edmonton'), 8),
  ('5186023f-8aba-5757-8a75-61ae349937ec', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'round_robin', 'Round 5', 2, null, '2577b417-7bf7-5e23-b1a9-3763e8714d7e', '5d5a2dc9-c08b-5c8a-b034-97dd7b890826', 'Ring 1', (timestamp '2025-03-15 13:11' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[0,2],"b":[4,0]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'a9d280f4-be6a-5c07-aacf-9022ad31e523' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[1,3],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '089ddc2d-4f34-503c-9c84-7aacb019fb79' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 7, '{"kind":"duel","rounds":{"a":[2,0,0,1,1,2,3],"b":[0,2,1,0,0,2,2]},"totals":{"a":9,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'fd562336-95df-5119-90ed-02518ddeed64' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,0,1],"b":[1,0,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'b9ddb0b9-7d3e-57a1-a534-3b28e9098b97' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[1,2],"b":[2,3]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '2d30b049-81ac-5637-82d1-389c00285e31' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 0, '{"kind":"duel","rounds":{"a":[2,4],"b":[0,0]},"totals":{"a":6,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '397d1ded-1827-536b-b99d-e26c775a20a3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 0, '{"kind":"duel","rounds":{"a":[1,4],"b":[0,0]},"totals":{"a":5,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '6c795b7f-ee85-5eab-beb5-e7419401b207' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 4, '{"kind":"duel","rounds":{"a":[0,3,3],"b":[1,1,2]},"totals":{"a":6,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '5ab9a11a-7f51-5884-9b31-a0367fcbc123' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,1]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '98e70b68-124b-574a-a625-11099952292d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[3,1]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '267fe19d-feaa-54fe-abbc-aa578b3e4df4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,2]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'ce6b5d6b-a93c-55b4-9583-221b8e5858fa' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[1,3],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'dd633c26-6491-5a2a-ae77-f6c1fdc5f162' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 4, '{"kind":"duel","rounds":{"a":[1,2,3],"b":[3,0,1]},"totals":{"a":6,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '1e42449b-9e11-579e-baed-fba6eaec3d91' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[0,1],"b":[2,2]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'e5572e3e-ff94-5f2d-a1ce-f2a593bf365b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 2, '{"kind":"duel","rounds":{"a":[3,3],"b":[1,1]},"totals":{"a":6,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '5186023f-8aba-5757-8a75-61ae349937ec' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'efb382ae-9a3f-5815-a567-efe6e2e23035' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('efb382ae-9a3f-5815-a567-efe6e2e23035') where tied group by part, rank loop perform public.record_tie_decision('efb382ae-9a3f-5815-a567-efe6e2e23035', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('efb382ae-9a3f-5815-a567-efe6e2e23035', 'tournament_structure') where exists (select 1 from public.competitions where id = 'efb382ae-9a3f-5815-a567-efe6e2e23035' and status <> 'finished');
-- Male Sword & Shield: elimination, 8 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('e9cbf12d-931f-505e-9bc5-b2e92073d7f7', '4574050d-94c8-5b0c-a101-aa751079dc49', 'elimination', 'Quarterfinal', 0, null, 'cbb9d07d-284d-529c-b9bc-d19ac89e8ead', '284480de-9ea6-55f0-a5bc-0dbad10da763', 'Ring 2', (timestamp '2025-03-15 10:17' at time zone 'America/Edmonton'), 8),
  ('0a5eb040-dd01-5333-920e-d1bce6e123d5', '4574050d-94c8-5b0c-a101-aa751079dc49', 'elimination', 'Quarterfinal', 1, null, 'ab6f85e6-7b42-52e4-86bf-adaf6b5067aa', 'b2499337-3da3-536a-ba50-e3ba392eb37d', 'Ring 2', (timestamp '2025-03-15 10:27' at time zone 'America/Edmonton'), 8),
  ('d8a16752-4bb7-5f23-8937-4263e5dd0b74', '4574050d-94c8-5b0c-a101-aa751079dc49', 'elimination', 'Quarterfinal', 2, null, '0fdeae2a-0059-50a7-b0d5-61c8941d3fd3', 'e740f17d-1c50-53bf-a726-aea9d0368d43', 'Ring 2', (timestamp '2025-03-15 10:37' at time zone 'America/Edmonton'), 8),
  ('4f62a930-044e-5141-9b5e-3184ce7fc9c3', '4574050d-94c8-5b0c-a101-aa751079dc49', 'elimination', 'Quarterfinal', 3, null, '0a2c5cdf-215d-5c6b-bf39-739f036efbce', '1321af75-e696-5704-b71d-16eb67bfb8ef', 'Ring 2', (timestamp '2025-03-15 10:47' at time zone 'America/Edmonton'), 8),
  ('66933aa7-8d47-5345-9c4c-3a5540c428c3', '4574050d-94c8-5b0c-a101-aa751079dc49', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2025-03-15 10:57' at time zone 'America/Edmonton'), 8),
  ('a76fb8cd-7cff-5973-8954-0d12417b3d23', '4574050d-94c8-5b0c-a101-aa751079dc49', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2025-03-15 11:07' at time zone 'America/Edmonton'), 8),
  ('1d46b7c4-883d-5a59-99e3-4ca8d4783c0e', '4574050d-94c8-5b0c-a101-aa751079dc49', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2025-03-15 11:17' at time zone 'America/Edmonton'), 8),
  ('ed29a8d1-c15f-55fa-badb-b592d20f8914', '4574050d-94c8-5b0c-a101-aa751079dc49', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2025-03-15 11:27' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('e9cbf12d-931f-505e-9bc5-b2e92073d7f7'::uuid, '66933aa7-8d47-5345-9c4c-3a5540c428c3'::uuid, 'a'),
  ('0a5eb040-dd01-5333-920e-d1bce6e123d5'::uuid, '66933aa7-8d47-5345-9c4c-3a5540c428c3'::uuid, 'b'),
  ('d8a16752-4bb7-5f23-8937-4263e5dd0b74'::uuid, 'a76fb8cd-7cff-5973-8954-0d12417b3d23'::uuid, 'a'),
  ('4f62a930-044e-5141-9b5e-3184ce7fc9c3'::uuid, 'a76fb8cd-7cff-5973-8954-0d12417b3d23'::uuid, 'b'),
  ('66933aa7-8d47-5345-9c4c-3a5540c428c3'::uuid, '1d46b7c4-883d-5a59-99e3-4ca8d4783c0e'::uuid, 'a'),
  ('a76fb8cd-7cff-5973-8954-0d12417b3d23'::uuid, '1d46b7c4-883d-5a59-99e3-4ca8d4783c0e'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,2]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'e9cbf12d-931f-505e-9bc5-b2e92073d7f7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[3,1],"b":[1,0]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '0a5eb040-dd01-5333-920e-d1bce6e123d5' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 3, '{"kind":"duel","rounds":{"a":[2,4],"b":[1,2]},"totals":{"a":6,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'd8a16752-4bb7-5f23-8937-4263e5dd0b74' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 7, '{"kind":"duel","rounds":{"a":[0,2],"b":[4,3]},"totals":{"a":2,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '4f62a930-044e-5141-9b5e-3184ce7fc9c3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[2,3],"b":[1,0]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '66933aa7-8d47-5345-9c4c-3a5540c428c3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[0,1,1,0],"b":[1,1,1,1]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'a76fb8cd-7cff-5973-8954-0d12417b3d23' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '1d46b7c4-883d-5a59-99e3-4ca8d4783c0e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 4, '{"kind":"duel","rounds":{"a":[0,2,1,3],"b":[0,1,2,1]},"totals":{"a":6,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ed29a8d1-c15f-55fa-badb-b592d20f8914' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '4574050d-94c8-5b0c-a101-aa751079dc49' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('4574050d-94c8-5b0c-a101-aa751079dc49') where tied group by part, rank loop perform public.record_tie_decision('4574050d-94c8-5b0c-a101-aa751079dc49', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('4574050d-94c8-5b0c-a101-aa751079dc49', 'tournament_structure') where exists (select 1 from public.competitions where id = '4574050d-94c8-5b0c-a101-aa751079dc49' and status <> 'finished');
-- Female Sword & Shield: elimination, 8 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('c5f0585e-7734-5450-88c2-1af641508287', '1568aa86-ff64-51a5-b996-9065a397de58', 'elimination', 'Quarterfinal', 0, null, '07b3d0e8-e381-53e9-8b5e-5601199da05e', '4d8bb515-a50d-547e-b25c-4604a509b7a8', 'Ring 3', (timestamp '2025-03-15 11:20' at time zone 'America/Edmonton'), 8),
  ('6cf2cf1b-d191-5c44-9c4c-50f312ac128e', '1568aa86-ff64-51a5-b996-9065a397de58', 'elimination', 'Quarterfinal', 1, null, 'b37d8d7c-3928-57c7-b858-51b8dec6f588', '92d9a8dc-b127-5bff-93c1-8513b9607d76', 'Ring 3', (timestamp '2025-03-15 11:30' at time zone 'America/Edmonton'), 8),
  ('1524a49a-d98c-57f7-a283-7cfb1e3e8671', '1568aa86-ff64-51a5-b996-9065a397de58', 'elimination', 'Quarterfinal', 2, null, '9b21f943-6d4b-5c80-8142-b6f2653d2adf', '1fcd22b0-1c78-5cc7-837c-2f11001ab3a4', 'Ring 3', (timestamp '2025-03-15 11:40' at time zone 'America/Edmonton'), 8),
  ('902255ef-9e3d-5903-91b5-1a4975d33b09', '1568aa86-ff64-51a5-b996-9065a397de58', 'elimination', 'Quarterfinal', 3, null, '638bdd08-07e0-5cf1-be9c-15572c667fac', 'f466741d-fdf6-5d9f-8af4-23a4761456ef', 'Ring 3', (timestamp '2025-03-15 11:50' at time zone 'America/Edmonton'), 8),
  ('e0eecfa1-d7dc-5bd0-b835-d7b5b1095111', '1568aa86-ff64-51a5-b996-9065a397de58', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 3', (timestamp '2025-03-15 12:00' at time zone 'America/Edmonton'), 8),
  ('3f723c96-953d-5d0b-bec5-fa43475a1c07', '1568aa86-ff64-51a5-b996-9065a397de58', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 3', (timestamp '2025-03-15 12:10' at time zone 'America/Edmonton'), 8),
  ('45db611b-654f-5c4c-b526-f8396c608a81', '1568aa86-ff64-51a5-b996-9065a397de58', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2025-03-15 12:20' at time zone 'America/Edmonton'), 8),
  ('87ef1281-e017-528a-8d27-b87abd58ff3d', '1568aa86-ff64-51a5-b996-9065a397de58', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2025-03-15 12:30' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('c5f0585e-7734-5450-88c2-1af641508287'::uuid, 'e0eecfa1-d7dc-5bd0-b835-d7b5b1095111'::uuid, 'a'),
  ('6cf2cf1b-d191-5c44-9c4c-50f312ac128e'::uuid, 'e0eecfa1-d7dc-5bd0-b835-d7b5b1095111'::uuid, 'b'),
  ('1524a49a-d98c-57f7-a283-7cfb1e3e8671'::uuid, '3f723c96-953d-5d0b-bec5-fa43475a1c07'::uuid, 'a'),
  ('902255ef-9e3d-5903-91b5-1a4975d33b09'::uuid, '3f723c96-953d-5d0b-bec5-fa43475a1c07'::uuid, 'b'),
  ('e0eecfa1-d7dc-5bd0-b835-d7b5b1095111'::uuid, '45db611b-654f-5c4c-b526-f8396c608a81'::uuid, 'a'),
  ('3f723c96-953d-5d0b-bec5-fa43475a1c07'::uuid, '45db611b-654f-5c4c-b526-f8396c608a81'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 1, 7, '{"kind":"duel","rounds":{"a":[0,1],"b":[5,2]},"totals":{"a":1,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'c5f0585e-7734-5450-88c2-1af641508287' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,2]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '6cf2cf1b-d191-5c44-9c4c-50f312ac128e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[1,1,1],"b":[2,1,2]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '1524a49a-d98c-57f7-a283-7cfb1e3e8671' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,2]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '902255ef-9e3d-5903-91b5-1a4975d33b09' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 0, '{"kind":"duel","rounds":{"a":[5,2],"b":[0,0]},"totals":{"a":7,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'e0eecfa1-d7dc-5bd0-b835-d7b5b1095111' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 10, 13, '{"kind":"duel","rounds":{"a":[2,2,1,4,1],"b":[2,1,3,3,4]},"totals":{"a":10,"b":13}}'::jsonb, m.version) from public.matches m where m.id = '3f723c96-953d-5d0b-bec5-fa43475a1c07' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[3,1,1],"b":[2,3,2]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '45db611b-654f-5c4c-b526-f8396c608a81' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 10, 8, '{"kind":"duel","rounds":{"a":[4,2,2,2],"b":[3,4,1,0]},"totals":{"a":10,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '87ef1281-e017-528a-8d27-b87abd58ff3d' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '1568aa86-ff64-51a5-b996-9065a397de58' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('1568aa86-ff64-51a5-b996-9065a397de58') where tied group by part, rank loop perform public.record_tie_decision('1568aa86-ff64-51a5-b996-9065a397de58', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('1568aa86-ff64-51a5-b996-9065a397de58', 'tournament_structure') where exists (select 1 from public.competitions where id = '1568aa86-ff64-51a5-b996-9065a397de58' and status <> 'finished');
-- Male Polearm: round_robin, 5 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('8771c959-5062-5355-a48a-26d038b3dfc5', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 1', 0, null, '5c74f4cc-74bf-5e53-90af-be7de2e3f02b', '498f82ac-2590-5699-bb55-633f55fa1cca', 'Ring 1', (timestamp '2025-03-15 13:21' at time zone 'America/Edmonton'), 8),
  ('c2a22a42-7e18-543c-bc27-94b08af66491', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 1', 1, null, '792765ae-e210-5900-a7b7-1280e2a43509', '71789294-01ec-5955-a181-5759ed955f03', 'Ring 1', (timestamp '2025-03-15 13:31' at time zone 'America/Edmonton'), 8),
  ('f66c19b8-a0b1-54c0-9650-7d1597349419', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 2', 0, null, '498f82ac-2590-5699-bb55-633f55fa1cca', '3ca3434e-7143-5895-90c2-16a8f4f4ef1e', 'Ring 1', (timestamp '2025-03-15 13:41' at time zone 'America/Edmonton'), 8),
  ('b259094c-2d78-5623-97e8-1d68ffbd4d7f', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 2', 1, null, '5c74f4cc-74bf-5e53-90af-be7de2e3f02b', '792765ae-e210-5900-a7b7-1280e2a43509', 'Ring 1', (timestamp '2025-03-15 13:51' at time zone 'America/Edmonton'), 8),
  ('0bfe2b77-e206-5853-be3c-e1d2565e0e11', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 3', 0, null, '3ca3434e-7143-5895-90c2-16a8f4f4ef1e', '71789294-01ec-5955-a181-5759ed955f03', 'Ring 1', (timestamp '2025-03-15 14:01' at time zone 'America/Edmonton'), 8),
  ('5b4581b2-53cf-534d-a4ce-dc4148e03bc3', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 3', 1, null, '498f82ac-2590-5699-bb55-633f55fa1cca', '792765ae-e210-5900-a7b7-1280e2a43509', 'Ring 1', (timestamp '2025-03-15 14:11' at time zone 'America/Edmonton'), 8),
  ('6f6b4cec-0e25-558d-ad41-1367401ad28d', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 4', 0, null, '792765ae-e210-5900-a7b7-1280e2a43509', '3ca3434e-7143-5895-90c2-16a8f4f4ef1e', 'Ring 1', (timestamp '2025-03-15 14:21' at time zone 'America/Edmonton'), 8),
  ('9a2febb7-ea0e-55a5-b9fc-e5002cfc348b', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 4', 1, null, '71789294-01ec-5955-a181-5759ed955f03', '5c74f4cc-74bf-5e53-90af-be7de2e3f02b', 'Ring 1', (timestamp '2025-03-15 14:31' at time zone 'America/Edmonton'), 8),
  ('1412a792-0628-5914-8c8f-cdbeb22d7419', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 5', 0, null, '3ca3434e-7143-5895-90c2-16a8f4f4ef1e', '5c74f4cc-74bf-5e53-90af-be7de2e3f02b', 'Ring 1', (timestamp '2025-03-15 14:41' at time zone 'America/Edmonton'), 8),
  ('9373fac9-fe04-56c0-a4cf-46166f7f1d7a', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'round_robin', 'Round 5', 1, null, '71789294-01ec-5955-a181-5759ed955f03', '498f82ac-2590-5699-bb55-633f55fa1cca', 'Ring 1', (timestamp '2025-03-15 14:51' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 5, 0, '{"kind":"duel","rounds":{"a":[2,3],"b":[0,0]},"totals":{"a":5,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '8771c959-5062-5355-a48a-26d038b3dfc5' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[0,5],"b":[2,0]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'c2a22a42-7e18-543c-bc27-94b08af66491' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[3,1],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'f66c19b8-a0b1-54c0-9650-7d1597349419' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,3]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'b259094c-2d78-5623-97e8-1d68ffbd4d7f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,1]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '0bfe2b77-e206-5853-be3c-e1d2565e0e11' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 6, '{"kind":"duel","rounds":{"a":[0,0],"b":[3,3]},"totals":{"a":0,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '5b4581b2-53cf-534d-a4ce-dc4148e03bc3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 1, '{"kind":"duel","rounds":{"a":[1,1,4],"b":[0,1,0]},"totals":{"a":6,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '6f6b4cec-0e25-558d-ad41-1367401ad28d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 0, '{"kind":"duel","rounds":{"a":[4,3],"b":[0,0]},"totals":{"a":7,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '9a2febb7-ea0e-55a5-b9fc-e5002cfc348b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 10, '{"kind":"duel","rounds":{"a":[0,1,1,2],"b":[0,1,2,7]},"totals":{"a":4,"b":10}}'::jsonb, m.version) from public.matches m where m.id = '1412a792-0628-5914-8c8f-cdbeb22d7419' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[0,1,2],"b":[0,0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '9373fac9-fe04-56c0-a4cf-46166f7f1d7a' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'da95c9e1-a9d1-5b87-8116-64b101397a00' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('da95c9e1-a9d1-5b87-8116-64b101397a00') where tied group by part, rank loop perform public.record_tie_decision('da95c9e1-a9d1-5b87-8116-64b101397a00', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('da95c9e1-a9d1-5b87-8116-64b101397a00', 'tournament_structure') where exists (select 1 from public.competitions where id = 'da95c9e1-a9d1-5b87-8116-64b101397a00' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'c2a11d28-355e-54ba-8e68-ffb546b67c6d', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '840c0164-a61d-5e5c-b72d-f920bdd0135a', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '2f469480-3a23-5e0b-8f01-25b047d7f816', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'efb382ae-9a3f-5815-a567-efe6e2e23035', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '4574050d-94c8-5b0c-a101-aa751079dc49', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '1568aa86-ff64-51a5-b996-9065a397de58', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'da95c9e1-a9d1-5b87-8116-64b101397a00', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = '50a32e72-97da-5e2f-9657-fb9c0a8b0efc' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = '50a32e72-97da-5e2f-9657-fb9c0a8b0efc' and m.queue_state = 'final';
update public.audit_log set at = (date '2025-03-16' + time '21:00') at time zone 'America/Edmonton' where event_id = '50a32e72-97da-5e2f-9657-fb9c0a8b0efc';
commit;
