-- NACL-test fictional dataset: Medicine Hat Mayhem-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'medicine-hat-mayhem-test', 'Medicine Hat Mayhem-test', 'Summer mayhem in the south-east, hosted by Steel Serpents-test.', 'tournament', 'published', 'Kinplex Arena-test', 'Medicine Hat', 'AB', 'CA', 'America/Edmonton', 0, date '2025-07-12', date '2025-07-13', 'b902f3cf-959c-5300-b019-d678b76aee3a', 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'efe22c3e-9535-5607-9f69-ca0db8246165');
select public.set_event_organization('96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('06e40c1f-4d12-5f72-b05a-cd065d288033', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Male 5v5', '5v5', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('2bb8f76c-1d36-535d-ba18-01d09f1a2673', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Female 5v5', '5v5', 'women', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 20),
  ('e144e88f-559c-5674-af99-601f06dbc989', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Male 3v3', '3v3', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 30),
  ('265db25b-1cdf-5b8c-8148-269fb9780ee5', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Male Longsword', 'longsword', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 40),
  ('9d6543ce-640f-5176-9c95-cd4d6e78bdee', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Female Longsword', 'longsword', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 50),
  ('9a0bf38c-2270-535f-8056-cfb8e618495e', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Male Sword & Shield', 'sword_shield', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 60),
  ('b18fcfc2-e16d-561d-b2da-7a85163de3b6', '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce', 'Male Polearm', 'polearm', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 70)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('99fa0f03-390a-50b1-8ef9-c6e87cf47805', '06e40c1f-4d12-5f72-b05a-cd065d288033', '4842a217-7f85-509f-aa7e-cefa2bffbfab', null, 'checked_in'),
  ('6cd4d291-9d6f-5df4-8335-5efbc1874006', '06e40c1f-4d12-5f72-b05a-cd065d288033', '9e6caec8-33a2-5b5c-97e8-89f86facf0ea', null, 'checked_in'),
  ('4ce6cae0-034e-5ad9-afed-dd8e8b9fc8a1', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', '4842a217-7f85-509f-aa7e-cefa2bffbfab', null, 'checked_in'),
  ('7c5e226c-0fc5-5a36-9625-7f7c4c5da470', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('be127d76-fad1-536d-9e84-2324918eef7d', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', 'e9de392a-a969-592b-809d-fe5732f32cd7', null, 'checked_in'),
  ('8a284e47-d186-5334-a0ce-d2751cf2c541', 'e144e88f-559c-5674-af99-601f06dbc989', '4842a217-7f85-509f-aa7e-cefa2bffbfab', null, 'checked_in'),
  ('1b49c8ba-1151-5657-82a1-a068281aac4e', 'e144e88f-559c-5674-af99-601f06dbc989', '9e6caec8-33a2-5b5c-97e8-89f86facf0ea', null, 'checked_in'),
  ('d599fcbc-bb03-5a05-9b27-09dc3b095433', 'e144e88f-559c-5674-af99-601f06dbc989', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('40a36a64-4df6-51df-a125-538193367ebf', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, 'dc986b96-be3f-5c26-914b-c1162aa0eb4b', 'checked_in'),
  ('f2929760-a9c5-5475-9b76-27178ea249dc', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, '7ba3fceb-e85e-5ed0-84a0-76915d6c6f83', 'checked_in'),
  ('490f4d99-210c-5ab5-a40f-7708848dd074', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, '88af5e4f-d812-5e43-837b-5eb6dbb92226', 'checked_in'),
  ('a35a574d-e0c7-57ba-9b53-d0f32462fe70', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, '49c189e3-a1f5-5342-b03f-965e69b3406c', 'checked_in'),
  ('db0799f2-671c-57ed-b872-d17b5c6bb995', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, 'd3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd', 'checked_in'),
  ('d8cce533-14e7-59b4-b11e-060458d591e6', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, 'df7d277f-b7dc-5d74-85f9-0a5e44bffad5', 'checked_in'),
  ('874f992d-861a-5f33-bd23-227e393481ba', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, 'd2ea0e0b-da23-5e24-802d-85145d3f616f', 'checked_in'),
  ('71692912-ffb6-5e45-88ec-3002d8629235', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, '88d259b3-3d84-5796-bdcb-c2fdfd8b09ed', 'checked_in'),
  ('e7b98b4b-081f-5fc1-a0fb-4010840d94c7', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, 'c2114868-da44-5a82-a1d3-f91f5326285f', 'checked_in'),
  ('57ecf260-4ea0-573b-89d7-032e92044d25', '265db25b-1cdf-5b8c-8148-269fb9780ee5', null, '460268e5-c451-567f-8916-b847f5089921', 'checked_in'),
  ('8c84b99b-8dff-5633-afb4-ad5dd98d9024', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, 'f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61', 'checked_in'),
  ('fc5ef8ec-62cf-56ea-83b6-5933e398fd97', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, '7b2a7b7d-ddd2-595d-9269-7efa0dbacd1a', 'checked_in'),
  ('f8efd56c-0b80-533e-b331-ccc793fd94ca', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, 'a92a1c83-58d6-572d-9736-27fde0c87cf7', 'checked_in'),
  ('c9b2d124-d7e7-55e8-99c6-d61c0608c03f', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, '0debf14e-901a-5dde-a288-533867b19c6e', 'checked_in'),
  ('145e8ddc-fa5f-5b52-b342-db15a8e65468', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, 'ccd25c59-7eec-5757-bff1-3437c26baed8', 'checked_in'),
  ('aa482bd1-4c7a-565c-8f2d-07ca849af32f', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, 'fb79f2e7-85b4-5565-b024-4a24ed929a62', 'checked_in'),
  ('452f7697-8a16-544e-a445-86bef396c092', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, 'd997ef6a-817a-5dbe-8940-a6fa9956f341', 'checked_in'),
  ('2b45b4e4-0ad4-52f8-91a2-f8b4d338eb7e', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, 'a84d9159-737e-54fd-ad21-cbbe6152d754', 'checked_in'),
  ('ec22450a-6814-52d3-acce-f957eb74f41a', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', null, '9890f7c8-373a-5cf8-b06c-34ea20a58304', 'checked_in'),
  ('45f4b8ea-d68f-5ce1-a658-d66cedae6e3f', '9a0bf38c-2270-535f-8056-cfb8e618495e', null, 'b4b23592-ecfd-5625-92ec-4224c70404c2', 'checked_in'),
  ('bf4d6806-d78d-507c-815d-7fcb8d44f6d8', '9a0bf38c-2270-535f-8056-cfb8e618495e', null, '33dae536-85e7-5060-a8b0-8eed569e82d3', 'checked_in'),
  ('7a1baf4b-ad9a-5db3-b7de-8f257f2020cd', '9a0bf38c-2270-535f-8056-cfb8e618495e', null, 'a6d7fbe4-0392-5679-9e83-3a4693aa452d', 'checked_in'),
  ('2bb73eff-b109-5bc5-bee5-7b5b02cbbe98', '9a0bf38c-2270-535f-8056-cfb8e618495e', null, '74aade55-9f48-5ddd-867a-c465dcdc36e0', 'checked_in'),
  ('28ffc28d-bc5a-5c2c-8728-4072014b571d', '9a0bf38c-2270-535f-8056-cfb8e618495e', null, 'cb21b06a-886b-5e1a-9453-1c173a5168f9', 'checked_in'),
  ('9b302e9c-f8fe-5c5f-9443-4c393e0ab48a', '9a0bf38c-2270-535f-8056-cfb8e618495e', null, '200ae42d-0337-5186-ab5e-51d6f011162f', 'checked_in'),
  ('062bf0f1-0a6f-5626-a183-4cfc4fc43b25', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', null, 'bd195699-a4ba-5049-babf-d01f743911b5', 'checked_in'),
  ('7823b820-fb0d-54a7-a14b-b0b6eec56a54', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', null, '8120e2f4-1510-5cfd-a077-7320c47a52a9', 'checked_in'),
  ('a6e1a679-362d-509a-9cd6-9bc0383a2233', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', null, '7f46df0f-b1c8-527e-aff1-d8ababc108d8', 'checked_in'),
  ('3fc90651-5704-5fef-8b4e-1e4acedf9cfe', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', null, 'c500cb85-208c-54bb-8631-dc4fc0403487', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('99fa0f03-390a-50b1-8ef9-c6e87cf47805', '[{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"fighter"},{"fighter_id":"b4b23592-ecfd-5625-92ec-4224c70404c2","role":"fighter"},{"fighter_id":"c88c4ad7-6508-52b3-a310-c9e2c4c6ba58","role":"fighter"},{"fighter_id":"bd195699-a4ba-5049-babf-d01f743911b5","role":"fighter"},{"fighter_id":"49c189e3-a1f5-5342-b03f-965e69b3406c","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '06e40c1f-4d12-5f72-b05a-cd065d288033' and status <> 'finished');
select public.set_entry_roster('6cd4d291-9d6f-5df4-8335-5efbc1874006', '[{"fighter_id":"8120e2f4-1510-5cfd-a077-7320c47a52a9","role":"fighter"},{"fighter_id":"d3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd","role":"fighter"},{"fighter_id":"a6d7fbe4-0392-5679-9e83-3a4693aa452d","role":"fighter"},{"fighter_id":"cb21b06a-886b-5e1a-9453-1c173a5168f9","role":"mercenary"},{"fighter_id":"88d259b3-3d84-5796-bdcb-c2fdfd8b09ed","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '06e40c1f-4d12-5f72-b05a-cd065d288033' and status <> 'finished');
select public.set_entry_roster('4ce6cae0-034e-5ad9-afed-dd8e8b9fc8a1', '[{"fighter_id":"7b4eb64c-041e-55c7-ade2-755393281205","role":"fighter"},{"fighter_id":"f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61","role":"fighter"},{"fighter_id":"7b2a7b7d-ddd2-595d-9269-7efa0dbacd1a","role":"fighter"},{"fighter_id":"faaae965-8f7f-5c9d-8300-0d6cf7cf6b75","role":"fighter"},{"fighter_id":"ccd25c59-7eec-5757-bff1-3437c26baed8","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '2bb8f76c-1d36-535d-ba18-01d09f1a2673' and status <> 'finished');
select public.set_entry_roster('7c5e226c-0fc5-5a36-9625-7f7c4c5da470', '[{"fighter_id":"a92a1c83-58d6-572d-9736-27fde0c87cf7","role":"fighter"},{"fighter_id":"8a0b0f89-6e54-548f-938c-84238b1e23e1","role":"fighter"},{"fighter_id":"285f8b35-de1b-5ade-82c6-4fe0a0a132d9","role":"fighter"},{"fighter_id":"a84d9159-737e-54fd-ad21-cbbe6152d754","role":"mercenary"},{"fighter_id":"0b508c1f-b0a2-524e-b471-331960200135","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '2bb8f76c-1d36-535d-ba18-01d09f1a2673' and status <> 'finished');
select public.set_entry_roster('be127d76-fad1-536d-9e84-2324918eef7d', '[{"fighter_id":"d5185702-fa37-5db8-8a4d-2cb114461bcf","role":"fighter"},{"fighter_id":"48e29b2c-61a9-5986-88bf-44714334aa9d","role":"fighter"},{"fighter_id":"44de541c-49d9-5576-bad7-2bcd7f194801","role":"fighter"},{"fighter_id":"1c29a853-dcea-582a-9561-f92c4ef9b6a3","role":"mercenary"},{"fighter_id":"9890f7c8-373a-5cf8-b06c-34ea20a58304","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '2bb8f76c-1d36-535d-ba18-01d09f1a2673' and status <> 'finished');
select public.set_entry_roster('8a284e47-d186-5334-a0ce-d2751cf2c541', '[{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"fighter"},{"fighter_id":"c88c4ad7-6508-52b3-a310-c9e2c4c6ba58","role":"fighter"},{"fighter_id":"88af5e4f-d812-5e43-837b-5eb6dbb92226","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = 'e144e88f-559c-5674-af99-601f06dbc989' and status <> 'finished');
select public.set_entry_roster('1b49c8ba-1151-5657-82a1-a068281aac4e', '[{"fighter_id":"8120e2f4-1510-5cfd-a077-7320c47a52a9","role":"fighter"},{"fighter_id":"a6d7fbe4-0392-5679-9e83-3a4693aa452d","role":"fighter"},{"fighter_id":"d3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = 'e144e88f-559c-5674-af99-601f06dbc989' and status <> 'finished');
select public.set_entry_roster('d599fcbc-bb03-5a05-9b27-09dc3b095433', '[{"fighter_id":"c2114868-da44-5a82-a1d3-f91f5326285f","role":"fighter"},{"fighter_id":"88d259b3-3d84-5796-bdcb-c2fdfd8b09ed","role":"fighter"},{"fighter_id":"31375f7d-13ba-5a5f-95ec-75173fd0c9a1","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'e144e88f-559c-5674-af99-601f06dbc989' and status <> 'finished');
-- Male 5v5: round_robin, 2 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('f9e8c143-138e-5008-bd39-0e8edec35696', '06e40c1f-4d12-5f72-b05a-cd065d288033', 'round_robin', 'Round 1', 0, null, '6cd4d291-9d6f-5df4-8335-5efbc1874006', '99fa0f03-390a-50b1-8ef9-c6e87cf47805', 'Ring 1', (timestamp '2025-07-12 10:00' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'f9e8c143-138e-5008-bd39-0e8edec35696' and m.queue_state <> 'final';
select public.finish_competition('06e40c1f-4d12-5f72-b05a-cd065d288033', 'tournament_structure') where exists (select 1 from public.competitions where id = '06e40c1f-4d12-5f72-b05a-cd065d288033' and status <> 'finished');
-- Female 5v5: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('5ae9673b-24a0-5869-be3a-c4c8190bb84c', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', 'round_robin', 'Round 1', 0, null, '4ce6cae0-034e-5ad9-afed-dd8e8b9fc8a1', 'be127d76-fad1-536d-9e84-2324918eef7d', 'Ring 2', (timestamp '2025-07-12 10:00' at time zone 'America/Edmonton'), 15),
  ('c0e2be0a-01a5-50d3-a8cd-ab0b907655d7', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', 'round_robin', 'Round 2', 0, null, 'be127d76-fad1-536d-9e84-2324918eef7d', '7c5e226c-0fc5-5a36-9625-7f7c4c5da470', 'Ring 2', (timestamp '2025-07-12 10:17' at time zone 'America/Edmonton'), 15),
  ('1a383b27-bb63-59e2-8ed5-da3f85418786', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', 'round_robin', 'Round 3', 0, null, '7c5e226c-0fc5-5a36-9625-7f7c4c5da470', '4ce6cae0-034e-5ad9-afed-dd8e8b9fc8a1', 'Ring 2', (timestamp '2025-07-12 10:34' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '5ae9673b-24a0-5869-be3a-c4c8190bb84c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = 'c0e2be0a-01a5-50d3-a8cd-ab0b907655d7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '1a383b27-bb63-59e2-8ed5-da3f85418786' and m.queue_state <> 'final';
select public.finish_competition('2bb8f76c-1d36-535d-ba18-01d09f1a2673', 'tournament_structure') where exists (select 1 from public.competitions where id = '2bb8f76c-1d36-535d-ba18-01d09f1a2673' and status <> 'finished');
-- Male 3v3: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('bf8f0884-8bb4-537f-9f3e-18b9d8928e95', 'e144e88f-559c-5674-af99-601f06dbc989', 'round_robin', 'Round 1', 0, null, 'd599fcbc-bb03-5a05-9b27-09dc3b095433', '1b49c8ba-1151-5657-82a1-a068281aac4e', 'Ring 3', (timestamp '2025-07-12 10:00' at time zone 'America/Edmonton'), 15),
  ('48b5baf3-8536-5618-8cb0-d64dede0adbe', 'e144e88f-559c-5674-af99-601f06dbc989', 'round_robin', 'Round 2', 0, null, '1b49c8ba-1151-5657-82a1-a068281aac4e', '8a284e47-d186-5334-a0ce-d2751cf2c541', 'Ring 3', (timestamp '2025-07-12 10:17' at time zone 'America/Edmonton'), 15),
  ('654e8ef6-da85-524c-a0e0-2e062bd19738', 'e144e88f-559c-5674-af99-601f06dbc989', 'round_robin', 'Round 3', 0, null, '8a284e47-d186-5334-a0ce-d2751cf2c541', 'd599fcbc-bb03-5a05-9b27-09dc3b095433', 'Ring 3', (timestamp '2025-07-12 10:34' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = 'bf8f0884-8bb4-537f-9f3e-18b9d8928e95' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '48b5baf3-8536-5618-8cb0-d64dede0adbe' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '654e8ef6-da85-524c-a0e0-2e062bd19738' and m.queue_state <> 'final';
select public.finish_competition('e144e88f-559c-5674-af99-601f06dbc989', 'tournament_structure') where exists (select 1 from public.competitions where id = 'e144e88f-559c-5674-af99-601f06dbc989' and status <> 'finished');
-- Male Longsword: elimination, 10 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('53fb0e17-9a69-5bcd-a9db-383c59907a99', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Round of 16', 1, null, 'd8cce533-14e7-59b4-b11e-060458d591e6', 'a35a574d-e0c7-57ba-9b53-d0f32462fe70', 'Ring 1', (timestamp '2025-07-12 10:17' at time zone 'America/Edmonton'), 8),
  ('711b887b-e3dc-53ad-8c52-03884e4f7419', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Round of 16', 5, null, 'e7b98b4b-081f-5fc1-a0fb-4010840d94c7', '490f4d99-210c-5ab5-a40f-7708848dd074', 'Ring 1', (timestamp '2025-07-12 10:27' at time zone 'America/Edmonton'), 8),
  ('f15216d2-831c-5bef-99a1-a9c786f31cfd', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Quarterfinal', 0, null, '40a36a64-4df6-51df-a125-538193367ebf', null, 'Ring 1', (timestamp '2025-07-12 10:37' at time zone 'America/Edmonton'), 8),
  ('34736528-cc7e-5a38-a82d-d69c5866d844', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Quarterfinal', 1, null, 'db0799f2-671c-57ed-b872-d17b5c6bb995', '57ecf260-4ea0-573b-89d7-032e92044d25', 'Ring 1', (timestamp '2025-07-12 10:47' at time zone 'America/Edmonton'), 8),
  ('fb38d95a-0352-59f1-ad95-3a2d5a6fc10b', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Quarterfinal', 2, null, 'f2929760-a9c5-5475-9b76-27178ea249dc', null, 'Ring 1', (timestamp '2025-07-12 10:57' at time zone 'America/Edmonton'), 8),
  ('756d39f8-1759-5beb-98b4-7ca42ca6fb65', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Quarterfinal', 3, null, '71692912-ffb6-5e45-88ec-3002d8629235', '874f992d-861a-5f33-bd23-227e393481ba', 'Ring 1', (timestamp '2025-07-12 11:07' at time zone 'America/Edmonton'), 8),
  ('bf124c65-39f4-5705-8d35-19401265c550', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 1', (timestamp '2025-07-12 11:17' at time zone 'America/Edmonton'), 8),
  ('7fa83bbc-9d7f-5aa3-8c5d-9a6003b269da', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 1', (timestamp '2025-07-12 11:27' at time zone 'America/Edmonton'), 8),
  ('4dc02718-cd6b-5d64-88f0-609fd7f40599', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'final', 'Final', 0, null, null, null, 'Ring 1', (timestamp '2025-07-12 11:37' at time zone 'America/Edmonton'), 8),
  ('f99dc139-ca5d-50f1-b0ab-3705a2e481d8', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'third_place', 'Third place', 0, null, null, null, 'Ring 1', (timestamp '2025-07-12 11:47' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('53fb0e17-9a69-5bcd-a9db-383c59907a99'::uuid, 'f15216d2-831c-5bef-99a1-a9c786f31cfd'::uuid, 'b'),
  ('711b887b-e3dc-53ad-8c52-03884e4f7419'::uuid, 'fb38d95a-0352-59f1-ad95-3a2d5a6fc10b'::uuid, 'b'),
  ('f15216d2-831c-5bef-99a1-a9c786f31cfd'::uuid, 'bf124c65-39f4-5705-8d35-19401265c550'::uuid, 'a'),
  ('34736528-cc7e-5a38-a82d-d69c5866d844'::uuid, 'bf124c65-39f4-5705-8d35-19401265c550'::uuid, 'b'),
  ('fb38d95a-0352-59f1-ad95-3a2d5a6fc10b'::uuid, '7fa83bbc-9d7f-5aa3-8c5d-9a6003b269da'::uuid, 'a'),
  ('756d39f8-1759-5beb-98b4-7ca42ca6fb65'::uuid, '7fa83bbc-9d7f-5aa3-8c5d-9a6003b269da'::uuid, 'b'),
  ('bf124c65-39f4-5705-8d35-19401265c550'::uuid, '4dc02718-cd6b-5d64-88f0-609fd7f40599'::uuid, 'a'),
  ('7fa83bbc-9d7f-5aa3-8c5d-9a6003b269da'::uuid, '4dc02718-cd6b-5d64-88f0-609fd7f40599'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[3,0],"b":[1,4]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '53fb0e17-9a69-5bcd-a9db-383c59907a99' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '711b887b-e3dc-53ad-8c52-03884e4f7419' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[0,3]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'f15216d2-831c-5bef-99a1-a9c786f31cfd' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[2,0,0],"b":[0,2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '34736528-cc7e-5a38-a82d-d69c5866d844' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[1,0,1],"b":[0,0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'fb38d95a-0352-59f1-ad95-3a2d5a6fc10b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 10, 8, '{"kind":"duel","rounds":{"a":[1,2,2,0,2,3],"b":[0,4,2,0,2,0]},"totals":{"a":10,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '756d39f8-1759-5beb-98b4-7ca42ca6fb65' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[4,1],"b":[1,0]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'bf124c65-39f4-5705-8d35-19401265c550' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 6, '{"kind":"duel","rounds":{"a":[1,1,1,0,1],"b":[0,2,0,2,2]},"totals":{"a":4,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '7fa83bbc-9d7f-5aa3-8c5d-9a6003b269da' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '4dc02718-cd6b-5d64-88f0-609fd7f40599' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[0,2],"b":[2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'f99dc139-ca5d-50f1-b0ab-3705a2e481d8' and m.queue_state <> 'final';
select public.finish_competition('265db25b-1cdf-5b8c-8148-269fb9780ee5', 'tournament_structure') where exists (select 1 from public.competitions where id = '265db25b-1cdf-5b8c-8148-269fb9780ee5' and status <> 'finished');
-- Female Longsword: elimination, 9 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('a6f51696-9df1-5003-9513-b572cd6f879e', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Round of 16', 1, null, 'c9b2d124-d7e7-55e8-99c6-d61c0608c03f', 'ec22450a-6814-52d3-acce-f957eb74f41a', 'Ring 2', (timestamp '2025-07-12 10:51' at time zone 'America/Edmonton'), 8),
  ('8ca78049-c53d-509c-9efd-03e484bb2014', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Quarterfinal', 0, null, '452f7697-8a16-544e-a445-86bef396c092', null, 'Ring 2', (timestamp '2025-07-12 11:01' at time zone 'America/Edmonton'), 8),
  ('f510c8e0-4c86-5af6-84b2-58fc6c9004c5', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Quarterfinal', 1, null, '2b45b4e4-0ad4-52f8-91a2-f8b4d338eb7e', '8c84b99b-8dff-5633-afb4-ad5dd98d9024', 'Ring 2', (timestamp '2025-07-12 11:11' at time zone 'America/Edmonton'), 8),
  ('ecd041a4-042e-5150-8209-b86ce374fcb4', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Quarterfinal', 2, null, 'aa482bd1-4c7a-565c-8f2d-07ca849af32f', 'fc5ef8ec-62cf-56ea-83b6-5933e398fd97', 'Ring 2', (timestamp '2025-07-12 11:21' at time zone 'America/Edmonton'), 8),
  ('6ee4e075-880a-576e-9b0e-a4dc3750c274', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Quarterfinal', 3, null, 'f8efd56c-0b80-533e-b331-ccc793fd94ca', '145e8ddc-fa5f-5b52-b342-db15a8e65468', 'Ring 2', (timestamp '2025-07-12 11:31' at time zone 'America/Edmonton'), 8),
  ('1483d435-11ee-52e3-9c13-4b54bbc4521f', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2025-07-12 11:41' at time zone 'America/Edmonton'), 8),
  ('32bfeb87-56d4-5a27-a50c-d996e5c3d847', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2025-07-12 11:51' at time zone 'America/Edmonton'), 8),
  ('5dbf169f-6ff1-5062-960b-5a8a34b52fb9', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2025-07-12 12:01' at time zone 'America/Edmonton'), 8),
  ('f5d4807b-2fff-5a81-a1e4-1c371ff35375', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2025-07-12 12:11' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('a6f51696-9df1-5003-9513-b572cd6f879e'::uuid, '8ca78049-c53d-509c-9efd-03e484bb2014'::uuid, 'b'),
  ('8ca78049-c53d-509c-9efd-03e484bb2014'::uuid, '1483d435-11ee-52e3-9c13-4b54bbc4521f'::uuid, 'a'),
  ('f510c8e0-4c86-5af6-84b2-58fc6c9004c5'::uuid, '1483d435-11ee-52e3-9c13-4b54bbc4521f'::uuid, 'b'),
  ('ecd041a4-042e-5150-8209-b86ce374fcb4'::uuid, '32bfeb87-56d4-5a27-a50c-d996e5c3d847'::uuid, 'a'),
  ('6ee4e075-880a-576e-9b0e-a4dc3750c274'::uuid, '32bfeb87-56d4-5a27-a50c-d996e5c3d847'::uuid, 'b'),
  ('1483d435-11ee-52e3-9c13-4b54bbc4521f'::uuid, '5dbf169f-6ff1-5062-960b-5a8a34b52fb9'::uuid, 'a'),
  ('32bfeb87-56d4-5a27-a50c-d996e5c3d847'::uuid, '5dbf169f-6ff1-5062-960b-5a8a34b52fb9'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[1,4],"b":[1,0]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'a6f51696-9df1-5003-9513-b572cd6f879e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 8, '{"kind":"duel","rounds":{"a":[2,1,2],"b":[2,2,4]},"totals":{"a":5,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '8ca78049-c53d-509c-9efd-03e484bb2014' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 6, '{"kind":"duel","rounds":{"a":[0,2,1,3,3],"b":[2,0,1,3,0]},"totals":{"a":9,"b":6}}'::jsonb, m.version) from public.matches m where m.id = 'f510c8e0-4c86-5af6-84b2-58fc6c9004c5' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1],"b":[3,0]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'ecd041a4-042e-5150-8209-b86ce374fcb4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[1,2],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '6ee4e075-880a-576e-9b0e-a4dc3750c274' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[1,4],"b":[0,1]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '1483d435-11ee-52e3-9c13-4b54bbc4521f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,3]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '32bfeb87-56d4-5a27-a50c-d996e5c3d847' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,2]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '5dbf169f-6ff1-5062-960b-5a8a34b52fb9' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[2,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'f5d4807b-2fff-5a81-a1e4-1c371ff35375' and m.queue_state <> 'final';
select public.finish_competition('9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'tournament_structure') where exists (select 1 from public.competitions where id = '9d6543ce-640f-5176-9c95-cd4d6e78bdee' and status <> 'finished');
-- Male Sword & Shield: round_robin, 6 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('bc685b54-b75a-5901-ad23-4bcc25c1be3d', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 1', 0, null, '7a1baf4b-ad9a-5db3-b7de-8f257f2020cd', '9b302e9c-f8fe-5c5f-9443-4c393e0ab48a', 'Ring 3', (timestamp '2025-07-12 10:51' at time zone 'America/Edmonton'), 8),
  ('d9f0e717-edfb-59b9-b2c7-7c784058b650', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 1', 1, null, 'bf4d6806-d78d-507c-815d-7fcb8d44f6d8', '28ffc28d-bc5a-5c2c-8728-4072014b571d', 'Ring 3', (timestamp '2025-07-12 11:01' at time zone 'America/Edmonton'), 8),
  ('3567c6a7-6005-58ca-913a-e0eb9b261bf8', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 1', 2, null, '45f4b8ea-d68f-5ce1-a658-d66cedae6e3f', '2bb73eff-b109-5bc5-bee5-7b5b02cbbe98', 'Ring 3', (timestamp '2025-07-12 11:11' at time zone 'America/Edmonton'), 8),
  ('abd2a24a-7b42-5a05-a322-2ffbc499f158', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 2', 0, null, '28ffc28d-bc5a-5c2c-8728-4072014b571d', '7a1baf4b-ad9a-5db3-b7de-8f257f2020cd', 'Ring 3', (timestamp '2025-07-12 11:21' at time zone 'America/Edmonton'), 8),
  ('0cbf000c-9d0b-545a-96ee-debd6bba3922', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 2', 1, null, '9b302e9c-f8fe-5c5f-9443-4c393e0ab48a', '2bb73eff-b109-5bc5-bee5-7b5b02cbbe98', 'Ring 3', (timestamp '2025-07-12 11:31' at time zone 'America/Edmonton'), 8),
  ('7c4adc09-a895-5881-a3b6-1cc0fb22d358', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 2', 2, null, 'bf4d6806-d78d-507c-815d-7fcb8d44f6d8', '45f4b8ea-d68f-5ce1-a658-d66cedae6e3f', 'Ring 3', (timestamp '2025-07-12 11:41' at time zone 'America/Edmonton'), 8),
  ('a3a7814b-cdfb-5555-a76c-504f4fde0e19', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 3', 0, null, '7a1baf4b-ad9a-5db3-b7de-8f257f2020cd', '2bb73eff-b109-5bc5-bee5-7b5b02cbbe98', 'Ring 3', (timestamp '2025-07-12 11:51' at time zone 'America/Edmonton'), 8),
  ('8aa2010e-663c-534a-8749-91a27de5ec49', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 3', 1, null, '28ffc28d-bc5a-5c2c-8728-4072014b571d', '45f4b8ea-d68f-5ce1-a658-d66cedae6e3f', 'Ring 3', (timestamp '2025-07-12 12:01' at time zone 'America/Edmonton'), 8),
  ('eb1c1496-6726-5ea4-b1da-590d4ac27ba3', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 3', 2, null, '9b302e9c-f8fe-5c5f-9443-4c393e0ab48a', 'bf4d6806-d78d-507c-815d-7fcb8d44f6d8', 'Ring 3', (timestamp '2025-07-12 12:11' at time zone 'America/Edmonton'), 8),
  ('40f856e4-a749-5c93-8cce-f493bbb318bd', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 4', 0, null, '45f4b8ea-d68f-5ce1-a658-d66cedae6e3f', '7a1baf4b-ad9a-5db3-b7de-8f257f2020cd', 'Ring 3', (timestamp '2025-07-12 12:21' at time zone 'America/Edmonton'), 8),
  ('f85480ca-0814-55a1-aee9-b44e3441623a', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 4', 1, null, '2bb73eff-b109-5bc5-bee5-7b5b02cbbe98', 'bf4d6806-d78d-507c-815d-7fcb8d44f6d8', 'Ring 3', (timestamp '2025-07-12 12:31' at time zone 'America/Edmonton'), 8),
  ('83e93d84-1c5d-536d-bffd-e461a2d93598', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 4', 2, null, '28ffc28d-bc5a-5c2c-8728-4072014b571d', '9b302e9c-f8fe-5c5f-9443-4c393e0ab48a', 'Ring 3', (timestamp '2025-07-12 12:41' at time zone 'America/Edmonton'), 8),
  ('70658539-fadf-5b8a-b9d9-157e8fc22e1b', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 5', 0, null, '7a1baf4b-ad9a-5db3-b7de-8f257f2020cd', 'bf4d6806-d78d-507c-815d-7fcb8d44f6d8', 'Ring 3', (timestamp '2025-07-12 12:51' at time zone 'America/Edmonton'), 8),
  ('0563e6e2-ca8f-54f1-a185-3cef05603304', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 5', 1, null, '45f4b8ea-d68f-5ce1-a658-d66cedae6e3f', '9b302e9c-f8fe-5c5f-9443-4c393e0ab48a', 'Ring 3', (timestamp '2025-07-12 13:01' at time zone 'America/Edmonton'), 8),
  ('182eb575-f5a0-5bcd-ac0f-162af038038e', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'round_robin', 'Round 5', 2, null, '2bb73eff-b109-5bc5-bee5-7b5b02cbbe98', '28ffc28d-bc5a-5c2c-8728-4072014b571d', 'Ring 3', (timestamp '2025-07-12 13:11' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,2],"b":[1,1]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'bc685b54-b75a-5901-ad23-4bcc25c1be3d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[2,0],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'd9f0e717-edfb-59b9-b2c7-7c784058b650' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[3,1],"b":[0,2]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '3567c6a7-6005-58ca-913a-e0eb9b261bf8' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 4, '{"kind":"duel","rounds":{"a":[1,0],"b":[3,1]},"totals":{"a":1,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'abd2a24a-7b42-5a05-a322-2ffbc499f158' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 7, '{"kind":"duel","rounds":{"a":[1,1,1],"b":[1,1,5]},"totals":{"a":3,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '0cbf000c-9d0b-545a-96ee-debd6bba3922' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 8, 4, '{"kind":"duel","rounds":{"a":[1,2,5],"b":[0,2,2]},"totals":{"a":8,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '7c4adc09-a895-5881-a3b6-1cc0fb22d358' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 12, 10, '{"kind":"duel","rounds":{"a":[2,1,3,1,0,2,1,2],"b":[1,1,4,1,0,2,1,0]},"totals":{"a":12,"b":10}}'::jsonb, m.version) from public.matches m where m.id = 'a3a7814b-cdfb-5555-a76c-504f4fde0e19' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 8, 6, '{"kind":"duel","rounds":{"a":[2,2,1,3],"b":[2,1,1,2]},"totals":{"a":8,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '8aa2010e-663c-534a-8749-91a27de5ec49' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'eb1c1496-6726-5ea4-b1da-590d4ac27ba3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,1]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '40f856e4-a749-5c93-8cce-f493bbb318bd' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1],"b":[3,0]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'f85480ca-0814-55a1-aee9-b44e3441623a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 7, '{"kind":"duel","rounds":{"a":[4,0,0],"b":[3,1,3]},"totals":{"a":4,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '83e93d84-1c5d-536d-bffd-e461a2d93598' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 10, '{"kind":"duel","rounds":{"a":[0,2],"b":[5,5]},"totals":{"a":2,"b":10}}'::jsonb, m.version) from public.matches m where m.id = '70658539-fadf-5b8a-b9d9-157e8fc22e1b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[0,0,1,3],"b":[0,0,0,2]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '0563e6e2-ca8f-54f1-a185-3cef05603304' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,1]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '182eb575-f5a0-5bcd-ac0f-162af038038e' and m.queue_state <> 'final';
select public.finish_competition('9a0bf38c-2270-535f-8056-cfb8e618495e', 'tournament_structure') where exists (select 1 from public.competitions where id = '9a0bf38c-2270-535f-8056-cfb8e618495e' and status <> 'finished');
-- Male Polearm: round_robin, 4 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('ba3e30ff-3b3e-53d7-a6b1-70a9e0d8d9f7', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'round_robin', 'Round 1', 0, null, 'a6e1a679-362d-509a-9cd6-9bc0383a2233', '7823b820-fb0d-54a7-a14b-b0b6eec56a54', 'Ring 1', (timestamp '2025-07-12 11:57' at time zone 'America/Edmonton'), 8),
  ('a3426a54-e5b8-5dde-af06-7f707effe035', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'round_robin', 'Round 1', 1, null, '062bf0f1-0a6f-5626-a183-4cfc4fc43b25', '3fc90651-5704-5fef-8b4e-1e4acedf9cfe', 'Ring 1', (timestamp '2025-07-12 12:07' at time zone 'America/Edmonton'), 8),
  ('a1994d54-35fd-5bc7-b66c-e40817531e1f', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'round_robin', 'Round 2', 0, null, '3fc90651-5704-5fef-8b4e-1e4acedf9cfe', 'a6e1a679-362d-509a-9cd6-9bc0383a2233', 'Ring 1', (timestamp '2025-07-12 12:17' at time zone 'America/Edmonton'), 8),
  ('5bb3ccf9-7b33-5906-b5a8-93a49647da00', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'round_robin', 'Round 2', 1, null, '7823b820-fb0d-54a7-a14b-b0b6eec56a54', '062bf0f1-0a6f-5626-a183-4cfc4fc43b25', 'Ring 1', (timestamp '2025-07-12 12:27' at time zone 'America/Edmonton'), 8),
  ('67f32fb2-ff87-5fb4-8aca-5ca72a698ed1', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'round_robin', 'Round 3', 0, null, 'a6e1a679-362d-509a-9cd6-9bc0383a2233', '062bf0f1-0a6f-5626-a183-4cfc4fc43b25', 'Ring 1', (timestamp '2025-07-12 12:37' at time zone 'America/Edmonton'), 8),
  ('490404f0-b6d6-5f02-914d-9982ffdbe3b5', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'round_robin', 'Round 3', 1, null, '3fc90651-5704-5fef-8b4e-1e4acedf9cfe', '7823b820-fb0d-54a7-a14b-b0b6eec56a54', 'Ring 1', (timestamp '2025-07-12 12:47' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,1]},"totals":{"a":0,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'ba3e30ff-3b3e-53d7-a6b1-70a9e0d8d9f7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1],"b":[0,3]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'a3426a54-e5b8-5dde-af06-7f707effe035' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 3, '{"kind":"duel","rounds":{"a":[1,1,1,1,2],"b":[1,1,0,1,0]},"totals":{"a":6,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'a1994d54-35fd-5bc7-b66c-e40817531e1f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 0, '{"kind":"duel","rounds":{"a":[3,2],"b":[0,0]},"totals":{"a":5,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '5bb3ccf9-7b33-5906-b5a8-93a49647da00' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 5, '{"kind":"duel","rounds":{"a":[3,0,1,2,3],"b":[0,4,1,0,0]},"totals":{"a":9,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '67f32fb2-ff87-5fb4-8aca-5ca72a698ed1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 6, 10, '{"kind":"duel","rounds":{"a":[2,1,0,3,0],"b":[0,3,1,3,3]},"totals":{"a":6,"b":10}}'::jsonb, m.version) from public.matches m where m.id = '490404f0-b6d6-5f02-914d-9982ffdbe3b5' and m.queue_state <> 'final';
select public.finish_competition('b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'tournament_structure') where exists (select 1 from public.competitions where id = 'b18fcfc2-e16d-561d-b2da-7a85163de3b6' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '06e40c1f-4d12-5f72-b05a-cd065d288033', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '2bb8f76c-1d36-535d-ba18-01d09f1a2673', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'e144e88f-559c-5674-af99-601f06dbc989', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '265db25b-1cdf-5b8c-8148-269fb9780ee5', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '9d6543ce-640f-5176-9c95-cd4d6e78bdee', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '9a0bf38c-2270-535f-8056-cfb8e618495e', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'b18fcfc2-e16d-561d-b2da-7a85163de3b6', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce' and m.queue_state = 'final';
update public.audit_log set at = (date '2025-07-13' + time '21:00') at time zone 'America/Edmonton' where event_id = '96fb5e0d-6c87-54bf-bc06-1f56c39d00ce';
commit;
