-- NACL-test fictional dataset: Grande Prairie Northern Clash-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('48c14d82-9d37-5f43-a309-89383d67b39e', 'grande-prairie-northern-clash-test', 'Grande Prairie Northern Clash-test', 'A far-north Alberta clash, small but keen.', 'tournament', 'published', 'Northern Lights Hall-test', 'Grande Prairie', 'AB', 'CA', 'America/Edmonton', 0, date '2026-07-11', date '2026-07-12', null, 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', '48c14d82-9d37-5f43-a309-89383d67b39e', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('48c14d82-9d37-5f43-a309-89383d67b39e', '6acd0719-46c7-540c-9290-1e09e1af0070');
select public.set_event_organization('48c14d82-9d37-5f43-a309-89383d67b39e', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', '48c14d82-9d37-5f43-a309-89383d67b39e', 'Male 3v3', '3v3', 'men', 'Source', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('289f4aeb-1d3e-5e68-9cf6-45c0da240b65', '48c14d82-9d37-5f43-a309-89383d67b39e', 'Male Longsword', 'longsword', 'men', 'Source', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 20),
  ('a01f1330-2281-5d96-86e7-88240493a821', '48c14d82-9d37-5f43-a309-89383d67b39e', 'Female Longsword', 'longsword', 'women', 'Source', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 30),
  ('6c980b90-8fa8-5c51-8bea-78c8da264236', '48c14d82-9d37-5f43-a309-89383d67b39e', 'Male Polearm', 'polearm', 'men', 'Source', 'Buhurt International: Duels rules V.26.4', 'round_robin', 'running', null, 40)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('c3b75429-a065-5ec8-b4ac-22b239e68cbb', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('dbc2c565-b035-5064-a891-8ad94e724511', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', '9e6caec8-33a2-5b5c-97e8-89f86facf0ea', null, 'checked_in'),
  ('34f5fad9-33d8-506e-9018-0e2ee38ae1ee', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('f73a7c07-83b3-5078-b091-01c11f6a86ae', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, 'dc986b96-be3f-5c26-914b-c1162aa0eb4b', 'checked_in'),
  ('d197e74f-e3f2-5c8e-89d0-00441eb5407b', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, '7ba3fceb-e85e-5ed0-84a0-76915d6c6f83', 'checked_in'),
  ('56e14bcf-9f0a-5a18-9b72-f909db9da8d6', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, '49c189e3-a1f5-5342-b03f-965e69b3406c', 'checked_in'),
  ('7ce0be92-faab-59c5-a6f5-6105c14f1e34', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, '88383cff-3cd0-5e0a-91bd-8c375e39c4b5', 'checked_in'),
  ('d7e10efc-eb7d-5db2-9df3-ddf94c8cd5dd', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, '97d5d06f-fcbe-5363-875c-abb48e8c9cbc', 'checked_in'),
  ('9ad7349c-0d98-5e51-90b9-a87e1714713d', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, 'd3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd', 'checked_in'),
  ('27f86767-4647-5018-8386-8232df7ff654', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, 'df7d277f-b7dc-5d74-85f9-0a5e44bffad5', 'checked_in'),
  ('3b3fe3ef-e9c9-54c9-8105-613e018952ff', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, 'c2114868-da44-5a82-a1d3-f91f5326285f', 'checked_in'),
  ('77b3a40d-5832-5568-944f-e41f188ffb06', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, 'f8297a85-7282-5c93-a25a-7ebfd34d0160', 'checked_in'),
  ('062b363d-fbcb-5af2-b48b-0d4375d440bf', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', null, 'dc6ad18c-6ea3-5243-b794-7098006f2790', 'checked_in'),
  ('5c37d963-d52f-5874-aa0d-27890e4291e2', 'a01f1330-2281-5d96-86e7-88240493a821', null, 'f5bf9cb2-e86b-5c61-bcc5-2d3febce1a61', 'checked_in'),
  ('2f1736b9-5729-5d64-bc5d-edfd95914915', 'a01f1330-2281-5d96-86e7-88240493a821', null, '7b2a7b7d-ddd2-595d-9269-7efa0dbacd1a', 'checked_in'),
  ('61f447f4-c0d6-57de-932c-f5dd8eaf5a6a', 'a01f1330-2281-5d96-86e7-88240493a821', null, 'd1b9ab79-147f-5ab9-9356-0ebb9f9bcc40', 'checked_in'),
  ('38554678-5179-5cec-bc71-f5d3c25e9c79', 'a01f1330-2281-5d96-86e7-88240493a821', null, 'f263eeb9-8098-5d5a-8b30-36c01db0900d', 'checked_in'),
  ('0cec645a-ad62-5f9c-9b58-65c6c0fc74ad', 'a01f1330-2281-5d96-86e7-88240493a821', null, '9b130d30-471b-5ccf-9192-7e0c04af836e', 'checked_in'),
  ('826ac709-faa5-5ec0-b50f-2e59152e7f3f', '6c980b90-8fa8-5c51-8bea-78c8da264236', null, 'e0e182fe-bce4-5347-ac8c-ac85f8f10fd5', 'checked_in'),
  ('08b4ae1e-26da-5366-ab14-15b22b57e099', '6c980b90-8fa8-5c51-8bea-78c8da264236', null, '8120e2f4-1510-5cfd-a077-7320c47a52a9', 'checked_in'),
  ('87fb0716-0e1e-5c3e-a60a-20373fd60483', '6c980b90-8fa8-5c51-8bea-78c8da264236', null, '7f46df0f-b1c8-527e-aff1-d8ababc108d8', 'checked_in'),
  ('0489beaf-14be-508e-a3ca-547117c3ccba', '6c980b90-8fa8-5c51-8bea-78c8da264236', null, '334bbc46-99e7-573f-8be9-5c304f12e660', 'checked_in'),
  ('7b452f55-f6f3-52c5-a81a-60c3f8ffd1ea', '6c980b90-8fa8-5c51-8bea-78c8da264236', null, '98146ed7-d388-5e3c-822d-f8d5285044bf', 'checked_in'),
  ('35e93bdd-65c0-5ee1-9192-bbef0936b771', '6c980b90-8fa8-5c51-8bea-78c8da264236', null, 'b9551194-d28a-50e3-9bfc-36c446fa8f54', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('c3b75429-a065-5ec8-b4ac-22b239e68cbb', '[{"fighter_id":"97d5d06f-fcbe-5363-875c-abb48e8c9cbc","role":"fighter"},{"fighter_id":"72ab5bcb-c669-59a6-9865-86a0a151bc59","role":"fighter"},{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1' and status <> 'finished');
select public.set_entry_roster('dbc2c565-b035-5064-a891-8ad94e724511', '[{"fighter_id":"8120e2f4-1510-5cfd-a077-7320c47a52a9","role":"fighter"},{"fighter_id":"a6d7fbe4-0392-5679-9e83-3a4693aa452d","role":"fighter"},{"fighter_id":"d3fcbcf8-0c56-5b9c-aba4-bcd0ff57dffd","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1' and status <> 'finished');
select public.set_entry_roster('34f5fad9-33d8-506e-9018-0e2ee38ae1ee', '[{"fighter_id":"0e28a5bf-3ca5-50ce-bf11-142105c58181","role":"fighter"},{"fighter_id":"c2114868-da44-5a82-a1d3-f91f5326285f","role":"fighter"},{"fighter_id":"dc6ad18c-6ea3-5243-b794-7098006f2790","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1' and status <> 'finished');
-- Male 3v3: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('7ddd4a76-cf52-5bbb-b2aa-217a37186b3e', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', 'round_robin', 'Round 1', 0, null, 'dbc2c565-b035-5064-a891-8ad94e724511', 'c3b75429-a065-5ec8-b4ac-22b239e68cbb', 'Ring 1', (timestamp '2026-07-11 10:00' at time zone 'America/Edmonton'), 15),
  ('24138548-4393-5a25-8125-a0b4e91449c6', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', 'round_robin', 'Round 2', 0, null, 'c3b75429-a065-5ec8-b4ac-22b239e68cbb', '34f5fad9-33d8-506e-9018-0e2ee38ae1ee', 'Ring 1', (timestamp '2026-07-11 10:17' at time zone 'America/Edmonton'), 15),
  ('0f93c46b-a578-599e-b9b5-e00e13544895', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', 'round_robin', 'Round 3', 0, null, '34f5fad9-33d8-506e-9018-0e2ee38ae1ee', 'dbc2c565-b035-5064-a891-8ad94e724511', 'Ring 1', (timestamp '2026-07-11 10:34' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '7ddd4a76-cf52-5bbb-b2aa-217a37186b3e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '24138548-4393-5a25-8125-a0b4e91449c6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '0f93c46b-a578-599e-b9b5-e00e13544895' and m.queue_state <> 'final';
select public.finish_competition('15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', 'tournament_structure') where exists (select 1 from public.competitions where id = '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1' and status <> 'finished');
-- Male Longsword: elimination, 10 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('5bda08e5-5480-56b9-9ced-c667703b146c', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Round of 16', 1, null, '7ce0be92-faab-59c5-a6f5-6105c14f1e34', '56e14bcf-9f0a-5a18-9b72-f909db9da8d6', 'Ring 2', (timestamp '2026-07-11 10:00' at time zone 'America/Edmonton'), 8),
  ('c2908dcb-16dd-5cd8-b2fa-95b9d5fb0ae7', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Round of 16', 5, null, '062b363d-fbcb-5af2-b48b-0d4375d440bf', 'd7e10efc-eb7d-5db2-9df3-ddf94c8cd5dd', 'Ring 2', (timestamp '2026-07-11 10:10' at time zone 'America/Edmonton'), 8),
  ('ee0a2cb2-aa7c-5f36-ae93-2488fba683ce', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Quarterfinal', 0, null, '77b3a40d-5832-5568-944f-e41f188ffb06', null, 'Ring 2', (timestamp '2026-07-11 10:20' at time zone 'America/Edmonton'), 8),
  ('8eed6f9f-e433-5df1-8b1f-0214b74795b0', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Quarterfinal', 1, null, '9ad7349c-0d98-5e51-90b9-a87e1714713d', '27f86767-4647-5018-8386-8232df7ff654', 'Ring 2', (timestamp '2026-07-11 10:30' at time zone 'America/Edmonton'), 8),
  ('207f2af0-501e-5148-a594-18ed38efcd49', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Quarterfinal', 2, null, '3b3fe3ef-e9c9-54c9-8105-613e018952ff', null, 'Ring 2', (timestamp '2026-07-11 10:40' at time zone 'America/Edmonton'), 8),
  ('c34ffaf9-0171-5b9f-84a1-8daff865d82f', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Quarterfinal', 3, null, 'd197e74f-e3f2-5c8e-89d0-00441eb5407b', 'f73a7c07-83b3-5078-b091-01c11f6a86ae', 'Ring 2', (timestamp '2026-07-11 10:50' at time zone 'America/Edmonton'), 8),
  ('e3cfec93-845d-5e7f-9870-540ee542dc9a', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2026-07-11 11:00' at time zone 'America/Edmonton'), 8),
  ('0cdb1d61-7a4c-5066-8e9d-fefba1de27f4', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2026-07-11 11:10' at time zone 'America/Edmonton'), 8),
  ('72c1a599-36f3-5190-81bd-00e6efb308f9', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2026-07-11 11:20' at time zone 'America/Edmonton'), 8),
  ('a883cedd-1589-5c9b-9789-32fc4ed93061', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2026-07-11 11:30' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('5bda08e5-5480-56b9-9ced-c667703b146c'::uuid, 'ee0a2cb2-aa7c-5f36-ae93-2488fba683ce'::uuid, 'b'),
  ('c2908dcb-16dd-5cd8-b2fa-95b9d5fb0ae7'::uuid, '207f2af0-501e-5148-a594-18ed38efcd49'::uuid, 'b'),
  ('ee0a2cb2-aa7c-5f36-ae93-2488fba683ce'::uuid, 'e3cfec93-845d-5e7f-9870-540ee542dc9a'::uuid, 'a'),
  ('8eed6f9f-e433-5df1-8b1f-0214b74795b0'::uuid, 'e3cfec93-845d-5e7f-9870-540ee542dc9a'::uuid, 'b'),
  ('207f2af0-501e-5148-a594-18ed38efcd49'::uuid, '0cdb1d61-7a4c-5066-8e9d-fefba1de27f4'::uuid, 'a'),
  ('c34ffaf9-0171-5b9f-84a1-8daff865d82f'::uuid, '0cdb1d61-7a4c-5066-8e9d-fefba1de27f4'::uuid, 'b'),
  ('e3cfec93-845d-5e7f-9870-540ee542dc9a'::uuid, '72c1a599-36f3-5190-81bd-00e6efb308f9'::uuid, 'a'),
  ('0cdb1d61-7a4c-5066-8e9d-fefba1de27f4'::uuid, '72c1a599-36f3-5190-81bd-00e6efb308f9'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 6, '{"kind":"duel","rounds":{"a":[0,0],"b":[5,1]},"totals":{"a":0,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '5bda08e5-5480-56b9-9ced-c667703b146c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 10, '{"kind":"duel","rounds":{"a":[2,0],"b":[4,6]},"totals":{"a":2,"b":10}}'::jsonb, m.version) from public.matches m where m.id = 'c2908dcb-16dd-5cd8-b2fa-95b9d5fb0ae7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[3,1]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ee0a2cb2-aa7c-5f36-ae93-2488fba683ce' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 6, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,2]},"totals":{"a":0,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '8eed6f9f-e433-5df1-8b1f-0214b74795b0' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 8, '{"kind":"duel","rounds":{"a":[1,0],"b":[4,4]},"totals":{"a":1,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '207f2af0-501e-5148-a594-18ed38efcd49' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[0,2],"b":[3,2]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'c34ffaf9-0171-5b9f-84a1-8daff865d82f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,3]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'e3cfec93-845d-5e7f-9870-540ee542dc9a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[3,2],"b":[2,0]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '0cdb1d61-7a4c-5066-8e9d-fefba1de27f4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[0,3],"b":[1,0]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '72c1a599-36f3-5190-81bd-00e6efb308f9' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[0,2],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'a883cedd-1589-5c9b-9789-32fc4ed93061' and m.queue_state <> 'final';
select public.finish_competition('289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'tournament_structure') where exists (select 1 from public.competitions where id = '289f4aeb-1d3e-5e68-9cf6-45c0da240b65' and status <> 'finished');
-- Female Longsword: round_robin, 5 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('ff9f0f99-8a8e-5602-abef-7b57e263cacb', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 1', 0, null, '38554678-5179-5cec-bc71-f5d3c25e9c79', '61f447f4-c0d6-57de-932c-f5dd8eaf5a6a', 'Ring 3', (timestamp '2026-07-11 10:00' at time zone 'America/Edmonton'), 8),
  ('fca0e298-ce39-54b3-9f29-2d5af31b6cfe', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 1', 1, null, '2f1736b9-5729-5d64-bc5d-edfd95914915', '0cec645a-ad62-5f9c-9b58-65c6c0fc74ad', 'Ring 3', (timestamp '2026-07-11 10:10' at time zone 'America/Edmonton'), 8),
  ('a3d832a2-d599-577f-b1fd-6070cb39e0a6', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 2', 0, null, '61f447f4-c0d6-57de-932c-f5dd8eaf5a6a', '5c37d963-d52f-5874-aa0d-27890e4291e2', 'Ring 3', (timestamp '2026-07-11 10:20' at time zone 'America/Edmonton'), 8),
  ('66222194-810f-5b57-889b-6422fa244a4f', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 2', 1, null, '38554678-5179-5cec-bc71-f5d3c25e9c79', '2f1736b9-5729-5d64-bc5d-edfd95914915', 'Ring 3', (timestamp '2026-07-11 10:30' at time zone 'America/Edmonton'), 8),
  ('a2deaa5a-072e-5107-a2c2-c1b59435dbc5', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 3', 0, null, '5c37d963-d52f-5874-aa0d-27890e4291e2', '0cec645a-ad62-5f9c-9b58-65c6c0fc74ad', 'Ring 3', (timestamp '2026-07-11 10:40' at time zone 'America/Edmonton'), 8),
  ('d3d67d49-cfe6-570c-9b1f-5030bba9bf06', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 3', 1, null, '61f447f4-c0d6-57de-932c-f5dd8eaf5a6a', '2f1736b9-5729-5d64-bc5d-edfd95914915', 'Ring 3', (timestamp '2026-07-11 10:50' at time zone 'America/Edmonton'), 8),
  ('5ae2a046-415f-5942-b715-d67cb2422351', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 4', 0, null, '2f1736b9-5729-5d64-bc5d-edfd95914915', '5c37d963-d52f-5874-aa0d-27890e4291e2', 'Ring 3', (timestamp '2026-07-11 11:00' at time zone 'America/Edmonton'), 8),
  ('953a3ecd-dc2b-59c6-9150-09f4e62abaa4', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 4', 1, null, '0cec645a-ad62-5f9c-9b58-65c6c0fc74ad', '38554678-5179-5cec-bc71-f5d3c25e9c79', 'Ring 3', (timestamp '2026-07-11 11:10' at time zone 'America/Edmonton'), 8),
  ('0b688cb1-9400-535e-ac43-f49418541d46', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 5', 0, null, '5c37d963-d52f-5874-aa0d-27890e4291e2', '38554678-5179-5cec-bc71-f5d3c25e9c79', 'Ring 3', (timestamp '2026-07-11 11:20' at time zone 'America/Edmonton'), 8),
  ('15b62446-28f1-5583-9548-bb2cd0bc4945', 'a01f1330-2281-5d96-86e7-88240493a821', 'round_robin', 'Round 5', 1, null, '0cec645a-ad62-5f9c-9b58-65c6c0fc74ad', '61f447f4-c0d6-57de-932c-f5dd8eaf5a6a', 'Ring 3', (timestamp '2026-07-11 11:30' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,3]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ff9f0f99-8a8e-5602-abef-7b57e263cacb' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[2,0],"b":[1,3]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'fca0e298-ce39-54b3-9f29-2d5af31b6cfe' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 6, 8, '{"kind":"duel","rounds":{"a":[1,1,1,0,0,1,1,1],"b":[2,0,1,0,1,0,2,2]},"totals":{"a":6,"b":8}}'::jsonb, m.version) from public.matches m where m.id = 'a3d832a2-d599-577f-b1fd-6070cb39e0a6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,2]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '66222194-810f-5b57-889b-6422fa244a4f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 5, '{"kind":"duel","rounds":{"a":[0,0,1],"b":[1,0,4]},"totals":{"a":1,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'a2deaa5a-072e-5107-a2c2-c1b59435dbc5' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 2, '{"kind":"duel","rounds":{"a":[4,2],"b":[0,2]},"totals":{"a":6,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'd3d67d49-cfe6-570c-9b1f-5030bba9bf06' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 6, '{"kind":"duel","rounds":{"a":[0,2,2,0],"b":[0,2,3,1]},"totals":{"a":4,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '5ae2a046-415f-5942-b715-d67cb2422351' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 1, '{"kind":"duel","rounds":{"a":[5,1],"b":[0,1]},"totals":{"a":6,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '953a3ecd-dc2b-59c6-9150-09f4e62abaa4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[2,1],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '0b688cb1-9400-535e-ac43-f49418541d46' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[0,1,2,2],"b":[0,0,2,1]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '15b62446-28f1-5583-9548-bb2cd0bc4945' and m.queue_state <> 'final';
select public.finish_competition('a01f1330-2281-5d96-86e7-88240493a821', 'tournament_structure') where exists (select 1 from public.competitions where id = 'a01f1330-2281-5d96-86e7-88240493a821' and status <> 'finished');
-- Male Polearm: round_robin, 6 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('fb72bde9-769a-5d1b-92ec-2756480e7ea1', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 1', 0, null, '35e93bdd-65c0-5ee1-9192-bbef0936b771', '7b452f55-f6f3-52c5-a81a-60c3f8ffd1ea', 'Ring 1', (timestamp '2026-07-11 10:51' at time zone 'America/Edmonton'), 8),
  ('685c5baa-eee9-5429-9329-42d63cc03b21', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 1', 1, null, '08b4ae1e-26da-5366-ab14-15b22b57e099', '0489beaf-14be-508e-a3ca-547117c3ccba', 'Ring 1', (timestamp '2026-07-11 11:01' at time zone 'America/Edmonton'), 8),
  ('c3da3554-e634-5aa6-bb12-f5afbca36532', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 1', 2, null, '87fb0716-0e1e-5c3e-a60a-20373fd60483', '826ac709-faa5-5ec0-b50f-2e59152e7f3f', 'Ring 1', (timestamp '2026-07-11 11:11' at time zone 'America/Edmonton'), 8),
  ('4bd26957-d1c7-5b1a-a0c0-d1620a226d77', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 2', 0, null, '0489beaf-14be-508e-a3ca-547117c3ccba', '35e93bdd-65c0-5ee1-9192-bbef0936b771', 'Ring 1', (timestamp '2026-07-11 11:21' at time zone 'America/Edmonton'), 8),
  ('80f23914-3aee-5e1e-98a5-fd7d1fed20e6', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 2', 1, null, '7b452f55-f6f3-52c5-a81a-60c3f8ffd1ea', '826ac709-faa5-5ec0-b50f-2e59152e7f3f', 'Ring 1', (timestamp '2026-07-11 11:31' at time zone 'America/Edmonton'), 8),
  ('c6b8e9ce-ca39-5540-87a0-51d029e92c4f', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 2', 2, null, '08b4ae1e-26da-5366-ab14-15b22b57e099', '87fb0716-0e1e-5c3e-a60a-20373fd60483', 'Ring 1', (timestamp '2026-07-11 11:41' at time zone 'America/Edmonton'), 8),
  ('65cc3882-d75f-566d-bb04-40afdfd36391', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 3', 0, null, '35e93bdd-65c0-5ee1-9192-bbef0936b771', '826ac709-faa5-5ec0-b50f-2e59152e7f3f', 'Ring 1', (timestamp '2026-07-11 11:51' at time zone 'America/Edmonton'), 8),
  ('6ee76e53-14d6-5483-8a4e-7dabe443ead4', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 3', 1, null, '0489beaf-14be-508e-a3ca-547117c3ccba', '87fb0716-0e1e-5c3e-a60a-20373fd60483', 'Ring 1', (timestamp '2026-07-11 12:01' at time zone 'America/Edmonton'), 8),
  ('ea2df7fd-7fd1-57b1-9a00-76aa48f9e2e3', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 3', 2, null, '7b452f55-f6f3-52c5-a81a-60c3f8ffd1ea', '08b4ae1e-26da-5366-ab14-15b22b57e099', 'Ring 1', (timestamp '2026-07-11 12:11' at time zone 'America/Edmonton'), 8),
  ('73b66029-3625-5d6a-ac03-ab6a926c6e02', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 4', 0, null, '87fb0716-0e1e-5c3e-a60a-20373fd60483', '35e93bdd-65c0-5ee1-9192-bbef0936b771', 'Ring 1', (timestamp '2026-07-11 12:21' at time zone 'America/Edmonton'), 8),
  ('e41e46a8-872b-584c-a619-c29a4addf482', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 4', 1, null, '826ac709-faa5-5ec0-b50f-2e59152e7f3f', '08b4ae1e-26da-5366-ab14-15b22b57e099', 'Ring 1', (timestamp '2026-07-11 12:31' at time zone 'America/Edmonton'), 8),
  ('50e53ded-a607-5bea-8164-9f93e725a595', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 4', 2, null, '0489beaf-14be-508e-a3ca-547117c3ccba', '7b452f55-f6f3-52c5-a81a-60c3f8ffd1ea', 'Ring 1', (timestamp '2026-07-11 12:41' at time zone 'America/Edmonton'), 8),
  ('fd7b383f-9493-56c2-b0be-ce3791085a82', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 5', 0, null, '35e93bdd-65c0-5ee1-9192-bbef0936b771', '08b4ae1e-26da-5366-ab14-15b22b57e099', 'Ring 1', (timestamp '2026-07-11 12:51' at time zone 'America/Edmonton'), 8),
  ('786cabda-2b9a-50ac-9594-f362b99a9bd2', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 5', 1, null, '87fb0716-0e1e-5c3e-a60a-20373fd60483', '7b452f55-f6f3-52c5-a81a-60c3f8ffd1ea', 'Ring 1', (timestamp '2026-07-11 13:01' at time zone 'America/Edmonton'), 8),
  ('657870ee-ff30-5327-a7bc-949519201045', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'round_robin', 'Round 5', 2, null, '826ac709-faa5-5ec0-b50f-2e59152e7f3f', '0489beaf-14be-508e-a3ca-547117c3ccba', 'Ring 1', (timestamp '2026-07-11 13:11' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,0,1,0],"b":[0,0,1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'fb72bde9-769a-5d1b-92ec-2756480e7ea1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,1]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '685c5baa-eee9-5429-9329-42d63cc03b21' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[1,1],"b":[5,0]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'c3da3554-e634-5aa6-bb12-f5afbca36532' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 0, '{"kind":"duel","rounds":{"a":[2,5],"b":[0,0]},"totals":{"a":7,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '4bd26957-d1c7-5b1a-a0c0-d1620a226d77' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[2,1,1],"b":[1,1,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '80f23914-3aee-5e1e-98a5-fd7d1fed20e6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 0, '{"kind":"duel","rounds":{"a":[3,0],"b":[0,0]},"totals":{"a":3,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'c6b8e9ce-ca39-5540-87a0-51d029e92c4f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[2,1],"b":[1,0]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '65cc3882-d75f-566d-bb04-40afdfd36391' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[2,3],"b":[1,0]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '6ee76e53-14d6-5483-8a4e-7dabe443ead4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 3, '{"kind":"duel","rounds":{"a":[5,2],"b":[1,2]},"totals":{"a":7,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'ea2df7fd-7fd1-57b1-9a00-76aa48f9e2e3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[1,2],"b":[2,3]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '73b66029-3625-5d6a-ac03-ab6a926c6e02' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,3]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = 'e41e46a8-872b-584c-a619-c29a4addf482' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 3, 5, '{"kind":"duel","rounds":{"a":[1,0,1,1],"b":[1,1,0,3]},"totals":{"a":3,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '50e53ded-a607-5bea-8164-9f93e725a595' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 6, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,4]},"totals":{"a":0,"b":6}}'::jsonb, m.version) from public.matches m where m.id = 'fd7b383f-9493-56c2-b0be-ce3791085a82' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[2,1]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '786cabda-2b9a-50ac-9594-f362b99a9bd2' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 7, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,3]},"totals":{"a":0,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '657870ee-ff30-5327-a7bc-949519201045' and m.queue_state <> 'final';
select public.finish_competition('6c980b90-8fa8-5c51-8bea-78c8da264236', 'tournament_structure') where exists (select 1 from public.competitions where id = '6c980b90-8fa8-5c51-8bea-78c8da264236' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '15167fb9-8b0b-5992-9358-d9c7c4c1a1a1', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '289f4aeb-1d3e-5e68-9cf6-45c0da240b65', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'a01f1330-2281-5d96-86e7-88240493a821', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '6c980b90-8fa8-5c51-8bea-78c8da264236', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = '48c14d82-9d37-5f43-a309-89383d67b39e' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = '48c14d82-9d37-5f43-a309-89383d67b39e' and m.queue_state = 'final';
update public.audit_log set at = (date '2026-07-12' + time '21:00') at time zone 'America/Edmonton' where event_id = '48c14d82-9d37-5f43-a309-89383d67b39e';
commit;
