-- NACL-test fictional dataset: Rocky Mountain Rumble-test (completed). Everything here is fictional (names end in -test). Generated by scripts/testLeague; do not edit by hand.
-- Replace __OWNER_ID__ with the platform owner's auth user id before running. Safe to run again.

begin;
insert into public.events (id, slug, name, description, event_type, status, venue, city, region, country, timezone, fee_cents, starts_on, ends_on, host_team_id, registration_mode, time_note) values
  ('4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'rocky-mountain-rumble-test', 'Rocky Mountain Rumble-test', 'The latest completed event: a large mountain weekend hosted by Mountain Bears-test.', 'tournament', 'published', 'Mountain Rec Centre-test', 'Canmore', 'AB', 'CA', 'America/Edmonton', 0, date '2026-09-12', date '2026-09-13', '5796049c-2e49-521c-b959-47744fa8c73f', 'none', 'Fictional test event. Entries were recorded by the organizer; there is no registration form.')
on conflict (id) do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'event', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"__OWNER_ID__","role":"authenticated"}', true);
select public.set_event_season('4ce9cfd7-c876-5a1b-928b-ef86ded32066', '6acd0719-46c7-540c-9290-1e09e1af0070');
select public.set_event_organization('4ce9cfd7-c876-5a1b-928b-ef86ded32066', '9b255f37-a821-57e0-a2a3-0a0811646ddf');
insert into public.competitions (id, event_id, name, category, gender, tier, ruleset, structure, status, rounds_to_win, sort) values
  ('9e464303-7e2f-5606-8224-dbba22e69349', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Male 5v5', '5v5', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 10),
  ('38fe0d63-4153-5653-99f9-a88ee62214f9', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Female 5v5', '5v5', 'women', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 20),
  ('d6d1573f-0109-5741-b867-6e6797a4e028', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Male 3v3', '3v3', 'men', 'Classic', 'Buhurt International: Buhurt Rules V.26.4.1', 'round_robin', 'running', 2, 30),
  ('0f8661f9-6ec8-56d2-9e36-1278513c04d3', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Male Longsword', 'longsword', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 40),
  ('729aeb14-31cb-5c88-8c01-c926003118b3', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Female Longsword', 'longsword', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 50),
  ('42b52d0d-4876-5bbe-9102-812c0dc77222', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Male Sword & Shield', 'sword_shield', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 60),
  ('12d8e791-8b11-515e-be38-f0f1f1d9cddc', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Female Sword & Shield', 'sword_shield', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 70),
  ('af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Male Polearm', 'polearm', 'men', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 80),
  ('28c264b4-5c17-5990-a7d1-f5e505b6b798', '4ce9cfd7-c876-5a1b-928b-ef86ded32066', 'Female Polearm', 'polearm', 'women', 'Classic', 'Buhurt International: Duels rules V.26.4', 'elimination', 'running', null, 90)
on conflict (id) do nothing;
insert into public.entries (id, competition_id, team_id, fighter_id, status) values
  ('f1c0d300-5203-5611-ad42-ddc7a0e9437d', '9e464303-7e2f-5606-8224-dbba22e69349', '4842a217-7f85-509f-aa7e-cefa2bffbfab', null, 'checked_in'),
  ('9b26194b-c5ba-5f94-8994-e656cb598cd4', '9e464303-7e2f-5606-8224-dbba22e69349', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('2dde05ba-4a28-52aa-96c1-532e7d0882a0', '9e464303-7e2f-5606-8224-dbba22e69349', '5796049c-2e49-521c-b959-47744fa8c73f', null, 'checked_in'),
  ('e67b0e94-e918-5bfe-8373-5340ed81e2d2', '38fe0d63-4153-5653-99f9-a88ee62214f9', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('d55bdb67-f9ea-5fc6-ad4b-791b6da5af30', '38fe0d63-4153-5653-99f9-a88ee62214f9', '9e6caec8-33a2-5b5c-97e8-89f86facf0ea', null, 'checked_in'),
  ('5cdbe4a2-abf7-5645-b0b0-e14764dd41fa', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('a6770780-34cb-5189-ae86-9f6dddfd60a3', '38fe0d63-4153-5653-99f9-a88ee62214f9', '5796049c-2e49-521c-b959-47744fa8c73f', null, 'checked_in'),
  ('d383e922-8044-55da-a845-c3958f71347f', 'd6d1573f-0109-5741-b867-6e6797a4e028', '4842a217-7f85-509f-aa7e-cefa2bffbfab', null, 'checked_in'),
  ('048d24ca-1201-5095-8432-2542bc64769d', 'd6d1573f-0109-5741-b867-6e6797a4e028', '93d193e0-68eb-5bb6-a045-4b963f97ef22', null, 'checked_in'),
  ('6d0d1194-68b5-5223-9d03-6a5b8f6d1936', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'b902f3cf-959c-5300-b019-d678b76aee3a', null, 'checked_in'),
  ('bba1c9a3-fda8-5cdf-b496-5652c743b3ac', 'd6d1573f-0109-5741-b867-6e6797a4e028', '19b99cd7-c067-5ae8-b5ba-88b4dab9678f', null, 'checked_in'),
  ('ea02392e-3f8c-5e4d-84a8-5859282d5e12', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, 'dc986b96-be3f-5c26-914b-c1162aa0eb4b', 'checked_in'),
  ('908f570a-69ef-5566-a7dc-f04cf26ecdb9', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, '7ba3fceb-e85e-5ed0-84a0-76915d6c6f83', 'checked_in'),
  ('d826b5ac-d9ee-5cb4-a18d-0bc5054e7f05', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, '88383cff-3cd0-5e0a-91bd-8c375e39c4b5', 'checked_in'),
  ('74ca297a-25f3-514b-8de8-94fa0ebc013b', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, 'e3b4a9f7-0116-5514-b4ba-e76cfc0ee774', 'checked_in'),
  ('cb061c1f-b786-53fb-986e-a348c01d7324', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, '88d259b3-3d84-5796-bdcb-c2fdfd8b09ed', 'checked_in'),
  ('9409f043-1968-58d9-b875-045934b81997', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, 'c2114868-da44-5a82-a1d3-f91f5326285f', 'checked_in'),
  ('d6da165f-ca1d-5a48-afa3-cc3a6bb85ef9', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, '7df00fd3-0d78-5dbe-b0c7-eeaceda48ddb', 'checked_in'),
  ('bf7e562a-8879-5f49-b90c-c5582af17ae8', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, '54a3231b-0712-5fe9-8b22-4e8cca02a99c', 'checked_in'),
  ('ec4c756c-a935-553c-a511-a4bb3d57bb59', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', null, '31375f7d-13ba-5a5f-95ec-75173fd0c9a1', 'checked_in'),
  ('d24779dd-75e5-5e6a-96fb-5f4cd4cb588a', '729aeb14-31cb-5c88-8c01-c926003118b3', null, 'a92a1c83-58d6-572d-9736-27fde0c87cf7', 'checked_in'),
  ('61d74e9d-75fb-5cd8-9f57-f6730db1f96d', '729aeb14-31cb-5c88-8c01-c926003118b3', null, '0debf14e-901a-5dde-a288-533867b19c6e', 'checked_in'),
  ('cbb0fa3f-00ed-54d8-bc76-f2dcff15ff3d', '729aeb14-31cb-5c88-8c01-c926003118b3', null, 'ccd25c59-7eec-5757-bff1-3437c26baed8', 'checked_in'),
  ('333a2510-f342-5136-9816-6bd8e533b684', '729aeb14-31cb-5c88-8c01-c926003118b3', null, 'fb79f2e7-85b4-5565-b024-4a24ed929a62', 'checked_in'),
  ('33b9a635-54a6-5cc2-a4a4-aedca900fff9', '729aeb14-31cb-5c88-8c01-c926003118b3', null, 'a84d9159-737e-54fd-ad21-cbbe6152d754', 'checked_in'),
  ('ebc43e47-9fdc-5e7a-86f3-3ea269daff18', '729aeb14-31cb-5c88-8c01-c926003118b3', null, '9890f7c8-373a-5cf8-b06c-34ea20a58304', 'checked_in'),
  ('63d5ff77-9de5-5910-b19e-969d8099e36e', '729aeb14-31cb-5c88-8c01-c926003118b3', null, '4cb4a51f-1606-5b8d-bf8b-4d859aef037c', 'checked_in'),
  ('215fc1b1-1919-554b-8f5a-153803f7eb9e', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, 'b4b23592-ecfd-5625-92ec-4224c70404c2', 'checked_in'),
  ('7999f0ce-9273-5d38-9f2f-708d99f811f5', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, '72ab5bcb-c669-59a6-9865-86a0a151bc59', 'checked_in'),
  ('c97a2f9f-d9f7-5074-81ae-a326c7531137', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, 'a6d7fbe4-0392-5679-9e83-3a4693aa452d', 'checked_in'),
  ('307bc6b8-be73-5621-94bc-ddfcc0a502dc', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, '4a28fccb-ff24-506e-8459-b2a304fb4784', 'checked_in'),
  ('3dfb80d4-abfc-5476-b8a2-781021d345c3', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, '74aade55-9f48-5ddd-867a-c465dcdc36e0', 'checked_in'),
  ('3659fcad-a346-5f61-aba1-8b4a54cc510d', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, 'cb21b06a-886b-5e1a-9453-1c173a5168f9', 'checked_in'),
  ('a4490a84-a492-541a-b141-b4efff06e647', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, 'bcf07ca4-7db2-527a-a644-5c49ff701df3', 'checked_in'),
  ('318f709b-4575-5b93-8b6f-ff4b2c1955cc', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, 'b181793f-6729-5349-8392-78e65113b857', 'checked_in'),
  ('1c89ef7b-5729-51a0-9661-d601ad3f9d68', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, '53ac4dfa-3d15-5881-8a92-361c7e59b120', 'checked_in'),
  ('55ad2026-b06d-58ad-bb32-2c8a1059ef2a', '42b52d0d-4876-5bbe-9102-812c0dc77222', null, 'f5cc5373-d952-5604-adde-f304f3f6c86e', 'checked_in'),
  ('fda9fba2-de73-5380-8c66-8dd84d8065f0', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '285f8b35-de1b-5ade-82c6-4fe0a0a132d9', 'checked_in'),
  ('3d6c657e-0800-5570-9b98-615d8487797c', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '8a0b0f89-6e54-548f-938c-84238b1e23e1', 'checked_in'),
  ('b7db1d4d-93bc-5641-9e8a-b81007588819', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '14aed5cd-7ebd-5bd5-a88c-b122058d9b5b', 'checked_in'),
  ('fc30db42-8e1a-5b29-a32c-c22c1fa98131', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '48e29b2c-61a9-5986-88bf-44714334aa9d', 'checked_in'),
  ('f9ee30ac-5eb5-5e41-abde-60c2fa5fbecc', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, 'f59071d8-f158-5947-ba7a-7ff8533d06e5', 'checked_in'),
  ('c91dafc0-e4e9-501a-9d42-d47180107a44', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '1c29a853-dcea-582a-9561-f92c4ef9b6a3', 'checked_in'),
  ('15c12771-09c5-5830-9842-8cb1da99b529', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, 'f7373850-cf16-5419-8c34-acfe15164af2', 'checked_in'),
  ('a73913ee-479a-59bf-b735-4b2ddc60d9b1', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '982d4f9a-fb1c-5e81-b7f7-62c231c79fb2', 'checked_in'),
  ('d62eb267-8c22-5406-9fe8-c50c7e9e71e6', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '3ce36aa6-ecae-5293-bac9-da3cebdd791a', 'checked_in'),
  ('403946d8-8c8c-5f70-adf2-a2d754838a21', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', null, '5777bdcc-18bc-518f-a88f-103441365171', 'checked_in'),
  ('60a5b8d3-2379-5e80-80c8-7d40d5d2ba75', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, 'bd195699-a4ba-5049-babf-d01f743911b5', 'checked_in'),
  ('daefcffe-1df0-5e5b-87b4-edfbcc266445', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, '0e28a5bf-3ca5-50ce-bf11-142105c58181', 'checked_in'),
  ('93310ee9-f945-52b1-a7e8-42db45bc19c5', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, '1fcb6cfe-8069-5c6d-96dd-56ea1b461f7b', 'checked_in'),
  ('1c8cc372-676c-58ca-a941-660a0cad68d0', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, '695e3415-b6f8-5182-94d9-d8e4904c74e6', 'checked_in'),
  ('c5ccb820-350e-5b52-918d-52a5d314a442', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, '488ea1e6-aded-5c9c-b935-de30de9cf949', 'checked_in'),
  ('34f704c4-a0a9-5e58-b31a-0fade42f835a', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, '98146ed7-d388-5e3c-822d-f8d5285044bf', 'checked_in'),
  ('7c246c07-b8ec-5c8d-9363-5247a675ed75', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', null, 'b9551194-d28a-50e3-9bfc-36c446fa8f54', 'checked_in'),
  ('02016075-47f4-5be6-af74-7abc0eb539c0', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '8a8305b0-ca44-5b4f-847e-7cb7d1c13988', 'checked_in'),
  ('516c0a46-6791-5903-b015-6f17a38ee275', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '0e9e0d00-70a7-5985-ac4a-8b379a5521bf', 'checked_in'),
  ('a152064f-97c1-5791-ac06-5b425c434aa6', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '76cd4d5a-eb01-5869-8182-cfd75385dc7f', 'checked_in'),
  ('2cc21646-3cc8-5b94-8a12-07c0b23517bd', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, 'd5185702-fa37-5db8-8a4d-2cb114461bcf', 'checked_in'),
  ('db241e7e-cc89-569c-abed-a3e9a5c0e7b9', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '0b508c1f-b0a2-524e-b471-331960200135', 'checked_in'),
  ('1ab0da7f-3dd7-5ecc-a983-a6f0ab21a062', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '831b7043-6c86-5de6-9865-fba0592e1309', 'checked_in'),
  ('c17c9fea-5782-5142-bd76-b606d29b0221', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '27a1672b-da85-5cb1-b3d2-29f1d968da7a', 'checked_in'),
  ('9fdd8385-e05d-5a86-a5f8-fe888686f067', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '9b2380a1-bda2-56dc-bf4b-5f04307838d7', 'checked_in'),
  ('6f0607ca-583d-5584-8a73-32efdea5b2e5', '28c264b4-5c17-5990-a7d1-f5e505b6b798', null, '67c1cd1c-898d-5c7a-a7a8-1fceccb87ba3', 'checked_in')
on conflict (id) do nothing;
select public.set_entry_roster('f1c0d300-5203-5611-ad42-ddc7a0e9437d', '[{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"fighter"},{"fighter_id":"b4b23592-ecfd-5625-92ec-4224c70404c2","role":"fighter"},{"fighter_id":"bd195699-a4ba-5049-babf-d01f743911b5","role":"fighter"},{"fighter_id":"4a28fccb-ff24-506e-8459-b2a304fb4784","role":"mercenary"},{"fighter_id":"53ac4dfa-3d15-5881-8a92-361c7e59b120","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '9e464303-7e2f-5606-8224-dbba22e69349' and status <> 'finished');
select public.set_entry_roster('9b26194b-c5ba-5f94-8994-e656cb598cd4', '[{"fighter_id":"cb21b06a-886b-5e1a-9453-1c173a5168f9","role":"fighter"},{"fighter_id":"88d259b3-3d84-5796-bdcb-c2fdfd8b09ed","role":"fighter"},{"fighter_id":"0e28a5bf-3ca5-50ce-bf11-142105c58181","role":"fighter"},{"fighter_id":"e3b4a9f7-0116-5514-b4ba-e76cfc0ee774","role":"fighter"},{"fighter_id":"a6d7fbe4-0392-5679-9e83-3a4693aa452d","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '9e464303-7e2f-5606-8224-dbba22e69349' and status <> 'finished');
select public.set_entry_roster('2dde05ba-4a28-52aa-96c1-532e7d0882a0', '[{"fighter_id":"7df00fd3-0d78-5dbe-b0c7-eeaceda48ddb","role":"fighter"},{"fighter_id":"b181793f-6729-5349-8392-78e65113b857","role":"fighter"},{"fighter_id":"695e3415-b6f8-5182-94d9-d8e4904c74e6","role":"fighter"},{"fighter_id":"bcf07ca4-7db2-527a-a644-5c49ff701df3","role":"fighter"},{"fighter_id":"1fcb6cfe-8069-5c6d-96dd-56ea1b461f7b","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = '9e464303-7e2f-5606-8224-dbba22e69349' and status <> 'finished');
select public.set_entry_roster('e67b0e94-e918-5bfe-8373-5340ed81e2d2', '[{"fighter_id":"a92a1c83-58d6-572d-9736-27fde0c87cf7","role":"fighter"},{"fighter_id":"8a0b0f89-6e54-548f-938c-84238b1e23e1","role":"fighter"},{"fighter_id":"285f8b35-de1b-5ade-82c6-4fe0a0a132d9","role":"fighter"},{"fighter_id":"3ce36aa6-ecae-5293-bac9-da3cebdd791a","role":"mercenary"},{"fighter_id":"4cb4a51f-1606-5b8d-bf8b-4d859aef037c","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '38fe0d63-4153-5653-99f9-a88ee62214f9' and status <> 'finished');
select public.set_entry_roster('d55bdb67-f9ea-5fc6-ad4b-791b6da5af30', '[{"fighter_id":"0e9e0d00-70a7-5985-ac4a-8b379a5521bf","role":"fighter"},{"fighter_id":"76cd4d5a-eb01-5869-8182-cfd75385dc7f","role":"fighter"},{"fighter_id":"ccd25c59-7eec-5757-bff1-3437c26baed8","role":"fighter"},{"fighter_id":"14aed5cd-7ebd-5bd5-a88c-b122058d9b5b","role":"fighter"},{"fighter_id":"7b2a7b7d-ddd2-595d-9269-7efa0dbacd1a","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '38fe0d63-4153-5653-99f9-a88ee62214f9' and status <> 'finished');
select public.set_entry_roster('5cdbe4a2-abf7-5645-b0b0-e14764dd41fa', '[{"fighter_id":"0b508c1f-b0a2-524e-b471-331960200135","role":"fighter"},{"fighter_id":"1c29a853-dcea-582a-9561-f92c4ef9b6a3","role":"fighter"},{"fighter_id":"9890f7c8-373a-5cf8-b06c-34ea20a58304","role":"fighter"},{"fighter_id":"a84d9159-737e-54fd-ad21-cbbe6152d754","role":"fighter"},{"fighter_id":"982d4f9a-fb1c-5e81-b7f7-62c231c79fb2","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '38fe0d63-4153-5653-99f9-a88ee62214f9' and status <> 'finished');
select public.set_entry_roster('a6770780-34cb-5189-ae86-9f6dddfd60a3', '[{"fighter_id":"f7373850-cf16-5419-8c34-acfe15164af2","role":"fighter"},{"fighter_id":"831b7043-6c86-5de6-9865-fba0592e1309","role":"fighter"},{"fighter_id":"27a1672b-da85-5cb1-b3d2-29f1d968da7a","role":"fighter"},{"fighter_id":"44de541c-49d9-5576-bad7-2bcd7f194801","role":"mercenary"},{"fighter_id":"48e29b2c-61a9-5986-88bf-44714334aa9d","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = '38fe0d63-4153-5653-99f9-a88ee62214f9' and status <> 'finished');
select public.set_entry_roster('d383e922-8044-55da-a845-c3958f71347f', '[{"fighter_id":"dc986b96-be3f-5c26-914b-c1162aa0eb4b","role":"fighter"},{"fighter_id":"bd195699-a4ba-5049-babf-d01f743911b5","role":"fighter"},{"fighter_id":"b4b23592-ecfd-5625-92ec-4224c70404c2","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = 'd6d1573f-0109-5741-b867-6e6797a4e028' and status <> 'finished');
select public.set_entry_roster('048d24ca-1201-5095-8432-2542bc64769d', '[{"fighter_id":"ff6d3454-18ef-5175-9d2b-56f676185804","role":"fighter"},{"fighter_id":"72ab5bcb-c669-59a6-9865-86a0a151bc59","role":"fighter"},{"fighter_id":"a6d7fbe4-0392-5679-9e83-3a4693aa452d","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'd6d1573f-0109-5741-b867-6e6797a4e028' and status <> 'finished');
select public.set_entry_roster('6d0d1194-68b5-5223-9d03-6a5b8f6d1936', '[{"fighter_id":"0e28a5bf-3ca5-50ce-bf11-142105c58181","role":"fighter"},{"fighter_id":"c2114868-da44-5a82-a1d3-f91f5326285f","role":"fighter"},{"fighter_id":"88d259b3-3d84-5796-bdcb-c2fdfd8b09ed","role":"fighter"}]'::jsonb) where exists (select 1 from public.competitions where id = 'd6d1573f-0109-5741-b867-6e6797a4e028' and status <> 'finished');
select public.set_entry_roster('bba1c9a3-fda8-5cdf-b496-5652c743b3ac', '[{"fighter_id":"54a3231b-0712-5fe9-8b22-4e8cca02a99c","role":"fighter"},{"fighter_id":"31375f7d-13ba-5a5f-95ec-75173fd0c9a1","role":"fighter"},{"fighter_id":"695e3415-b6f8-5182-94d9-d8e4904c74e6","role":"mercenary"}]'::jsonb) where exists (select 1 from public.competitions where id = 'd6d1573f-0109-5741-b867-6e6797a4e028' and status <> 'finished');
-- Male 5v5: round_robin, 3 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('052c4fb2-4d8a-5c5c-aa17-d88315cabe41', '9e464303-7e2f-5606-8224-dbba22e69349', 'round_robin', 'Round 1', 0, null, 'f1c0d300-5203-5611-ad42-ddc7a0e9437d', '9b26194b-c5ba-5f94-8994-e656cb598cd4', 'Ring 1', (timestamp '2026-09-12 10:00' at time zone 'America/Edmonton'), 15),
  ('fcf21723-1c62-5978-ac94-f2047814a117', '9e464303-7e2f-5606-8224-dbba22e69349', 'round_robin', 'Round 2', 0, null, '9b26194b-c5ba-5f94-8994-e656cb598cd4', '2dde05ba-4a28-52aa-96c1-532e7d0882a0', 'Ring 1', (timestamp '2026-09-12 10:17' at time zone 'America/Edmonton'), 15),
  ('7d19447d-f501-5785-8fe4-e995d60c3df2', '9e464303-7e2f-5606-8224-dbba22e69349', 'round_robin', 'Round 3', 0, null, '2dde05ba-4a28-52aa-96c1-532e7d0882a0', 'f1c0d300-5203-5611-ad42-ddc7a0e9437d', 'Ring 1', (timestamp '2026-09-12 10:34' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '052c4fb2-4d8a-5c5c-aa17-d88315cabe41' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = 'fcf21723-1c62-5978-ac94-f2047814a117' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '7d19447d-f501-5785-8fe4-e995d60c3df2' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '9e464303-7e2f-5606-8224-dbba22e69349' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('9e464303-7e2f-5606-8224-dbba22e69349') where tied group by part, rank loop perform public.record_tie_decision('9e464303-7e2f-5606-8224-dbba22e69349', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('9e464303-7e2f-5606-8224-dbba22e69349', 'tournament_structure') where exists (select 1 from public.competitions where id = '9e464303-7e2f-5606-8224-dbba22e69349' and status <> 'finished');
-- Female 5v5: round_robin, 4 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('c69ae89b-d012-5a43-8d55-c9fdd8a3c72b', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'round_robin', 'Round 1', 0, null, 'd55bdb67-f9ea-5fc6-ad4b-791b6da5af30', 'e67b0e94-e918-5bfe-8373-5340ed81e2d2', 'Ring 2', (timestamp '2026-09-12 10:00' at time zone 'America/Edmonton'), 15),
  ('a3389d0c-4c1c-5675-82c2-9d2f4c271aef', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'round_robin', 'Round 1', 1, null, 'a6770780-34cb-5189-ae86-9f6dddfd60a3', '5cdbe4a2-abf7-5645-b0b0-e14764dd41fa', 'Ring 2', (timestamp '2026-09-12 10:17' at time zone 'America/Edmonton'), 15),
  ('93d5ef07-2b30-5a37-97ed-75242a253413', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'round_robin', 'Round 2', 0, null, '5cdbe4a2-abf7-5645-b0b0-e14764dd41fa', 'd55bdb67-f9ea-5fc6-ad4b-791b6da5af30', 'Ring 2', (timestamp '2026-09-12 10:34' at time zone 'America/Edmonton'), 15),
  ('dc1cc7f2-3134-5f9a-b975-efb8de369c46', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'round_robin', 'Round 2', 1, null, 'e67b0e94-e918-5bfe-8373-5340ed81e2d2', 'a6770780-34cb-5189-ae86-9f6dddfd60a3', 'Ring 2', (timestamp '2026-09-12 10:51' at time zone 'America/Edmonton'), 15),
  ('50f5569c-5202-5b07-9f99-246ff778ef93', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'round_robin', 'Round 3', 0, null, 'd55bdb67-f9ea-5fc6-ad4b-791b6da5af30', 'a6770780-34cb-5189-ae86-9f6dddfd60a3', 'Ring 2', (timestamp '2026-09-12 11:08' at time zone 'America/Edmonton'), 15),
  ('5926cf75-9172-5f64-9ac8-b76d62699a83', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'round_robin', 'Round 3', 1, null, '5cdbe4a2-abf7-5645-b0b0-e14764dd41fa', 'e67b0e94-e918-5bfe-8373-5340ed81e2d2', 'Ring 2', (timestamp '2026-09-12 11:25' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'c69ae89b-d012-5a43-8d55-c9fdd8a3c72b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'a3389d0c-4c1c-5675-82c2-9d2f4c271aef' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '93d5ef07-2b30-5a37-97ed-75242a253413' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":1,"b":2},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = 'dc1cc7f2-3134-5f9a-b975-efb8de369c46' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '50f5569c-5202-5b07-9f99-246ff778ef93' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '5926cf75-9172-5f64-9ac8-b76d62699a83' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '38fe0d63-4153-5653-99f9-a88ee62214f9' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('38fe0d63-4153-5653-99f9-a88ee62214f9') where tied group by part, rank loop perform public.record_tie_decision('38fe0d63-4153-5653-99f9-a88ee62214f9', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('38fe0d63-4153-5653-99f9-a88ee62214f9', 'tournament_structure') where exists (select 1 from public.competitions where id = '38fe0d63-4153-5653-99f9-a88ee62214f9' and status <> 'finished');
-- Male 3v3: round_robin, 4 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('89381cd5-608b-510a-baa9-4cf5b75dca0a', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'round_robin', 'Round 1', 0, null, 'bba1c9a3-fda8-5cdf-b496-5652c743b3ac', '6d0d1194-68b5-5223-9d03-6a5b8f6d1936', 'Ring 3', (timestamp '2026-09-12 10:00' at time zone 'America/Edmonton'), 15),
  ('d8bbfb84-0dd1-5c21-8196-b126a8b1da7b', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'round_robin', 'Round 1', 1, null, 'd383e922-8044-55da-a845-c3958f71347f', '048d24ca-1201-5095-8432-2542bc64769d', 'Ring 3', (timestamp '2026-09-12 10:17' at time zone 'America/Edmonton'), 15),
  ('a463dae8-fbf5-5b6a-9180-28740e0fe047', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'round_robin', 'Round 2', 0, null, '048d24ca-1201-5095-8432-2542bc64769d', 'bba1c9a3-fda8-5cdf-b496-5652c743b3ac', 'Ring 3', (timestamp '2026-09-12 10:34' at time zone 'America/Edmonton'), 15),
  ('5167e318-a39d-5e73-8620-37cee0f17cbb', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'round_robin', 'Round 2', 1, null, '6d0d1194-68b5-5223-9d03-6a5b8f6d1936', 'd383e922-8044-55da-a845-c3958f71347f', 'Ring 3', (timestamp '2026-09-12 10:51' at time zone 'America/Edmonton'), 15),
  ('5090d9a9-82bd-5184-9de1-7175824e84cc', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'round_robin', 'Round 3', 0, null, 'bba1c9a3-fda8-5cdf-b496-5652c743b3ac', 'd383e922-8044-55da-a845-c3958f71347f', 'Ring 3', (timestamp '2026-09-12 11:08' at time zone 'America/Edmonton'), 15),
  ('3eeed542-8ece-5d31-bdd9-2e62f814b421', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'round_robin', 'Round 3', 1, null, '048d24ca-1201-5095-8432-2542bc64769d', '6d0d1194-68b5-5223-9d03-6a5b8f6d1936', 'Ring 3', (timestamp '2026-09-12 11:25' at time zone 'America/Edmonton'), 15)
on conflict (id) do nothing;
select public.finalize_match(m.id, 'b', 0, 2, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":0,"b":2},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '89381cd5-608b-510a-baa9-4cf5b75dca0a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = 'd8bbfb84-0dd1-5c21-8196-b126a8b1da7b' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = 'a463dae8-fbf5-5b6a-9180-28740e0fe047' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '5167e318-a39d-5e73-8620-37cee0f17cbb' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 1, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":1},"roundsPlayed":3}'::jsonb, m.version) from public.matches m where m.id = '5090d9a9-82bd-5184-9de1-7175824e84cc' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"group","roundsToWin":2,"roundsWon":{"a":2,"b":0},"roundsPlayed":2}'::jsonb, m.version) from public.matches m where m.id = '3eeed542-8ece-5d31-bdd9-2e62f814b421' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'd6d1573f-0109-5741-b867-6e6797a4e028' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('d6d1573f-0109-5741-b867-6e6797a4e028') where tied group by part, rank loop perform public.record_tie_decision('d6d1573f-0109-5741-b867-6e6797a4e028', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('d6d1573f-0109-5741-b867-6e6797a4e028', 'tournament_structure') where exists (select 1 from public.competitions where id = 'd6d1573f-0109-5741-b867-6e6797a4e028' and status <> 'finished');
-- Male Longsword: elimination, 9 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('e8f5215d-a530-5b3f-aa69-454489bcacfe', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Round of 16', 1, null, 'ea02392e-3f8c-5e4d-84a8-5859282d5e12', '908f570a-69ef-5566-a7dc-f04cf26ecdb9', 'Ring 4', (timestamp '2026-09-12 10:00' at time zone 'America/Edmonton'), 8),
  ('57064d18-ecf4-56c6-9017-078e49a343cc', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Quarterfinal', 0, null, '74ca297a-25f3-514b-8de8-94fa0ebc013b', null, 'Ring 4', (timestamp '2026-09-12 10:10' at time zone 'America/Edmonton'), 8),
  ('36c7a7f5-a04f-58b5-963a-97a4bab7c853', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Quarterfinal', 1, null, 'cb061c1f-b786-53fb-986e-a348c01d7324', '9409f043-1968-58d9-b875-045934b81997', 'Ring 4', (timestamp '2026-09-12 10:20' at time zone 'America/Edmonton'), 8),
  ('d7b42e9f-045a-55df-9613-d9b19a4b1696', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Quarterfinal', 2, null, 'bf7e562a-8879-5f49-b90c-c5582af17ae8', 'ec4c756c-a935-553c-a511-a4bb3d57bb59', 'Ring 4', (timestamp '2026-09-12 10:30' at time zone 'America/Edmonton'), 8),
  ('1c7ef1e1-9e9e-5850-b557-91d8d842b19e', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Quarterfinal', 3, null, 'd826b5ac-d9ee-5cb4-a18d-0bc5054e7f05', 'd6da165f-ca1d-5a48-afa3-cc3a6bb85ef9', 'Ring 4', (timestamp '2026-09-12 10:40' at time zone 'America/Edmonton'), 8),
  ('cf5b0004-cad2-5b35-a3e0-c7bc15c7fb27', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 4', (timestamp '2026-09-12 10:50' at time zone 'America/Edmonton'), 8),
  ('c3ab21de-b7c0-52db-a252-6165b8d565a6', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 4', (timestamp '2026-09-12 11:00' at time zone 'America/Edmonton'), 8),
  ('a8baa6b8-bea5-5f65-9924-c6db37e928d3', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'final', 'Final', 0, null, null, null, 'Ring 4', (timestamp '2026-09-12 11:10' at time zone 'America/Edmonton'), 8),
  ('abb1766f-d7fb-5551-86aa-166e02550be5', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'third_place', 'Third place', 0, null, null, null, 'Ring 4', (timestamp '2026-09-12 11:20' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('e8f5215d-a530-5b3f-aa69-454489bcacfe'::uuid, '57064d18-ecf4-56c6-9017-078e49a343cc'::uuid, 'b'),
  ('57064d18-ecf4-56c6-9017-078e49a343cc'::uuid, 'cf5b0004-cad2-5b35-a3e0-c7bc15c7fb27'::uuid, 'a'),
  ('36c7a7f5-a04f-58b5-963a-97a4bab7c853'::uuid, 'cf5b0004-cad2-5b35-a3e0-c7bc15c7fb27'::uuid, 'b'),
  ('d7b42e9f-045a-55df-9613-d9b19a4b1696'::uuid, 'c3ab21de-b7c0-52db-a252-6165b8d565a6'::uuid, 'a'),
  ('1c7ef1e1-9e9e-5850-b557-91d8d842b19e'::uuid, 'c3ab21de-b7c0-52db-a252-6165b8d565a6'::uuid, 'b'),
  ('cf5b0004-cad2-5b35-a3e0-c7bc15c7fb27'::uuid, 'a8baa6b8-bea5-5f65-9924-c6db37e928d3'::uuid, 'a'),
  ('c3ab21de-b7c0-52db-a252-6165b8d565a6'::uuid, 'a8baa6b8-bea5-5f65-9924-c6db37e928d3'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[1,1,2,1],"b":[0,3,2,2]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'e8f5215d-a530-5b3f-aa69-454489bcacfe' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 5, '{"kind":"duel","rounds":{"a":[2,1,2,0,4],"b":[2,1,1,1,0]},"totals":{"a":9,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '57064d18-ecf4-56c6-9017-078e49a343cc' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[3,1,1],"b":[3,0,0]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '36c7a7f5-a04f-58b5-963a-97a4bab7c853' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[0,1,0],"b":[1,1,1]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'd7b42e9f-045a-55df-9613-d9b19a4b1696' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[0,1,1,1,0,2],"b":[1,1,0,1,0,0]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '1c7ef1e1-9e9e-5850-b557-91d8d842b19e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[3,0,2],"b":[2,0,0]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'cf5b0004-cad2-5b35-a3e0-c7bc15c7fb27' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 6, '{"kind":"duel","rounds":{"a":[0,1],"b":[4,2]},"totals":{"a":1,"b":6}}'::jsonb, m.version) from public.matches m where m.id = 'c3ab21de-b7c0-52db-a252-6165b8d565a6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'a8baa6b8-bea5-5f65-9924-c6db37e928d3' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 7, 4, '{"kind":"duel","rounds":{"a":[1,3,0,3],"b":[1,2,0,1]},"totals":{"a":7,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'abb1766f-d7fb-5551-86aa-166e02550be5' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '0f8661f9-6ec8-56d2-9e36-1278513c04d3' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('0f8661f9-6ec8-56d2-9e36-1278513c04d3') where tied group by part, rank loop perform public.record_tie_decision('0f8661f9-6ec8-56d2-9e36-1278513c04d3', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'tournament_structure') where exists (select 1 from public.competitions where id = '0f8661f9-6ec8-56d2-9e36-1278513c04d3' and status <> 'finished');
-- Female Longsword: elimination, 7 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('36127629-7e9a-5984-b417-453244e66aba', '729aeb14-31cb-5c88-8c01-c926003118b3', 'elimination', 'Quarterfinal', 1, null, '333a2510-f342-5136-9816-6bd8e533b684', '61d74e9d-75fb-5cd8-9f57-f6730db1f96d', 'Ring 1', (timestamp '2026-09-12 10:51' at time zone 'America/Edmonton'), 8),
  ('75026b22-1fc3-5042-93eb-79538a8a989c', '729aeb14-31cb-5c88-8c01-c926003118b3', 'elimination', 'Quarterfinal', 2, null, '63d5ff77-9de5-5910-b19e-969d8099e36e', 'ebc43e47-9fdc-5e7a-86f3-3ea269daff18', 'Ring 1', (timestamp '2026-09-12 11:01' at time zone 'America/Edmonton'), 8),
  ('e2aba771-7b14-5e79-8629-64d69628b892', '729aeb14-31cb-5c88-8c01-c926003118b3', 'elimination', 'Quarterfinal', 3, null, 'd24779dd-75e5-5e6a-96fb-5f4cd4cb588a', '33b9a635-54a6-5cc2-a4a4-aedca900fff9', 'Ring 1', (timestamp '2026-09-12 11:11' at time zone 'America/Edmonton'), 8),
  ('26e02510-ba36-51d3-9461-b362d7fee37a', '729aeb14-31cb-5c88-8c01-c926003118b3', 'elimination', 'Semifinal', 0, null, 'cbb0fa3f-00ed-54d8-bc76-f2dcff15ff3d', null, 'Ring 1', (timestamp '2026-09-12 11:21' at time zone 'America/Edmonton'), 8),
  ('303a2388-a2aa-57a2-964b-4f0291cffa5f', '729aeb14-31cb-5c88-8c01-c926003118b3', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 1', (timestamp '2026-09-12 11:31' at time zone 'America/Edmonton'), 8),
  ('6b598060-38cb-5d84-8763-62324195523a', '729aeb14-31cb-5c88-8c01-c926003118b3', 'final', 'Final', 0, null, null, null, 'Ring 1', (timestamp '2026-09-12 11:41' at time zone 'America/Edmonton'), 8),
  ('606b246b-e7c3-59e0-b768-c0ba60b236f2', '729aeb14-31cb-5c88-8c01-c926003118b3', 'third_place', 'Third place', 0, null, null, null, 'Ring 1', (timestamp '2026-09-12 11:51' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('36127629-7e9a-5984-b417-453244e66aba'::uuid, '26e02510-ba36-51d3-9461-b362d7fee37a'::uuid, 'b'),
  ('75026b22-1fc3-5042-93eb-79538a8a989c'::uuid, '303a2388-a2aa-57a2-964b-4f0291cffa5f'::uuid, 'a'),
  ('e2aba771-7b14-5e79-8629-64d69628b892'::uuid, '303a2388-a2aa-57a2-964b-4f0291cffa5f'::uuid, 'b'),
  ('26e02510-ba36-51d3-9461-b362d7fee37a'::uuid, '6b598060-38cb-5d84-8763-62324195523a'::uuid, 'a'),
  ('303a2388-a2aa-57a2-964b-4f0291cffa5f'::uuid, '6b598060-38cb-5d84-8763-62324195523a'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 5, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,3]},"totals":{"a":0,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '36127629-7e9a-5984-b417-453244e66aba' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 3, '{"kind":"duel","rounds":{"a":[1,2,3],"b":[2,0,1]},"totals":{"a":6,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '75026b22-1fc3-5042-93eb-79538a8a989c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[3,1],"b":[0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'e2aba771-7b14-5e79-8629-64d69628b892' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 6, '{"kind":"duel","rounds":{"a":[0,0],"b":[1,5]},"totals":{"a":0,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '26e02510-ba36-51d3-9461-b362d7fee37a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 9, '{"kind":"duel","rounds":{"a":[2,0],"b":[3,6]},"totals":{"a":2,"b":9}}'::jsonb, m.version) from public.matches m where m.id = '303a2388-a2aa-57a2-964b-4f0291cffa5f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[2,1],"b":[1,0]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '6b598060-38cb-5d84-8763-62324195523a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[0,2,2],"b":[1,0,0]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '606b246b-e7c3-59e0-b768-c0ba60b236f2' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '729aeb14-31cb-5c88-8c01-c926003118b3' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('729aeb14-31cb-5c88-8c01-c926003118b3') where tied group by part, rank loop perform public.record_tie_decision('729aeb14-31cb-5c88-8c01-c926003118b3', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('729aeb14-31cb-5c88-8c01-c926003118b3', 'tournament_structure') where exists (select 1 from public.competitions where id = '729aeb14-31cb-5c88-8c01-c926003118b3' and status <> 'finished');
-- Male Sword & Shield: elimination, 10 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('32f700bd-b92e-51fa-89fe-d360e07446c1', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Round of 16', 1, null, '318f709b-4575-5b93-8b6f-ff4b2c1955cc', '1c89ef7b-5729-51a0-9661-d601ad3f9d68', 'Ring 2', (timestamp '2026-09-12 11:42' at time zone 'America/Edmonton'), 8),
  ('985f7914-127a-5809-bd6c-c35836156392', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Round of 16', 5, null, '215fc1b1-1919-554b-8f5a-153803f7eb9e', '7999f0ce-9273-5d38-9f2f-708d99f811f5', 'Ring 2', (timestamp '2026-09-12 11:52' at time zone 'America/Edmonton'), 8),
  ('e0290c3d-5e8c-5d4f-8583-227f7c64f034', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Quarterfinal', 0, null, '55ad2026-b06d-58ad-bb32-2c8a1059ef2a', null, 'Ring 2', (timestamp '2026-09-12 12:02' at time zone 'America/Edmonton'), 8),
  ('9f0aabfd-b58c-50b9-94c4-307e274763b7', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Quarterfinal', 1, null, '3659fcad-a346-5f61-aba1-8b4a54cc510d', '3dfb80d4-abfc-5476-b8a2-781021d345c3', 'Ring 2', (timestamp '2026-09-12 12:12' at time zone 'America/Edmonton'), 8),
  ('175f103c-3f20-5002-b6fc-4431225a8952', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Quarterfinal', 2, null, 'c97a2f9f-d9f7-5074-81ae-a326c7531137', null, 'Ring 2', (timestamp '2026-09-12 12:22' at time zone 'America/Edmonton'), 8),
  ('866dea90-4e00-5a8c-9d1b-c2e419653122', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Quarterfinal', 3, null, 'a4490a84-a492-541a-b141-b4efff06e647', '307bc6b8-be73-5621-94bc-ddfcc0a502dc', 'Ring 2', (timestamp '2026-09-12 12:32' at time zone 'America/Edmonton'), 8),
  ('18fbc36b-f6be-50f7-8eda-ce90293d895a', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 2', (timestamp '2026-09-12 12:42' at time zone 'America/Edmonton'), 8),
  ('030eb04a-b5df-5402-b0ed-597aa15f2617', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 2', (timestamp '2026-09-12 12:52' at time zone 'America/Edmonton'), 8),
  ('a09aff62-24d6-5c85-a7ff-b41f91f2020e', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'final', 'Final', 0, null, null, null, 'Ring 2', (timestamp '2026-09-12 13:02' at time zone 'America/Edmonton'), 8),
  ('0b465d9b-24e9-5165-908d-dc2f9df209f9', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'third_place', 'Third place', 0, null, null, null, 'Ring 2', (timestamp '2026-09-12 13:12' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('32f700bd-b92e-51fa-89fe-d360e07446c1'::uuid, 'e0290c3d-5e8c-5d4f-8583-227f7c64f034'::uuid, 'b'),
  ('985f7914-127a-5809-bd6c-c35836156392'::uuid, '175f103c-3f20-5002-b6fc-4431225a8952'::uuid, 'b'),
  ('e0290c3d-5e8c-5d4f-8583-227f7c64f034'::uuid, '18fbc36b-f6be-50f7-8eda-ce90293d895a'::uuid, 'a'),
  ('9f0aabfd-b58c-50b9-94c4-307e274763b7'::uuid, '18fbc36b-f6be-50f7-8eda-ce90293d895a'::uuid, 'b'),
  ('175f103c-3f20-5002-b6fc-4431225a8952'::uuid, '030eb04a-b5df-5402-b0ed-597aa15f2617'::uuid, 'a'),
  ('866dea90-4e00-5a8c-9d1b-c2e419653122'::uuid, '030eb04a-b5df-5402-b0ed-597aa15f2617'::uuid, 'b'),
  ('18fbc36b-f6be-50f7-8eda-ce90293d895a'::uuid, 'a09aff62-24d6-5c85-a7ff-b41f91f2020e'::uuid, 'a'),
  ('030eb04a-b5df-5402-b0ed-597aa15f2617'::uuid, 'a09aff62-24d6-5c85-a7ff-b41f91f2020e'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 5, 2, '{"kind":"duel","rounds":{"a":[2,1,2],"b":[2,0,0]},"totals":{"a":5,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '32f700bd-b92e-51fa-89fe-d360e07446c1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 4, '{"kind":"duel","rounds":{"a":[4,0,2],"b":[1,2,1]},"totals":{"a":6,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '985f7914-127a-5809-bd6c-c35836156392' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[2,0],"b":[2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'e0290c3d-5e8c-5d4f-8583-227f7c64f034' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 9, '{"kind":"duel","rounds":{"a":[1,0],"b":[6,3]},"totals":{"a":1,"b":9}}'::jsonb, m.version) from public.matches m where m.id = '9f0aabfd-b58c-50b9-94c4-307e274763b7' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[1,3],"b":[2,0]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '175f103c-3f20-5002-b6fc-4431225a8952' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 7, 9, '{"kind":"duel","rounds":{"a":[1,1,1,3,1,0],"b":[1,0,2,3,2,1]},"totals":{"a":7,"b":9}}'::jsonb, m.version) from public.matches m where m.id = '866dea90-4e00-5a8c-9d1b-c2e419653122' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[2,0],"b":[3,2]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '18fbc36b-f6be-50f7-8eda-ce90293d895a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 4, 6, '{"kind":"duel","rounds":{"a":[1,1,2],"b":[0,3,3]},"totals":{"a":4,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '030eb04a-b5df-5402-b0ed-597aa15f2617' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[0,1,3],"b":[0,0,1]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = 'a09aff62-24d6-5c85-a7ff-b41f91f2020e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 5, '{"kind":"duel","rounds":{"a":[1,1],"b":[2,3]},"totals":{"a":2,"b":5}}'::jsonb, m.version) from public.matches m where m.id = '0b465d9b-24e9-5165-908d-dc2f9df209f9' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '42b52d0d-4876-5bbe-9102-812c0dc77222' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('42b52d0d-4876-5bbe-9102-812c0dc77222') where tied group by part, rank loop perform public.record_tie_decision('42b52d0d-4876-5bbe-9102-812c0dc77222', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('42b52d0d-4876-5bbe-9102-812c0dc77222', 'tournament_structure') where exists (select 1 from public.competitions where id = '42b52d0d-4876-5bbe-9102-812c0dc77222' and status <> 'finished');
-- Female Sword & Shield: elimination, 10 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('aa839740-47a6-50b1-a36b-350cf5df776a', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Round of 16', 1, null, 'fc30db42-8e1a-5b29-a32c-c22c1fa98131', '15c12771-09c5-5830-9842-8cb1da99b529', 'Ring 3', (timestamp '2026-09-12 11:42' at time zone 'America/Edmonton'), 8),
  ('8c73b44c-51c3-5052-b13f-cce14718f172', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Round of 16', 5, null, '403946d8-8c8c-5f70-adf2-a2d754838a21', 'c91dafc0-e4e9-501a-9d42-d47180107a44', 'Ring 3', (timestamp '2026-09-12 11:52' at time zone 'America/Edmonton'), 8),
  ('dc1d61e2-0a2f-587e-a2db-5733ae703581', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Quarterfinal', 0, null, 'a73913ee-479a-59bf-b735-4b2ddc60d9b1', null, 'Ring 3', (timestamp '2026-09-12 12:02' at time zone 'America/Edmonton'), 8),
  ('fe4938c4-463f-5935-80e7-ffdd93393af6', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Quarterfinal', 1, null, 'f9ee30ac-5eb5-5e41-abde-60c2fa5fbecc', 'b7db1d4d-93bc-5641-9e8a-b81007588819', 'Ring 3', (timestamp '2026-09-12 12:12' at time zone 'America/Edmonton'), 8),
  ('a60da249-1163-5877-9e5e-cb5aaaf85eda', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Quarterfinal', 2, null, 'fda9fba2-de73-5380-8c66-8dd84d8065f0', null, 'Ring 3', (timestamp '2026-09-12 12:22' at time zone 'America/Edmonton'), 8),
  ('b0103851-ccd2-507d-8259-4e118b49a745', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Quarterfinal', 3, null, 'd62eb267-8c22-5406-9fe8-c50c7e9e71e6', '3d6c657e-0800-5570-9b98-615d8487797c', 'Ring 3', (timestamp '2026-09-12 12:32' at time zone 'America/Edmonton'), 8),
  ('7c795cf3-6ed1-5af4-9490-7f64218c85e1', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 3', (timestamp '2026-09-12 12:42' at time zone 'America/Edmonton'), 8),
  ('20fd73e3-3818-5792-802a-2424af0c255c', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 3', (timestamp '2026-09-12 12:52' at time zone 'America/Edmonton'), 8),
  ('6cd28020-7e6a-5502-a7e9-127d454c2c1d', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'final', 'Final', 0, null, null, null, 'Ring 3', (timestamp '2026-09-12 13:02' at time zone 'America/Edmonton'), 8),
  ('11eade09-148a-5b4d-a55e-55b41a136560', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'third_place', 'Third place', 0, null, null, null, 'Ring 3', (timestamp '2026-09-12 13:12' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('aa839740-47a6-50b1-a36b-350cf5df776a'::uuid, 'dc1d61e2-0a2f-587e-a2db-5733ae703581'::uuid, 'b'),
  ('8c73b44c-51c3-5052-b13f-cce14718f172'::uuid, 'a60da249-1163-5877-9e5e-cb5aaaf85eda'::uuid, 'b'),
  ('dc1d61e2-0a2f-587e-a2db-5733ae703581'::uuid, '7c795cf3-6ed1-5af4-9490-7f64218c85e1'::uuid, 'a'),
  ('fe4938c4-463f-5935-80e7-ffdd93393af6'::uuid, '7c795cf3-6ed1-5af4-9490-7f64218c85e1'::uuid, 'b'),
  ('a60da249-1163-5877-9e5e-cb5aaaf85eda'::uuid, '20fd73e3-3818-5792-802a-2424af0c255c'::uuid, 'a'),
  ('b0103851-ccd2-507d-8259-4e118b49a745'::uuid, '20fd73e3-3818-5792-802a-2424af0c255c'::uuid, 'b'),
  ('7c795cf3-6ed1-5af4-9490-7f64218c85e1'::uuid, '6cd28020-7e6a-5502-a7e9-127d454c2c1d'::uuid, 'a'),
  ('20fd73e3-3818-5792-802a-2424af0c255c'::uuid, '6cd28020-7e6a-5502-a7e9-127d454c2c1d'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'b', 0, 3, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,1]},"totals":{"a":0,"b":3}}'::jsonb, m.version) from public.matches m where m.id = 'aa839740-47a6-50b1-a36b-350cf5df776a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 7, '{"kind":"duel","rounds":{"a":[0,0],"b":[4,3]},"totals":{"a":0,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '8c73b44c-51c3-5052-b13f-cce14718f172' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 4, '{"kind":"duel","rounds":{"a":[0,0],"b":[2,2]},"totals":{"a":0,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'dc1d61e2-0a2f-587e-a2db-5733ae703581' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 2, '{"kind":"duel","rounds":{"a":[0,4],"b":[0,2]},"totals":{"a":4,"b":2}}'::jsonb, m.version) from public.matches m where m.id = 'fe4938c4-463f-5935-80e7-ffdd93393af6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[0,2],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = 'a60da249-1163-5877-9e5e-cb5aaaf85eda' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 0, 7, '{"kind":"duel","rounds":{"a":[0,0],"b":[3,4]},"totals":{"a":0,"b":7}}'::jsonb, m.version) from public.matches m where m.id = 'b0103851-ccd2-507d-8259-4e118b49a745' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 10, 1, '{"kind":"duel","rounds":{"a":[4,6],"b":[1,0]},"totals":{"a":10,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '7c795cf3-6ed1-5af4-9490-7f64218c85e1' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 3, '{"kind":"duel","rounds":{"a":[1,5],"b":[1,2]},"totals":{"a":6,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '20fd73e3-3818-5792-802a-2424af0c255c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 9, 6, '{"kind":"duel","rounds":{"a":[4,1,1,1,2],"b":[2,2,1,1,0]},"totals":{"a":9,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '6cd28020-7e6a-5502-a7e9-127d454c2c1d' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 3, '{"kind":"duel","rounds":{"a":[3,2],"b":[0,3]},"totals":{"a":5,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '11eade09-148a-5b4d-a55e-55b41a136560' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '12d8e791-8b11-515e-be38-f0f1f1d9cddc' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('12d8e791-8b11-515e-be38-f0f1f1d9cddc') where tied group by part, rank loop perform public.record_tie_decision('12d8e791-8b11-515e-be38-f0f1f1d9cddc', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'tournament_structure') where exists (select 1 from public.competitions where id = '12d8e791-8b11-515e-be38-f0f1f1d9cddc' and status <> 'finished');
-- Male Polearm: elimination, 7 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('577f3417-ae5c-51a0-a8f2-2f13cf2f3aff', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'elimination', 'Quarterfinal', 1, null, '1c8cc372-676c-58ca-a941-660a0cad68d0', 'daefcffe-1df0-5e5b-87b4-edfbcc266445', 'Ring 4', (timestamp '2026-09-12 11:30' at time zone 'America/Edmonton'), 8),
  ('ce773852-b424-5331-ae53-0cd2decf84bd', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'elimination', 'Quarterfinal', 2, null, '34f704c4-a0a9-5e58-b31a-0fade42f835a', '60a5b8d3-2379-5e80-80c8-7d40d5d2ba75', 'Ring 4', (timestamp '2026-09-12 11:40' at time zone 'America/Edmonton'), 8),
  ('3d21071c-28d4-5f0a-b0fb-1027e66e7bad', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'elimination', 'Quarterfinal', 3, null, '7c246c07-b8ec-5c8d-9363-5247a675ed75', 'c5ccb820-350e-5b52-918d-52a5d314a442', 'Ring 4', (timestamp '2026-09-12 11:50' at time zone 'America/Edmonton'), 8),
  ('dcf4b811-ca5d-567e-9cf2-28722bc543bd', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'elimination', 'Semifinal', 0, null, '93310ee9-f945-52b1-a7e8-42db45bc19c5', null, 'Ring 4', (timestamp '2026-09-12 12:00' at time zone 'America/Edmonton'), 8),
  ('833411d4-a9af-580e-9695-21b3ac4c28f4', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 4', (timestamp '2026-09-12 12:10' at time zone 'America/Edmonton'), 8),
  ('6fd0da84-4e3b-5b6e-b7bf-c8f2fadbcf0e', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'final', 'Final', 0, null, null, null, 'Ring 4', (timestamp '2026-09-12 12:20' at time zone 'America/Edmonton'), 8),
  ('306a735f-3e39-5eba-9c09-e5ee0b5ce611', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'third_place', 'Third place', 0, null, null, null, 'Ring 4', (timestamp '2026-09-12 12:30' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('577f3417-ae5c-51a0-a8f2-2f13cf2f3aff'::uuid, 'dcf4b811-ca5d-567e-9cf2-28722bc543bd'::uuid, 'b'),
  ('ce773852-b424-5331-ae53-0cd2decf84bd'::uuid, '833411d4-a9af-580e-9695-21b3ac4c28f4'::uuid, 'a'),
  ('3d21071c-28d4-5f0a-b0fb-1027e66e7bad'::uuid, '833411d4-a9af-580e-9695-21b3ac4c28f4'::uuid, 'b'),
  ('dcf4b811-ca5d-567e-9cf2-28722bc543bd'::uuid, '6fd0da84-4e3b-5b6e-b7bf-c8f2fadbcf0e'::uuid, 'a'),
  ('833411d4-a9af-580e-9695-21b3ac4c28f4'::uuid, '6fd0da84-4e3b-5b6e-b7bf-c8f2fadbcf0e'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 3, 1, '{"kind":"duel","rounds":{"a":[2,1],"b":[1,0]},"totals":{"a":3,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '577f3417-ae5c-51a0-a8f2-2f13cf2f3aff' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 4, '{"kind":"duel","rounds":{"a":[1,2,2,1],"b":[1,2,1,0]},"totals":{"a":6,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ce773852-b424-5331-ae53-0cd2decf84bd' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 6, 2, '{"kind":"duel","rounds":{"a":[1,1,4],"b":[0,1,1]},"totals":{"a":6,"b":2}}'::jsonb, m.version) from public.matches m where m.id = '3d21071c-28d4-5f0a-b0fb-1027e66e7bad' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 6, '{"kind":"duel","rounds":{"a":[1,1,0],"b":[1,2,3]},"totals":{"a":2,"b":6}}'::jsonb, m.version) from public.matches m where m.id = 'dcf4b811-ca5d-567e-9cf2-28722bc543bd' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 2, 0, '{"kind":"duel","rounds":{"a":[1,1],"b":[0,0]},"totals":{"a":2,"b":0}}'::jsonb, m.version) from public.matches m where m.id = '833411d4-a9af-580e-9695-21b3ac4c28f4' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 6, 8, '{"kind":"duel","rounds":{"a":[2,1,3],"b":[3,1,4]},"totals":{"a":6,"b":8}}'::jsonb, m.version) from public.matches m where m.id = '6fd0da84-4e3b-5b6e-b7bf-c8f2fadbcf0e' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 6, '{"kind":"duel","rounds":{"a":[1,0,1],"b":[2,0,4]},"totals":{"a":2,"b":6}}'::jsonb, m.version) from public.matches m where m.id = '306a735f-3e39-5eba-9c09-e5ee0b5ce611' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('af6c8701-6ab1-5cba-85ad-8cfd826dc3b3') where tied group by part, rank loop perform public.record_tie_decision('af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'tournament_structure') where exists (select 1 from public.competitions where id = 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3' and status <> 'finished');
-- Female Polearm: elimination, 9 entries
insert into public.matches (id, competition_id, stage, round_label, position, pool, entry_a, entry_b, field, scheduled_at, duration_minutes) values
  ('3c40454f-6420-525a-92ea-4d40ed8b79b6', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Round of 16', 1, null, '9fdd8385-e05d-5a86-a5f8-fe888686f067', '6f0607ca-583d-5584-8a73-32efdea5b2e5', 'Ring 1', (timestamp '2026-09-12 12:01' at time zone 'America/Edmonton'), 8),
  ('682d9621-9eef-5361-8eb2-a7811ab0987f', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Quarterfinal', 0, null, '1ab0da7f-3dd7-5ecc-a983-a6f0ab21a062', null, 'Ring 1', (timestamp '2026-09-12 12:11' at time zone 'America/Edmonton'), 8),
  ('3219978f-b6da-5843-941f-ca24728c0ab9', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Quarterfinal', 1, null, 'a152064f-97c1-5791-ac06-5b425c434aa6', 'db241e7e-cc89-569c-abed-a3e9a5c0e7b9', 'Ring 1', (timestamp '2026-09-12 12:21' at time zone 'America/Edmonton'), 8),
  ('bd735d29-8c05-5cd3-8949-7bcf8d10d01c', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Quarterfinal', 2, null, 'c17c9fea-5782-5142-bd76-b606d29b0221', '516c0a46-6791-5903-b015-6f17a38ee275', 'Ring 1', (timestamp '2026-09-12 12:31' at time zone 'America/Edmonton'), 8),
  ('ae9e26cd-882e-5c54-9fe4-25ea91688672', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Quarterfinal', 3, null, '02016075-47f4-5be6-af74-7abc0eb539c0', '2cc21646-3cc8-5b94-8a12-07c0b23517bd', 'Ring 1', (timestamp '2026-09-12 12:41' at time zone 'America/Edmonton'), 8),
  ('9fe149b0-42ea-5829-a1c2-6f633efab149', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Semifinal', 0, null, null, null, 'Ring 1', (timestamp '2026-09-12 12:51' at time zone 'America/Edmonton'), 8),
  ('874facac-42a2-594d-bc29-dfef8454104a', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'elimination', 'Semifinal', 1, null, null, null, 'Ring 1', (timestamp '2026-09-12 13:01' at time zone 'America/Edmonton'), 8),
  ('9b386dd5-bd79-5d3b-b154-ad6fa676f9f6', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'final', 'Final', 0, null, null, null, 'Ring 1', (timestamp '2026-09-12 13:11' at time zone 'America/Edmonton'), 8),
  ('08230c1d-32e9-553f-840a-9de046a00922', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'third_place', 'Third place', 0, null, null, null, 'Ring 1', (timestamp '2026-09-12 13:21' at time zone 'America/Edmonton'), 8)
on conflict (id) do nothing;
update public.matches m set next_match_id = v.n, next_slot = v.s from (values
  ('3c40454f-6420-525a-92ea-4d40ed8b79b6'::uuid, '682d9621-9eef-5361-8eb2-a7811ab0987f'::uuid, 'b'),
  ('682d9621-9eef-5361-8eb2-a7811ab0987f'::uuid, '9fe149b0-42ea-5829-a1c2-6f633efab149'::uuid, 'a'),
  ('3219978f-b6da-5843-941f-ca24728c0ab9'::uuid, '9fe149b0-42ea-5829-a1c2-6f633efab149'::uuid, 'b'),
  ('bd735d29-8c05-5cd3-8949-7bcf8d10d01c'::uuid, '874facac-42a2-594d-bc29-dfef8454104a'::uuid, 'a'),
  ('ae9e26cd-882e-5c54-9fe4-25ea91688672'::uuid, '874facac-42a2-594d-bc29-dfef8454104a'::uuid, 'b'),
  ('9fe149b0-42ea-5829-a1c2-6f633efab149'::uuid, '9b386dd5-bd79-5d3b-b154-ad6fa676f9f6'::uuid, 'a'),
  ('874facac-42a2-594d-bc29-dfef8454104a'::uuid, '9b386dd5-bd79-5d3b-b154-ad6fa676f9f6'::uuid, 'b')
) v(id, n, s) where m.id = v.id and m.next_match_id is null;
select public.finalize_match(m.id, 'a', 7, 4, '{"kind":"duel","rounds":{"a":[1,3,1,2],"b":[3,1,0,0]},"totals":{"a":7,"b":4}}'::jsonb, m.version) from public.matches m where m.id = '3c40454f-6420-525a-92ea-4d40ed8b79b6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 5, 1, '{"kind":"duel","rounds":{"a":[2,0,3],"b":[1,0,0]},"totals":{"a":5,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '682d9621-9eef-5361-8eb2-a7811ab0987f' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 5, 7, '{"kind":"duel","rounds":{"a":[2,0,1,2,0,0,0],"b":[1,1,2,1,1,0,1]},"totals":{"a":5,"b":7}}'::jsonb, m.version) from public.matches m where m.id = '3219978f-b6da-5843-941f-ca24728c0ab9' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[1,1],"b":[3,1]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'bd735d29-8c05-5cd3-8949-7bcf8d10d01c' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 2, 4, '{"kind":"duel","rounds":{"a":[1,1],"b":[2,2]},"totals":{"a":2,"b":4}}'::jsonb, m.version) from public.matches m where m.id = 'ae9e26cd-882e-5c54-9fe4-25ea91688672' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[1,2]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '9fe149b0-42ea-5829-a1c2-6f633efab149' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 1, 3, '{"kind":"duel","rounds":{"a":[1,0],"b":[0,3]},"totals":{"a":1,"b":3}}'::jsonb, m.version) from public.matches m where m.id = '874facac-42a2-594d-bc29-dfef8454104a' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'b', 8, 10, '{"kind":"duel","rounds":{"a":[1,1,0,4,2],"b":[0,2,1,4,3]},"totals":{"a":8,"b":10}}'::jsonb, m.version) from public.matches m where m.id = '9b386dd5-bd79-5d3b-b154-ad6fa676f9f6' and m.queue_state <> 'final';
select public.finalize_match(m.id, 'a', 4, 1, '{"kind":"duel","rounds":{"a":[1,1,2],"b":[0,1,0]},"totals":{"a":4,"b":1}}'::jsonb, m.version) from public.matches m where m.id = '08230c1d-32e9-553f-840a-9de046a00922' and m.queue_state <> 'final';
do $$ declare g record; begin if exists (select 1 from public.competitions where id = '28c264b4-5c17-5990-a7d1-f5e505b6b798' and status <> 'finished') then for g in select part, array_agg(entry_id order by entry_id) as ents from public.pool_standings('28c264b4-5c17-5990-a7d1-f5e505b6b798') where tied group by part, rank loop perform public.record_tie_decision('28c264b4-5c17-5990-a7d1-f5e505b6b798', g.part, g.ents, 'Fictional dataset: tie settled by entry id'); end loop; end if; end $$;
select public.finish_competition('28c264b4-5c17-5990-a7d1-f5e505b6b798', 'tournament_structure') where exists (select 1 from public.competitions where id = '28c264b4-5c17-5990-a7d1-f5e505b6b798' and status <> 'finished');
reset role;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) values
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '9e464303-7e2f-5606-8224-dbba22e69349', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '38fe0d63-4153-5653-99f9-a88ee62214f9', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'd6d1573f-0109-5741-b867-6e6797a4e028', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '0f8661f9-6ec8-56d2-9e36-1278513c04d3', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '729aeb14-31cb-5c88-8c01-c926003118b3', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '42b52d0d-4876-5bbe-9102-812c0dc77222', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '12d8e791-8b11-515e-be38-f0f1f1d9cddc', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', 'af6c8701-6ab1-5cba-85ad-8cfd826dc3b3', 'unverified', 'NACL-test fictional dataset'),
  ('ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'competition', '28c264b4-5c17-5990-a7d1-f5e505b6b798', 'unverified', 'NACL-test fictional dataset')
on conflict do nothing;
insert into public.record_sources (source_id, entity_type, entity_id, status, note) select 'ac7ebfbe-8866-5e61-918e-0f3ae9fafab8', 'result', r.id, 'unverified', 'NACL-test fictional dataset' from public.results r join public.competitions c on c.id = r.competition_id where c.event_id = '4ce9cfd7-c876-5a1b-928b-ef86ded32066' on conflict do nothing;
update public.matches m set finalized_at = m.scheduled_at + make_interval(mins => m.duration_minutes) from public.competitions c where c.id = m.competition_id and c.event_id = '4ce9cfd7-c876-5a1b-928b-ef86ded32066' and m.queue_state = 'final';
update public.audit_log set at = (date '2026-09-13' + time '21:00') at time zone 'America/Edmonton' where event_id = '4ce9cfd7-c876-5a1b-928b-ef86ded32066';
commit;
