import { useEffect, useState } from 'react';
import { useAppState } from '../features/AppState';
import { claimFirstSuperAdmin, createEvent, createOrganization, createSeason, listEvents, listOrganizations, listSeasons, setOrganizationStatus, setSeasonStatus, updateOrganization, updateSeason, type SetupOrganization, type SetupSeason } from '../lib/setup';
import { isSupabaseConfigured } from '../lib/supabase';

const toIso = (value:string) => new Date(value).toISOString();
const initialYear = new Date().getFullYear();
const openEvent = (eventId:string) => { window.location.hash = `/ops?event=${encodeURIComponent(eventId)}`; };

export function SetupPage(){
  const {user}=useAppState();
  const [organizations,setOrganizations]=useState<SetupOrganization[]>([]);
  const [seasons,setSeasons]=useState<SetupSeason[]>([]);
  const [events,setEvents]=useState<Array<{id:string;name:string;venue:string;startsAt:string;status:string}>>([]);
  const [orgId,setOrgId]=useState('');
  const [seasonId,setSeasonId]=useState('');
  const [orgForm,setOrgForm]=useState({name:'',shortName:'',region:''});
  const [orgEdit,setOrgEdit]=useState({name:'',shortName:'',region:'',status:'active' as 'active'|'inactive'});
  const [seasonForm,setSeasonForm]=useState({name:`${initialYear} Season`,startsAt:`${initialYear}-01-01T09:00`,endsAt:`${initialYear}-12-31T18:00`});
  const [seasonEdit,setSeasonEdit]=useState({name:'',startsAt:'',endsAt:'',status:'draft'});
  const [eventForm,setEventForm]=useState({name:'',venue:'',startsAt:'',endsAt:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC',eventType:'ranked_competitive',standingsMode:'season_and_event'});
  const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const platformAdmin=Boolean(user?.platformRoles.includes('platform_super_admin'));
  const canCreateOrg=platformAdmin;

  const refreshOrgs=async()=>{const rows=await listOrganizations();setOrganizations(rows);if(!orgId&&rows[0])setOrgId(rows[0].id);};
  useEffect(()=>{if(user)refreshOrgs().catch(e=>setMessage(e.message));},[user?.userId]);
  useEffect(()=>{const org=organizations.find(item=>item.id===orgId);if(org)setOrgEdit({name:org.name,shortName:org.shortName,region:org.region,status:org.status});if(!orgId){setSeasons([]);setEvents([]);return;}listSeasons(orgId).then(rows=>{setSeasons(rows);if(!seasonId&&rows[0])setSeasonId(rows[0].id);}).catch(e=>setMessage(e.message));listEvents(orgId).then(setEvents).catch(e=>setMessage(e.message));},[orgId,organizations.length]);
  useEffect(()=>{const season=seasons.find(item=>item.id===seasonId);if(season)setSeasonEdit({name:season.name,startsAt:season.startsAt.slice(0,16),endsAt:season.endsAt.slice(0,16),status:season.status});},[seasonId,seasons.length]);
  if(!user)return <div className="state-card">Sign in before configuring BuhurtOS.</div>;
  if(!isSupabaseConfigured)return <div className="state-card">Demo mode already contains a seeded organization, season, and event. Connect a dedicated Supabase project to use first-run setup.</div>;

  const claim=async()=>{setBusy(true);setMessage('');try{const claimed=await claimFirstSuperAdmin();setMessage(claimed?'This account is now the initial platform super admin. Reloading access…':'A platform administrator already exists. Ask that administrator to add you.');if(claimed)window.setTimeout(()=>window.location.reload(),500);}catch(e){setMessage(e instanceof Error?e.message:'Unable to claim bootstrap role.');}finally{setBusy(false);}};
  const addOrg=async()=>{if(!orgForm.name||!orgForm.shortName||!orgForm.region)return;setBusy(true);try{const org=await createOrganization({...orgForm,userId:user.userId});await refreshOrgs();setOrgId(org.id);setOrgForm({name:'',shortName:'',region:''});setMessage('Organization created and you were assigned organization admin.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to create organization.');}finally{setBusy(false);}};
  const addSeason=async()=>{if(!orgId||!seasonForm.name)return;setBusy(true);try{const season=await createSeason({organizationId:orgId,name:seasonForm.name,startsAt:toIso(seasonForm.startsAt),endsAt:toIso(seasonForm.endsAt),userId:user.userId});const rows=await listSeasons(orgId);setSeasons(rows);setSeasonId(season.id);setMessage('Season created.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to create season.');}finally{setBusy(false);}};
  const saveOrg=async()=>{if(!orgId)return;setBusy(true);setMessage('');try{await updateOrganization({id:orgId,...orgEdit});await refreshOrgs();setMessage('Organization updated.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to update organization.');}finally{setBusy(false);}};
  const toggleOrgStatus=async()=>{if(!orgId)return;const next=orgEdit.status==='active'?'inactive':'active';if(next==='inactive'&&!window.confirm('Mark this organization inactive? Existing seasons, events, and history will be retained.'))return;setBusy(true);setMessage('');try{await setOrganizationStatus(orgId,next);await refreshOrgs();setOrgEdit(edit=>({...edit,status:next}));setMessage(next==='inactive'?'Organization marked inactive.':'Organization reactivated.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to change organization status.');}finally{setBusy(false);}};
  const saveSeason=async()=>{if(!orgId||!seasonId)return;setBusy(true);setMessage('');try{await updateSeason({id:seasonId,organizationId:orgId,name:seasonEdit.name,startsAt:toIso(seasonEdit.startsAt),endsAt:toIso(seasonEdit.endsAt),status:seasonEdit.status});setSeasons(await listSeasons(orgId));setMessage('Season updated.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to update season.');}finally{setBusy(false);}};
  const archiveSeason=async()=>{if(!orgId||!seasonId)return;if(!window.confirm('Archive this season? Events and results remain intact.'))return;setBusy(true);setMessage('');try{await setSeasonStatus(orgId,seasonId,'archived');setSeasons(await listSeasons(orgId));setSeasonEdit(edit=>({...edit,status:'archived'}));setMessage('Season archived without deleting history.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to archive season.');}finally{setBusy(false);}};
  const addEvent=async()=>{if(!orgId||!seasonId||!eventForm.name||!eventForm.venue||!eventForm.startsAt||!eventForm.endsAt)return;setBusy(true);try{const eventId=await createEvent({organizationId:orgId,seasonId,name:eventForm.name,venue:eventForm.venue,startsAt:toIso(eventForm.startsAt),endsAt:toIso(eventForm.endsAt),timezone:eventForm.timezone,eventType:eventForm.eventType as any,standingsMode:eventForm.standingsMode as any,userId:user.userId});openEvent(eventId);}catch(e){setMessage(e instanceof Error?e.message:'Unable to create event.');}finally{setBusy(false);}};

  return <><section className="section-head"><div><span className="eyebrow">First run & organization</span><h1>BuhurtOS Setup</h1><p>Create the tenant hierarchy without manual SQL. The first platform administrator claim only succeeds on a database that has no platform memberships.</p></div></section>
  {!platformAdmin&&user.organizationRoles.length===0&&<section className="panel-card setup-callout"><h2>Bootstrap first administrator</h2><p>If this is a brand new BuhurtOS database, claim the one-time platform administrator role. Once claimed, this path permanently closes.</p><button className="primary" disabled={busy} onClick={claim}>Claim First Platform Admin</button></section>}
  <div className="admin-grid">
    <section className="panel-card"><h2>Organization</h2><label className="form-stack">Current organization<select value={orgId} onChange={e=>{setOrgId(e.target.value);setSeasonId('');}}><option value="">Choose organization</option>{organizations.map(org=><option value={org.id} key={org.id}>{org.name}{org.status==='inactive'?' · inactive':''}</option>)}</select></label>{orgId&&<div className="form-stack setup-subform"><input placeholder="Organization name" value={orgEdit.name} onChange={e=>setOrgEdit(f=>({...f,name:e.target.value}))}/><input placeholder="Short name" value={orgEdit.shortName} onChange={e=>setOrgEdit(f=>({...f,shortName:e.target.value}))}/><input placeholder="Region" value={orgEdit.region} onChange={e=>setOrgEdit(f=>({...f,region:e.target.value}))}/><button onClick={saveOrg} disabled={busy}>Save Organization</button><button onClick={toggleOrgStatus} disabled={busy}>{orgEdit.status==='active'?'Mark Inactive':'Reactivate'}</button></div>}{canCreateOrg&&<div className="form-stack setup-subform"><h3>Create another organization</h3><input placeholder="Organization name" value={orgForm.name} onChange={e=>setOrgForm(f=>({...f,name:e.target.value}))}/><input placeholder="Short name" value={orgForm.shortName} onChange={e=>setOrgForm(f=>({...f,shortName:e.target.value}))}/><input placeholder="Region" value={orgForm.region} onChange={e=>setOrgForm(f=>({...f,region:e.target.value}))}/><button onClick={addOrg} disabled={busy}>Create Organization</button></div>}</section>
    <section className="panel-card"><h2>Season</h2><label className="form-stack">Current season<select value={seasonId} onChange={e=>setSeasonId(e.target.value)}><option value="">Choose season</option>{seasons.map(season=><option value={season.id} key={season.id}>{season.name} · {season.status}</option>)}</select></label>{seasonId&&<div className="form-stack setup-subform"><input value={seasonEdit.name} onChange={e=>setSeasonEdit(f=>({...f,name:e.target.value}))}/><label>Starts<input type="datetime-local" value={seasonEdit.startsAt} onChange={e=>setSeasonEdit(f=>({...f,startsAt:e.target.value}))}/></label><label>Ends<input type="datetime-local" value={seasonEdit.endsAt} onChange={e=>setSeasonEdit(f=>({...f,endsAt:e.target.value}))}/></label><label>Status<select value={seasonEdit.status} onChange={e=>setSeasonEdit(f=>({...f,status:e.target.value}))}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label><button onClick={saveSeason} disabled={busy}>Save Season</button>{seasonEdit.status!=='archived'&&<button onClick={archiveSeason} disabled={busy}>Archive Season</button>}</div>}{orgId&&<div className="form-stack setup-subform"><h3>Create another season</h3><input value={seasonForm.name} onChange={e=>setSeasonForm(f=>({...f,name:e.target.value}))}/><label>Starts<input type="datetime-local" value={seasonForm.startsAt} onChange={e=>setSeasonForm(f=>({...f,startsAt:e.target.value}))}/></label><label>Ends<input type="datetime-local" value={seasonForm.endsAt} onChange={e=>setSeasonForm(f=>({...f,endsAt:e.target.value}))}/></label><button onClick={addSeason} disabled={busy}>Create Season</button></div>}</section>
    <section className="panel-card"><h2>New event</h2><div className="form-stack"><input placeholder="Event name" value={eventForm.name} onChange={e=>setEventForm(f=>({...f,name:e.target.value}))}/><input placeholder="Venue" value={eventForm.venue} onChange={e=>setEventForm(f=>({...f,venue:e.target.value}))}/><label>Starts<input type="datetime-local" value={eventForm.startsAt} onChange={e=>setEventForm(f=>({...f,startsAt:e.target.value}))}/></label><label>Ends<input type="datetime-local" value={eventForm.endsAt} onChange={e=>setEventForm(f=>({...f,endsAt:e.target.value}))}/></label><label>Timezone<input value={eventForm.timezone} onChange={e=>setEventForm(f=>({...f,timezone:e.target.value}))}/></label><label>Event type<select value={eventForm.eventType} onChange={e=>setEventForm(f=>({...f,eventType:e.target.value}))}><option value="ranked_competitive">Ranked competitive</option><option value="demo_fun">Demo / fun</option><option value="exhibition">Exhibition</option><option value="clinic_training">Clinic / training</option><option value="custom">Custom</option></select></label><label>Standings<select value={eventForm.standingsMode} onChange={e=>setEventForm(f=>({...f,standingsMode:e.target.value}))}><option value="season_and_event">Season + event</option><option value="event_only">Event only</option><option value="no_standings">No standings</option></select></label><button className="primary" onClick={addEvent} disabled={busy||!seasonId}>Create Event</button></div></section>
    <section className="panel-card"><h2>Existing events</h2><div className="membership-list">{events.length===0?<div className="state-card">No events in this organization yet.</div>:events.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.venue} · {item.status}</small></div><button onClick={()=>openEvent(item.id)}>Open</button></article>)}</div></section>
  </div>{message&&<div className="auth-message">{message}</div>}</>;
}
