import { useState } from 'react';
import { demoEvents, demoFighters, demoTeams, liveMatches, upcomingMatches } from '../data/showcase';
import { Avatar, PageHeader, Panel, Pill, StatCard } from '../components/ShowcaseUI';

type EventTab='command'|'registration'|'checkin'|'schedule'|'competition'|'staff'|'settings';

export function ShowcaseEventPage(){
  const event=demoEvents[0];
  const [tab,setTab]=useState<EventTab>('command');
  const tabs:Array<[EventTab,string,string]>=[['command','Command','◫'],['registration','Registration','✎'],['checkin','Check-in','✓'],['schedule','Schedule','≡'],['competition','Pools & Brackets','⌘'],['staff','Staff','♟'],['settings','Settings','⚙']];
  return <>
    <PageHeader eyebrow="LIVE EVENT • HACSA SANCTIONED" title={event.name} description={event.date+' • '+event.venue+' • '+event.city} actions={<><button className="show-btn secondary">Public view ↗</button><button className="show-btn primary">Event actions ▾</button></>}/>
    <div className="show-event-statusbar"><Pill tone="red">● LIVE</Pill><span>Rules: <b>{event.ruleset}</b></span><span>Host: <b>{event.host}</b></span><span>3 fields reporting</span><span>Last sync 4 sec ago</span></div>
    <div className="show-event-tabs">{tabs.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}</div>
    {tab==='command'?<CommandTab/>:tab==='registration'?<RegistrationTab/>:tab==='checkin'?<CheckinTab/>:tab==='schedule'?<ScheduleTab/>:tab==='competition'?<CompetitionTab/>:tab==='staff'?<StaffTab/>:<SettingsTab/>}
  </>;
}

function CommandTab(){
  return <div className="show-stack">
    <div className="show-stat-grid"><StatCard label="Checked in" value="58 / 64" note="91% complete" tone="good"/><StatCard label="Matches complete" value="47 / 112" note="42% of fight card"/><StatCard label="Medical holds" value="1" note="Not eligible" tone="warn"/><StatCard label="Queue conflicts" value="0" note="All fields synced" tone="good"/></div>
    <div className="show-live-field-grid">{liveMatches.map(m=><Panel key={m.id} className="show-field-panel"><div className="show-field-head"><div><span className="show-live-dot"></span><b>{m.field}</b></div><Pill tone="red">{m.clock}</Pill></div><span className="eyebrow">{m.division} • {m.round}</span><div className="show-scoreboard"><div><strong>{m.left}</strong><span>{m.leftScore}</span></div><i>VS</i><div><strong>{m.right}</strong><span>{m.rightScore}</span></div></div><div className="show-field-actions"><button>Open marshal console</button><button>Field display ↗</button></div></Panel>)}</div>
    <div className="show-two-col wide-left"><Panel title="Up next across all fields" subtitle="Automatic field queue"><div className="show-schedule-list">{upcomingMatches.map((m,i)=><article key={i}><time>{m.time}</time><Pill>{m.field}</Pill><div><b>{m.left} <span>vs</span> {m.right}</b><small>{m.division}</small></div><button>Open</button></article>)}</div></Panel><Panel title="Operations feed" subtitle="Live event activity"><div className="show-feed"><article><span className="green">✓</span><div><b>Result finalized</b><small>Field 2 • Longsword QF • 20 sec ago</small></div></article><article><span className="amber">!</span><div><b>Medical hold applied</b><small>Fighter #0482 • 3 min ago</small></div></article><article><span className="blue">↻</span><div><b>Fight card reordered</b><small>Field 1 • Marshal station • 5 min ago</small></div></article><article><span className="purple">✉</span><div><b>Announcement published</b><small>Armor check call • 8 min ago</small></div></article></div></Panel></div>
  </div>;
}

function RegistrationTab(){
  return <div className="show-stack"><div className="show-stat-grid"><StatCard label="Total registrations" value="71" note="64 approved"/><StatCard label="Needs review" value="7" note="3 new • 4 changed" tone="warn"/><StatCard label="Paid" value="61" note="$4,575 collected" tone="good"/><StatCard label="Waivers complete" value="66" note="5 outstanding"/></div><Panel title="Registration review" subtitle="Approval creates or links permanent fighter records and event roster entries" actions={<div className="show-filter-row"><select><option>Needs review</option><option>Approved</option><option>Waitlisted</option></select><button className="show-btn secondary">Export</button></div>}><div className="show-review-list">{demoFighters.map((f,i)=><article key={f.id}><Avatar initials={f.name.split(' ').map(x=>x[0]).join('').slice(0,2)} tone={f.photoTone}/><div className="grow"><b>{f.name}</b><small>{demoTeams.find(t=>t.id===f.teamId)?.name} • {f.categories.slice(0,2).join(' • ')}</small></div><div className="show-review-flags">{i===2?<Pill tone="amber">Possible duplicate</Pill>:<Pill tone="green">Waiver ✓</Pill>}<Pill tone={i===1?'amber':'green'}>{i===1?'Payment pending':'Paid'}</Pill></div><button className="show-btn secondary">Review</button></article>)}</div></Panel></div>;
}

function CheckinTab(){
  const roster=[...demoFighters,...demoFighters.map((f,i)=>({...f,id:f.id+'-b',name:'Guest Fighter '+(i+11),fighterName:'Guest Fighter '+(i+11)}))];
  return <div className="show-stack"><div className="show-checkin-toolbar"><div><h2>Field readiness</h2><p>Competition is blocked until required clearances are complete.</p></div><div className="show-filter-row"><button className="show-btn primary">Scan QR</button><button className="show-btn secondary">Bulk check-in</button></div></div><div className="show-checkin-grid">{roster.map((f,i)=><article key={f.id}><div className="show-checkin-person"><Avatar initials={f.name.split(' ').map(x=>x[0]).join('').slice(0,2)} tone={f.photoTone}/><div><b>{f.name}</b><small>{demoTeams.find(t=>t.id===f.teamId)?.name??'Guest / mercenary'}</small></div><Pill tone={i===5?'amber':'green'}>{i===5?'Blocked':'Eligible'}</Pill></div><div className="show-clearance-grid">{['Check-in','Armor','Medical','Waiver','Weigh-in'].map((x,j)=><button className={(i===5&&j===1)?'missing':'done'} key={x}><span>{(i===5&&j===1)?'○':'✓'}</span>{x}</button>)}</div></article>)}</div></div>;
}

function ScheduleTab(){
  const rows=upcomingMatches.concat(upcomingMatches);
  return <Panel title="Master fight schedule" subtitle="Across three fields • explicit up/down controls replace fragile drag-and-drop"><div className="show-master-schedule">{rows.map((m,i)=><article key={i}><span className="show-order-num">{i+48}</span><time>{m.time}</time><Pill>{m.field}</Pill><div className="grow"><b>{m.left} <span>vs</span> {m.right}</b><small>{m.division} • {i<4?'Pool stage':'Bracket stage'}</small></div><div className="show-order-actions"><button>↑</button><button>↓</button></div><button className="show-kebab">•••</button></article>)}</div></Panel>;
}

function CompetitionTab(){
  return <div className="show-stack"><div className="show-competition-switch"><button className="active">5v5</button><button>Longsword</button><button>Sword & Buckler</button><button>Polearm</button><button>Profight</button></div><div className="show-two-col wide-left"><Panel title="5v5 Pool A" subtitle="Top two advance to championship bracket"><div className="show-pool-table"><div className="head"><span>Team</span><span>W</span><span>L</span><span>RD</span><span>Pts</span></div>{demoTeams.slice(0,4).map((t,i)=><div key={t.id}><b>{t.name}</b><span>{3-i}</span><span>{i}</span><span>{5-i*2>0?'+'+(5-i*2):5-i*2}</span><strong>{9-i*2}</strong></div>)}</div></Panel><Panel title="Advancement" subtitle="Automatic when pools lock"><div className="show-advance-flow"><div><small>POOL A #1</small><b>Red Deer Reavers</b></div><span>→</span><div><small>SEMIFINAL 1</small><b>vs Pool B #2</b></div><div><small>POOL A #2</small><b>Iron Wolves</b></div><span>→</span><div><small>SEMIFINAL 2</small><b>vs Pool B #1</b></div></div><button className="show-btn secondary full">Manual placement override</button></Panel></div><Panel title="Championship bracket" subtitle="Winner progression, byes, seeding and anti-fratricide visible at a glance"><div className="show-bracket-preview"><div className="round"><h4>Quarterfinals</h4>{['Reavers 2–0 Badlands','Vanguard 2–1 Iron Wolves','North Guard vs Wild Rose','Steel Legion vs Foothills'].map((x,i)=><span key={x} className={i<2?'done':''}>{x}</span>)}</div><div className="connector">›</div><div className="round"><h4>Semifinals</h4><span>Red Deer Reavers vs Northern Vanguard</span><span>Winner QF3 vs Winner QF4</span></div><div className="connector">›</div><div className="round final"><h4>Final</h4><span>Winner SF1 vs Winner SF2</span></div></div></Panel></div>;
}

function StaffTab(){
  const staff=[['Jordan Lee','Event Organizer','All event controls'],['Sam H.','Field Marshal','Fields 1–3'],['Taylor K.','Assistant Marshal','Field 2'],['Morgan P.','Medical Lead','Medical clearance'],['Garrett Robson','Team Captain','Red Deer Reavers']];
  return <div className="show-two-col"><Panel title="Event staff" subtitle="Role-scoped access"><div className="show-staff-list">{staff.map(([name,role,scope])=><article key={name}><Avatar initials={name.split(' ').map(x=>x[0]).join('').slice(0,2)} size="sm"/><div className="grow"><b>{name}</b><small>{role}</small></div><span>{scope}</span><button className="show-kebab">•••</button></article>)}</div><button className="show-btn primary">＋ Assign staff</button></Panel><Panel title="Access model"><div className="show-detail-rows"><div><span>Event organizers</span><b>2</b></div><div><span>Field marshals</span><b>5</b></div><div><span>Assistant marshals</span><b>8</b></div><div><span>Team captains</span><b>8</b></div><div><span>Medical</span><b>3</b></div></div><p className="show-helper">Each person only sees the controls and private information required for their event role.</p></Panel></div>;
}

function SettingsTab(){
  return <div className="show-profile-editor"><Panel title="Event identity"><div className="show-form-grid"><label>Event name<input defaultValue="HACSA Fall Open"/></label><label>Venue<input defaultValue="Springbrook Event Centre"/></label><label>Starts<input type="date" defaultValue="2026-09-26"/></label><label>Ends<input type="date" defaultValue="2026-09-27"/></label></div></Panel><Panel title="Governance & rules"><div className="show-form-grid"><label>Sanctioning organization<select defaultValue="hacsa"><option value="hacsa">HACSA</option></select></label><label>Ruleset<select><option>HACSA Rules 2026.3</option><option>BI International Rules 2026</option></select></label><label>Event type<select><option>Ranked competitive</option><option>Exhibition</option><option>Demo / fun</option></select></label><label>Standings<select><option>Season + event</option><option>Event only</option><option>No standings</option></select></label></div></Panel><Panel title="Public & stream"><div className="show-form-grid"><label>Livestream URL<input defaultValue="https://youtube.com/..."/></label><label>Public status<select><option>Live</option><option>Published</option><option>Private draft</option></select></label></div></Panel></div>;
}
