export type RuleGroup = 'buhurt' | 'duels' | 'outrance' | 'tournaments' | 'safety';
export interface Rule { title: string; kind: string; group: RuleGroup; doc: string; section: string; body: string; /** Extra search words people use that the text does not. */ keywords?: string }

/** Paraphrased from Buhurt International documents. Not official text; each item names its source. */
export const RULES: Rule[] = [
  { title: 'When is a fighter grounded?', kind: 'Group fight', group: 'buhurt', doc: 'Buhurt Rules V.26.4.1', section: '§1.3.1', body: 'A fighter is grounded when the torso, hip, arm, hand, knee or shield touches the ground, with only the two feet allowed. Also grounded: leaning on a grounded fighter with downward pressure, armour failure that removes its protective function, attacking, pushing or grappling without a weapon in hand, and yielding by kneeling.' },
  { title: 'When a fighter is not grounded', kind: 'Group fight', group: 'buhurt', doc: 'Buhurt Rules V.26.4.1', section: '§1.3.2', body: 'Not grounded: touching the ground with the edge of the shield, an open hand or a fist during or just after a successful takedown; touching the opponent they are falling with, except with torso, hips or buttocks; armour failure the remaining protection can compensate for; any part of a weapon touching the ground.' },
  { title: 'What wins a group fight', keywords: 'victory winning score point', kind: 'Group fight', group: 'buhurt', doc: 'Buhurt Rules V.26.4.1', section: '§1.2', body: "The grounded position of all the opposing team's fighters is the main victory criterion in group battles." },
  { title: 'Thrusting is prohibited', kind: 'Group fight · Duels', group: 'safety', doc: 'Buhurt Rules V.26.4.1', section: '§4.2', body: 'Any thrusting action with a weapon is prohibited, and so is the threat of one. The penalty applies regardless of intent: a verbal warning, yellow card or red card.' },
  { title: 'Prohibited strike zones', kind: 'All formats · Safety', group: 'safety', doc: 'Buhurt Rules V.26.4.1', section: '§6', body: 'No strikes to the front or back of the neck, the base of the skull (bottom third of the back of the helmet), the back of the knee, the groin, or the feet and ankles. Any body part that has lost its protection also becomes a prohibited zone.' },
  { title: 'Intentional passivity and inactive clinches', kind: 'Group fight', group: 'buhurt', doc: 'Buhurt Rules V.26.4.1', section: '§4.10', body: 'Stalling is prohibited. A clinch is inactive when the fighters throw weak strikes or no grappling aimed at grounding the opponent for 10 seconds or longer. Strikes with a fist, knees or shield do not count.' },
  { title: 'Losing a weapon', kind: 'Group fight', group: 'buhurt', doc: 'Buhurt Rules V.26.4.1', section: '§3.5', body: 'A fighter must hold a weapon with at least one hand. Without one they are disarmed and may not attack until the grip is restored. They may defend, take a reserve weapon they carry, take one from an ungrounded teammate or the distribution zone, or yield by kneeling.' },
  { title: 'Grounded fighters stay down', kind: 'Group fight', group: 'buhurt', doc: 'Buhurt Rules V.26.4.1', section: '§5.2', body: "Grounded fighters stay on the ground until the Knight Marshal calls 'All Rise', may not interfere with the fight, and keep a comfortable seated or lying position as a signal that they are not injured." },
  { title: 'Scoring: Sword and Shield', kind: 'Duels', group: 'duels', doc: 'Duels rules V.26.4', section: '§2.1.1', body: 'Head and torso strikes score 2 points. Legs, arms and hands score 1. Only blade strikes to legal zones count, and only when clear, deliberate and not effectively countered.' },
  { title: 'Scoring: Sword and Buckler', kind: 'Duels', group: 'duels', doc: 'Duels rules V.26.4', section: '§2.1.2 · §2.2.1', body: 'Every legal strike scores 1 point. A round goes to the first fighter to 5 points, or the higher score at the 1-minute limit. The first fighter to win 2 rounds wins the match. There is no break between rounds.' },
  { title: 'Scoring: Longsword', kind: 'Duels', group: 'duels', doc: 'Duels rules V.26.4', section: '§2.1.4', body: 'With two hands on the grip, head and torso score 2 and arms, legs and hands score 1. With one hand on the grip, every legal zone scores 1.' },
  { title: 'Scoring: Polearm', kind: 'Duels', group: 'duels', doc: 'Duels rules V.26.4', section: '§2.1.3', body: 'The full length of the cutting edge counts as the blade. Haft strikes do not score. The grip must be held with two hands. Hands score 0 and every other legal zone scores 1.' },
  { title: 'How a Sword and Shield, Longsword or Polearm match is won', kind: 'Duels', group: 'duels', doc: 'Duels rules V.26.4', section: '§2.2.2', body: 'Two main rounds of 1 minute. The match goes to whoever leads by at least 2 points over the total. If the gap is under 2, extra 30-second rounds are fought until it is reached. 30-second break between rounds.' },
  { title: 'Technical win', keywords: 'forfeit walkover default no-show', kind: 'Duels', group: 'duels', doc: 'Duels rules V.26.4', section: '§2.3', body: 'Awarded when the opponent withdraws, fails to report, cannot fix equipment within 1 minute, is injured by an illegal strike, or is disqualified (2 yellow cards or 1 red). The score is 5–0 for both rounds in Sword and Buckler and 10–0 per round otherwise.' },
  { title: 'Profight: rounds and breaks', kind: 'Profight', group: 'outrance', doc: 'Outrance Rules V.26.4', section: '§4', body: 'Matched fights in Division 1 are 3 rounds of 2 minutes with 1-minute breaks. Tournament fights are 2 rounds of 2 minutes with a 45-second break, and a third round if the fight is level. Division 2 rounds are 1 minute 30.' },
  { title: 'Profight: the 10-point must system', keywords: 'scoring score judging judges 10-9 10-8 10-7', kind: 'Profight', group: 'outrance', doc: 'Outrance Rules V.26.4', section: '§15.3', body: 'Each line marshal scores every round. Out-striking by 6 to 10 strike points is 10–9, by 11 to 15 is 10–8, and by 16 or more is 10–7. A yellow card, armour failure or weapon loss costs one point each. KO and TKO score 10–7.' },
  { title: 'Profight: what judges weigh, in order', kind: 'Profight', group: 'outrance', doc: 'Outrance Rules V.26.4', section: '§15.2', body: 'Effective striking, effective grappling, list control, aggression and defence. Each clean legal strike with a weapon, leg, arm or shield is one strike point. Head strikes award none.' },
  { title: 'Profight weight classes', kind: 'Profight', group: 'outrance', doc: 'Outrance Rules V.26.4', section: '§1.2', body: 'Men: lightweight to 75 kg, middleweight to 85, light heavyweight to 95, heavyweight to 105, super heavyweight to 115, ultra heavyweight above. Women: featherweight to 60 kg, lightweight to 70, middleweight to 80, light heavyweight to 90, heavyweight above.' },
  { title: 'Tie in a pool or round robin', keywords: 'tiebreak tiebreaker tie-break tie break standings', kind: 'Tournaments', group: 'tournaments', doc: 'Tournament Structure and Formats (Jan 2026)', section: '§3', body: 'Break ties in order: head-to-head result when two are tied; round wins minus losses (group fights and buckler) or hits earned against hits received (other duels); active against downed competitors; fewest penalties.' },
  { title: 'Choosing a format for 6 to 12 entrants', kind: 'Tournaments', group: 'tournaments', doc: 'Tournament Structure and Formats (Jan 2026)', section: '§1.4', body: 'Either one round robin, or pools of 3 to 6 where the top two from each advance to the semifinals. The final four then play a round robin or a single-elimination bracket with a 3rd and 4th place match.' },
  { title: 'Registration deadlines', kind: 'Tournaments', group: 'tournaments', doc: 'Tournament Structure and Formats (Jan 2026)', section: '§1.1', body: 'Registration closes at least 15 days before the event. Events register with BI at least six weeks before they start. A double-elimination bracket must be declared before fees are collected.' },
  { title: 'List size and safety zone', kind: 'Group fight · Duels · Profight', group: 'safety', doc: 'Buhurt Regulations V.26.4 · Duels Regulations V.26.4', section: '§1.2', body: 'Rail height is 0.9 to 1.3 m and a fenced 2 m safety zone surrounds the list. Group fight lists: 3v3 7–20 × 5–15 m, 5v5 9–20 × 7–15 m, 12v12 15–20 × 7–15 m, 30v30 25–30 × 12.5–20 m. Duel and profight lists are 5 to 10 m.' }
];
